# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/arch/cv_ov5640.xdc

# XDC: imports/arch/pynq-z2_v1.0.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_intc_0/design_1_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_intc_0 || ORIG_REF_NAME==design_1_axi_intc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_camera_reset_0/design_1_camera_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_camera_reset_0 || ORIG_REF_NAME==design_1_camera_reset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_Encoder_0_0/design_1_AXI_Encoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_Encoder_0_0 || ORIG_REF_NAME==design_1_AXI_Encoder_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_Encoder_1_0/design_1_AXI_Encoder_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_Encoder_1_0 || ORIG_REF_NAME==design_1_AXI_Encoder_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_PWM_Servo_0/design_1_AXI_PWM_Servo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_PWM_Servo_0 || ORIG_REF_NAME==design_1_AXI_PWM_Servo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_ultrasonic_ranger_0_0/design_1_AXI_ultrasonic_ranger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_ultrasonic_ranger_0_0 || ORIG_REF_NAME==design_1_AXI_ultrasonic_ranger_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_analog2digital_0_0/design_1_analog2digital_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_analog2digital_0_0 || ORIG_REF_NAME==design_1_analog2digital_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_arduino_gpio_0/design_1_arduino_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_arduino_gpio_0 || ORIG_REF_NAME==design_1_arduino_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_1/design_1_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_1 || ORIG_REF_NAME==design_1_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_en_reset_vector_0_0/design_1_dff_en_reset_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dff_en_reset_vector_0_0 || ORIG_REF_NAME==design_1_dff_en_reset_vector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_intr_0/design_1_intr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_intr_0 || ORIG_REF_NAME==design_1_intr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_io_switch_0/design_1_io_switch_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_io_switch_0 || ORIG_REF_NAME==design_1_io_switch_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_logic_1_0/design_1_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_logic_1_0 || ORIG_REF_NAME==design_1_logic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mb_0/design_1_mb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mb_0 || ORIG_REF_NAME==design_1_mb_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mb_bram_ctrl_0/design_1_mb_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mb_bram_ctrl_0 || ORIG_REF_NAME==design_1_mb_bram_ctrl_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mb_intc_0/design_1_mb_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mb_intc_0 || ORIG_REF_NAME==design_1_mb_intc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_PWM_Motor_0/design_1_AXI_PWM_Motor_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_PWM_Motor_0 || ORIG_REF_NAME==design_1_AXI_PWM_Motor_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0/design_1_axi_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0 || ORIG_REF_NAME==design_1_axi_interconnect_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_motor_ctrl_sel_0_0/design_1_axi_motor_ctrl_sel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_motor_ctrl_sel_0_0 || ORIG_REF_NAME==design_1_axi_motor_ctrl_sel_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_PWM_Motor_1/design_1_AXI_PWM_Motor_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_PWM_Motor_1 || ORIG_REF_NAME==design_1_AXI_PWM_Motor_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_1/design_1_axi_interconnect_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_1 || ORIG_REF_NAME==design_1_axi_interconnect_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_motor_ctrl_sel_0_1/design_1_axi_motor_ctrl_sel_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_motor_ctrl_sel_0_1 || ORIG_REF_NAME==design_1_axi_motor_ctrl_sel_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0/design_1_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_timer_0_0/design_1_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_timer_0_0 || ORIG_REF_NAME==design_1_timer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_timer_1_0/design_1_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_timer_1_0 || ORIG_REF_NAME==design_1_timer_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_timer_intr_0/design_1_timer_intr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_timer_intr_0 || ORIG_REF_NAME==design_1_timer_intr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_PWM_0/design_1_xlconcat_PWM_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_PWM_0 || ORIG_REF_NAME==design_1_xlconcat_PWM_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_image_process_reset_0/design_1_image_process_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_image_process_reset_0 || ORIG_REF_NAME==design_1_image_process_reset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Canny_accel_0_0/design_1_Canny_accel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Canny_accel_0_0 || ORIG_REF_NAME==design_1_Canny_accel_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SobelX_accel_0_0/design_1_SobelX_accel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SobelX_accel_0_0 || ORIG_REF_NAME==design_1_SobelX_accel_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SobelY_accel_0_0/design_1_SobelY_accel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SobelY_accel_0_0 || ORIG_REF_NAME==design_1_SobelY_accel_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_proc_0/design_1_axi_dma_proc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_proc_0 || ORIG_REF_NAME==design_1_axi_dma_proc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_4/design_1_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_4 || ORIG_REF_NAME==design_1_xbar_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_2/design_1_axi_interconnect_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_2 || ORIG_REF_NAME==design_1_axi_interconnect_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_5 || ORIG_REF_NAME==design_1_xbar_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_back_0/design_1_axis_interconnect_back_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_back_0 || ORIG_REF_NAME==design_1_axis_interconnect_back_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_6/design_1_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_6 || ORIG_REF_NAME==design_1_xbar_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_front_0/design_1_axis_interconnect_front_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_front_0 || ORIG_REF_NAME==design_1_axis_interconnect_front_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_0 || ORIG_REF_NAME==design_1_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_1_0/design_1_axis_subset_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_1_0 || ORIG_REF_NAME==design_1_axis_subset_converter_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_2_0/design_1_axis_subset_converter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_2_0 || ORIG_REF_NAME==design_1_axis_subset_converter_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_3_0/design_1_axis_subset_converter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_3_0 || ORIG_REF_NAME==design_1_axis_subset_converter_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_4_0/design_1_axis_subset_converter_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_4_0 || ORIG_REF_NAME==design_1_axis_subset_converter_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_5_0/design_1_axis_subset_converter_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_5_0 || ORIG_REF_NAME==design_1_axis_subset_converter_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_color_detect_0/design_1_color_detect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_color_detect_0 || ORIG_REF_NAME==design_1_color_detect_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_logic_1_1/design_1_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_logic_1_1 || ORIG_REF_NAME==design_1_logic_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pixel_pack_0/design_1_pixel_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pixel_pack_0 || ORIG_REF_NAME==design_1_pixel_pack_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pixel_unpack_0/design_1_pixel_unpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pixel_unpack_0 || ORIG_REF_NAME==design_1_pixel_unpack_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_interrupt_0/design_1_interrupt_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_interrupt_0 || ORIG_REF_NAME==design_1_interrupt_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mb_car_iop_arduino_intr_ack_0/design_1_mb_car_iop_arduino_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mb_car_iop_arduino_intr_ack_0 || ORIG_REF_NAME==design_1_mb_car_iop_arduino_intr_ack_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mb_car_iop_arduino_reset_0/design_1_mb_car_iop_arduino_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mb_car_iop_arduino_reset_0 || ORIG_REF_NAME==design_1_mb_car_iop_arduino_reset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_0_0/design_1_mdm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_0_0 || ORIG_REF_NAME==design_1_mdm_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_a0_demosaic_0/design_1_a0_demosaic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_a0_demosaic_0 || ORIG_REF_NAME==design_1_a0_demosaic_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_7/design_1_xbar_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_7 || ORIG_REF_NAME==design_1_xbar_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_3/design_1_axi_interconnect_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_3 || ORIG_REF_NAME==design_1_axi_interconnect_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_sccb_0/design_1_axi_sccb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_sccb_0 || ORIG_REF_NAME==design_1_axi_sccb_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_cam_0/design_1_axi_vdma_cam_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_cam_0 || ORIG_REF_NAME==design_1_axi_vdma_cam_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_8/design_1_xbar_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_8 || ORIG_REF_NAME==design_1_xbar_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_back_1/design_1_axis_interconnect_back_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_back_1 || ORIG_REF_NAME==design_1_axis_interconnect_back_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_9/design_1_xbar_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_9 || ORIG_REF_NAME==design_1_xbar_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_front_1/design_1_axis_interconnect_front_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_front_1 || ORIG_REF_NAME==design_1_axis_interconnect_front_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_gbr2rgb_0/design_1_gbr2rgb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_gbr2rgb_0 || ORIG_REF_NAME==design_1_gbr2rgb_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_logic0_0/design_1_logic0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_logic0_0 || ORIG_REF_NAME==design_1_logic0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_logic1_0/design_1_logic1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_logic1_0 || ORIG_REF_NAME==design_1_logic1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pixel_pack_1/design_1_pixel_pack_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pixel_pack_1 || ORIG_REF_NAME==design_1_pixel_pack_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2gray_0_0/design_1_rgb2gray_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2gray_0_0 || ORIG_REF_NAME==design_1_rgb2gray_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_subset_cvt_0/design_1_subset_cvt_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_subset_cvt_0 || ORIG_REF_NAME==design_1_subset_cvt_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==design_1_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_100m_0/design_1_proc_sys_reset_100m_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_100m_0 || ORIG_REF_NAME==design_1_proc_sys_reset_100m_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RGBA2GBR_0/design_1_RGBA2GBR_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RGBA2GBR_0 || ORIG_REF_NAME==design_1_RGBA2GBR_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_10/design_1_xbar_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_10 || ORIG_REF_NAME==design_1_xbar_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_4/design_1_axi_interconnect_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_4 || ORIG_REF_NAME==design_1_axi_interconnect_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_vdma_0/design_1_axi_vdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0 || ORIG_REF_NAME==design_1_axi_vdma_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pixel_unpack_1/design_1_pixel_unpack_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pixel_unpack_1 || ORIG_REF_NAME==design_1_pixel_unpack_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2dvi_0/design_1_rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0 || ORIG_REF_NAME==design_1_rgb2dvi_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_0 || ORIG_REF_NAME==design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_k_1/design_1_auto_ss_k_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_k_1 || ORIG_REF_NAME==design_1_auto_ss_k_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slid_0/design_1_auto_ss_slid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slid_0 || ORIG_REF_NAME==design_1_auto_ss_slid_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_u_0/design_1_auto_ss_u_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_u_0 || ORIG_REF_NAME==design_1_auto_ss_u_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slid_1/design_1_auto_ss_slid_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slid_1 || ORIG_REF_NAME==design_1_auto_ss_slid_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_u_1/design_1_auto_ss_u_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_u_1 || ORIG_REF_NAME==design_1_auto_ss_u_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slid_2/design_1_auto_ss_slid_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slid_2 || ORIG_REF_NAME==design_1_auto_ss_slid_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_u_2/design_1_auto_ss_u_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_u_2 || ORIG_REF_NAME==design_1_auto_ss_u_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_k_0/design_1_auto_ss_k_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_k_0 || ORIG_REF_NAME==design_1_auto_ss_k_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_k_2/design_1_auto_ss_k_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_k_2 || ORIG_REF_NAME==design_1_auto_ss_k_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slidr_0/design_1_auto_ss_slidr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slidr_0 || ORIG_REF_NAME==design_1_auto_ss_slidr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_u_3/design_1_auto_ss_u_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_u_3 || ORIG_REF_NAME==design_1_auto_ss_u_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_k_3/design_1_auto_ss_k_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_k_3 || ORIG_REF_NAME==design_1_auto_ss_k_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slidr_1/design_1_auto_ss_slidr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slidr_1 || ORIG_REF_NAME==design_1_auto_ss_slidr_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_u_4/design_1_auto_ss_u_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_u_4 || ORIG_REF_NAME==design_1_auto_ss_u_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_k_4/design_1_auto_ss_k_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_k_4 || ORIG_REF_NAME==design_1_auto_ss_k_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slidr_2/design_1_auto_ss_slidr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slidr_2 || ORIG_REF_NAME==design_1_auto_ss_slidr_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_u_5/design_1_auto_ss_u_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_u_5 || ORIG_REF_NAME==design_1_auto_ss_u_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_k_5/design_1_auto_ss_k_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_k_5 || ORIG_REF_NAME==design_1_auto_ss_k_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slidr_3/design_1_auto_ss_slidr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slidr_3 || ORIG_REF_NAME==design_1_auto_ss_slidr_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slid_3/design_1_auto_ss_slid_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slid_3 || ORIG_REF_NAME==design_1_auto_ss_slid_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_k_6/design_1_auto_ss_k_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_k_6 || ORIG_REF_NAME==design_1_auto_ss_k_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slid_4/design_1_auto_ss_slid_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slid_4 || ORIG_REF_NAME==design_1_auto_ss_slid_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slidr_4/design_1_auto_ss_slidr_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slidr_4 || ORIG_REF_NAME==design_1_auto_ss_slidr_4} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
