-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Canny_accel is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM0_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM0_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM0_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM1_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM1_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM0_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM0_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_GMEM1_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM1_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM1_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ADDR_WIDTH-1 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH-1 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_WUSER_WIDTH-1 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ADDR_WIDTH-1 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH-1 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_RUSER_WIDTH-1 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_BUSER_WIDTH-1 downto 0);
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ADDR_WIDTH-1 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH-1 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_WUSER_WIDTH-1 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ADDR_WIDTH-1 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH-1 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_RUSER_WIDTH-1 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_BUSER_WIDTH-1 downto 0) );
end;


architecture behav of Canny_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Canny_accel,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=580,HLS_SYN_DSP=18,HLS_SYN_FF=3033,HLS_SYN_LUT=4581,HLS_VERSION=2018_3}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_S_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_S_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_ID_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_M_AXI_AWUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ARUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_WUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_RUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_BUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal img_inp_V : STD_LOGIC_VECTOR (31 downto 0);
    signal img_out_V : STD_LOGIC_VECTOR (31 downto 0);
    signal rows : STD_LOGIC_VECTOR (31 downto 0);
    signal cols : STD_LOGIC_VECTOR (31 downto 0);
    signal low_threshold : STD_LOGIC_VECTOR (31 downto 0);
    signal high_threshold : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem0_AWREADY : STD_LOGIC;
    signal gmem0_WREADY : STD_LOGIC;
    signal gmem0_ARREADY : STD_LOGIC;
    signal gmem0_RVALID : STD_LOGIC;
    signal gmem0_RDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem0_RLAST : STD_LOGIC;
    signal gmem0_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem0_BVALID : STD_LOGIC;
    signal gmem0_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem0_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem1_AWREADY : STD_LOGIC;
    signal gmem1_WREADY : STD_LOGIC;
    signal gmem1_ARREADY : STD_LOGIC;
    signal gmem1_RVALID : STD_LOGIC;
    signal gmem1_RDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem1_RLAST : STD_LOGIC;
    signal gmem1_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem1_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem1_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem1_BVALID : STD_LOGIC;
    signal gmem1_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem1_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem1_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal imgInput_data_V_i_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal imgInput_data_V_t_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal imgOutput_data_V_i_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal imgOutput_data_V_t_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal Block_Mat_exit45_pro_U0_ap_start : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_ap_done : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_ap_continue : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_ap_idle : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_ap_ready : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_imgInput_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit45_pro_U0_imgInput_rows_out_write : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_imgInput_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit45_pro_U0_imgInput_cols_out_write : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_imgOutput_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit45_pro_U0_imgOutput_rows_out_write : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_imgOutput_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit45_pro_U0_imgOutput_cols_out_write : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_low_threshold_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit45_pro_U0_low_threshold_out_write : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_img_inp_V_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit45_pro_U0_img_inp_V_out_write : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_img_out_V_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_Mat_exit45_pro_U0_img_out_V_out_write : STD_LOGIC;
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWVALID : STD_LOGIC;
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_WVALID : STD_LOGIC;
    signal Array2xfMat_U0_m_axi_srcPtr_V_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_WLAST : STD_LOGIC;
    signal Array2xfMat_U0_m_axi_srcPtr_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARVALID : STD_LOGIC;
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Array2xfMat_U0_m_axi_srcPtr_V_RREADY : STD_LOGIC;
    signal Array2xfMat_U0_m_axi_srcPtr_V_BREADY : STD_LOGIC;
    signal Array2xfMat_U0_srcPtr_V_offset_read : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_rows_read : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_cols_read : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_data_V_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal Array2xfMat_U0_dstMat_data_V_ce0 : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_data_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Array2xfMat_U0_dstMat_data_V_we0 : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_data_V_address1 : STD_LOGIC_VECTOR (19 downto 0);
    signal Array2xfMat_U0_dstMat_data_V_ce1 : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_data_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal Array2xfMat_U0_dstMat_data_V_we1 : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Array2xfMat_U0_dstMat_rows_out_write : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Array2xfMat_U0_dstMat_cols_out_write : STD_LOGIC;
    signal Array2xfMat_U0_ap_start : STD_LOGIC;
    signal Array2xfMat_U0_ap_done : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_data_V_full_n : STD_LOGIC;
    signal Array2xfMat_U0_dstMat_data_V_write : STD_LOGIC;
    signal Array2xfMat_U0_ap_ready : STD_LOGIC;
    signal Array2xfMat_U0_ap_idle : STD_LOGIC;
    signal Array2xfMat_U0_ap_continue : STD_LOGIC;
    signal ap_channel_done_imgInput_data_V : STD_LOGIC;
    signal binary_threshold_U0_ap_start : STD_LOGIC;
    signal binary_threshold_U0_ap_done : STD_LOGIC;
    signal binary_threshold_U0_ap_continue : STD_LOGIC;
    signal binary_threshold_U0_ap_idle : STD_LOGIC;
    signal binary_threshold_U0_ap_ready : STD_LOGIC;
    signal binary_threshold_U0_src_rows_read : STD_LOGIC;
    signal binary_threshold_U0_src_cols_read : STD_LOGIC;
    signal binary_threshold_U0_src_data_V_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal binary_threshold_U0_src_data_V_ce0 : STD_LOGIC;
    signal binary_threshold_U0_dst_data_V_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal binary_threshold_U0_dst_data_V_ce0 : STD_LOGIC;
    signal binary_threshold_U0_dst_data_V_we0 : STD_LOGIC;
    signal binary_threshold_U0_dst_data_V_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal binary_threshold_U0_threshold_read : STD_LOGIC;
    signal ap_channel_done_imgOutput_data_V : STD_LOGIC;
    signal binary_threshold_U0_dst_data_V_full_n : STD_LOGIC;
    signal xfMat2Array_U0_srcMat_rows_read : STD_LOGIC;
    signal xfMat2Array_U0_srcMat_cols_read : STD_LOGIC;
    signal xfMat2Array_U0_srcMat_data_V_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal xfMat2Array_U0_srcMat_data_V_ce0 : STD_LOGIC;
    signal xfMat2Array_U0_srcMat_data_V_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_srcMat_data_V_we0 : STD_LOGIC;
    signal xfMat2Array_U0_srcMat_data_V_address1 : STD_LOGIC_VECTOR (19 downto 0);
    signal xfMat2Array_U0_srcMat_data_V_ce1 : STD_LOGIC;
    signal xfMat2Array_U0_srcMat_data_V_d1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_srcMat_data_V_we1 : STD_LOGIC;
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWVALID : STD_LOGIC;
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_WVALID : STD_LOGIC;
    signal xfMat2Array_U0_m_axi_dstPtr_V_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_WLAST : STD_LOGIC;
    signal xfMat2Array_U0_m_axi_dstPtr_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARVALID : STD_LOGIC;
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2Array_U0_m_axi_dstPtr_V_RREADY : STD_LOGIC;
    signal xfMat2Array_U0_m_axi_dstPtr_V_BREADY : STD_LOGIC;
    signal xfMat2Array_U0_dstPtr_V_offset_read : STD_LOGIC;
    signal xfMat2Array_U0_srcMat_data_V_read : STD_LOGIC;
    signal xfMat2Array_U0_ap_start : STD_LOGIC;
    signal xfMat2Array_U0_ap_done : STD_LOGIC;
    signal xfMat2Array_U0_ap_ready : STD_LOGIC;
    signal xfMat2Array_U0_ap_idle : STD_LOGIC;
    signal xfMat2Array_U0_ap_continue : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal imgInput_data_V_i_full_n : STD_LOGIC;
    signal imgInput_data_V_t_empty_n : STD_LOGIC;
    signal imgOutput_data_V_i_full_n : STD_LOGIC;
    signal imgOutput_data_V_t_empty_n : STD_LOGIC;
    signal imgInput_rows_c_full_n : STD_LOGIC;
    signal imgInput_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal imgInput_rows_c_empty_n : STD_LOGIC;
    signal imgInput_cols_c_full_n : STD_LOGIC;
    signal imgInput_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal imgInput_cols_c_empty_n : STD_LOGIC;
    signal imgOutput_rows_c_full_n : STD_LOGIC;
    signal imgOutput_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal imgOutput_rows_c_empty_n : STD_LOGIC;
    signal imgOutput_cols_c_full_n : STD_LOGIC;
    signal imgOutput_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal imgOutput_cols_c_empty_n : STD_LOGIC;
    signal low_threshold_c_full_n : STD_LOGIC;
    signal low_threshold_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal low_threshold_c_empty_n : STD_LOGIC;
    signal img_inp_V_c_full_n : STD_LOGIC;
    signal img_inp_V_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_inp_V_c_empty_n : STD_LOGIC;
    signal img_out_V_c_full_n : STD_LOGIC;
    signal img_out_V_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_out_V_c_empty_n : STD_LOGIC;
    signal imgInput_rows_c13_full_n : STD_LOGIC;
    signal imgInput_rows_c13_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal imgInput_rows_c13_empty_n : STD_LOGIC;
    signal imgInput_cols_c14_full_n : STD_LOGIC;
    signal imgInput_cols_c14_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal imgInput_cols_c14_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_Block_Mat_exit45_pro_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Block_Mat_exit45_pro_U0_ap_ready : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_Array2xfMat_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Array2xfMat_U0_ap_ready : STD_LOGIC;
    signal Array2xfMat_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal Block_Mat_exit45_pro_U0_start_full_n : STD_LOGIC;
    signal Block_Mat_exit45_pro_U0_start_write : STD_LOGIC;
    signal Array2xfMat_U0_start_full_n : STD_LOGIC;
    signal Array2xfMat_U0_start_write : STD_LOGIC;
    signal binary_threshold_U0_start_full_n : STD_LOGIC;
    signal binary_threshold_U0_start_write : STD_LOGIC;
    signal xfMat2Array_U0_start_full_n : STD_LOGIC;
    signal xfMat2Array_U0_start_write : STD_LOGIC;

    component Block_Mat_exit45_pro IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rows : IN STD_LOGIC_VECTOR (31 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        low_threshold : IN STD_LOGIC_VECTOR (31 downto 0);
        imgInput_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        imgInput_rows_out_full_n : IN STD_LOGIC;
        imgInput_rows_out_write : OUT STD_LOGIC;
        imgInput_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        imgInput_cols_out_full_n : IN STD_LOGIC;
        imgInput_cols_out_write : OUT STD_LOGIC;
        imgOutput_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        imgOutput_rows_out_full_n : IN STD_LOGIC;
        imgOutput_rows_out_write : OUT STD_LOGIC;
        imgOutput_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        imgOutput_cols_out_full_n : IN STD_LOGIC;
        imgOutput_cols_out_write : OUT STD_LOGIC;
        low_threshold_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        low_threshold_out_full_n : IN STD_LOGIC;
        low_threshold_out_write : OUT STD_LOGIC;
        img_inp_V : IN STD_LOGIC_VECTOR (31 downto 0);
        img_out_V : IN STD_LOGIC_VECTOR (31 downto 0);
        img_inp_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_inp_V_out_full_n : IN STD_LOGIC;
        img_inp_V_out_write : OUT STD_LOGIC;
        img_out_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_out_V_out_full_n : IN STD_LOGIC;
        img_out_V_out_write : OUT STD_LOGIC );
    end component;


    component Array2xfMat IS
    port (
        m_axi_srcPtr_V_AWVALID : OUT STD_LOGIC;
        m_axi_srcPtr_V_AWREADY : IN STD_LOGIC;
        m_axi_srcPtr_V_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_srcPtr_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_srcPtr_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_srcPtr_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_srcPtr_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_srcPtr_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_srcPtr_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_srcPtr_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_srcPtr_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_srcPtr_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_WVALID : OUT STD_LOGIC;
        m_axi_srcPtr_V_WREADY : IN STD_LOGIC;
        m_axi_srcPtr_V_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_srcPtr_V_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_WLAST : OUT STD_LOGIC;
        m_axi_srcPtr_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_ARVALID : OUT STD_LOGIC;
        m_axi_srcPtr_V_ARREADY : IN STD_LOGIC;
        m_axi_srcPtr_V_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_srcPtr_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_srcPtr_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_srcPtr_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_srcPtr_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_srcPtr_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_srcPtr_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_srcPtr_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_srcPtr_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_srcPtr_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_RVALID : IN STD_LOGIC;
        m_axi_srcPtr_V_RREADY : OUT STD_LOGIC;
        m_axi_srcPtr_V_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_srcPtr_V_RLAST : IN STD_LOGIC;
        m_axi_srcPtr_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_srcPtr_V_BVALID : IN STD_LOGIC;
        m_axi_srcPtr_V_BREADY : OUT STD_LOGIC;
        m_axi_srcPtr_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_srcPtr_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_srcPtr_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        srcPtr_V_offset_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        srcPtr_V_offset_empty_n : IN STD_LOGIC;
        srcPtr_V_offset_read : OUT STD_LOGIC;
        dstMat_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        dstMat_rows_empty_n : IN STD_LOGIC;
        dstMat_rows_read : OUT STD_LOGIC;
        dstMat_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        dstMat_cols_empty_n : IN STD_LOGIC;
        dstMat_cols_read : OUT STD_LOGIC;
        dstMat_data_V_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        dstMat_data_V_ce0 : OUT STD_LOGIC;
        dstMat_data_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dstMat_data_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        dstMat_data_V_we0 : OUT STD_LOGIC;
        dstMat_data_V_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        dstMat_data_V_ce1 : OUT STD_LOGIC;
        dstMat_data_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dstMat_data_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dstMat_data_V_we1 : OUT STD_LOGIC;
        dstMat_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dstMat_rows_out_full_n : IN STD_LOGIC;
        dstMat_rows_out_write : OUT STD_LOGIC;
        dstMat_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dstMat_cols_out_full_n : IN STD_LOGIC;
        dstMat_cols_out_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        dstMat_data_V_full_n : IN STD_LOGIC;
        dstMat_data_V_write : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component binary_threshold IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        src_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_rows_empty_n : IN STD_LOGIC;
        src_rows_read : OUT STD_LOGIC;
        src_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        src_cols_empty_n : IN STD_LOGIC;
        src_cols_read : OUT STD_LOGIC;
        src_data_V_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        src_data_V_ce0 : OUT STD_LOGIC;
        src_data_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        dst_data_V_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        dst_data_V_ce0 : OUT STD_LOGIC;
        dst_data_V_we0 : OUT STD_LOGIC;
        dst_data_V_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        threshold_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        threshold_empty_n : IN STD_LOGIC;
        threshold_read : OUT STD_LOGIC );
    end component;


    component xfMat2Array IS
    port (
        srcMat_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        srcMat_rows_empty_n : IN STD_LOGIC;
        srcMat_rows_read : OUT STD_LOGIC;
        srcMat_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        srcMat_cols_empty_n : IN STD_LOGIC;
        srcMat_cols_read : OUT STD_LOGIC;
        srcMat_data_V_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        srcMat_data_V_ce0 : OUT STD_LOGIC;
        srcMat_data_V_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        srcMat_data_V_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        srcMat_data_V_we0 : OUT STD_LOGIC;
        srcMat_data_V_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        srcMat_data_V_ce1 : OUT STD_LOGIC;
        srcMat_data_V_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        srcMat_data_V_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
        srcMat_data_V_we1 : OUT STD_LOGIC;
        m_axi_dstPtr_V_AWVALID : OUT STD_LOGIC;
        m_axi_dstPtr_V_AWREADY : IN STD_LOGIC;
        m_axi_dstPtr_V_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_dstPtr_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_dstPtr_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_dstPtr_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_dstPtr_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_dstPtr_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_dstPtr_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_dstPtr_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_dstPtr_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_dstPtr_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_WVALID : OUT STD_LOGIC;
        m_axi_dstPtr_V_WREADY : IN STD_LOGIC;
        m_axi_dstPtr_V_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_dstPtr_V_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_WLAST : OUT STD_LOGIC;
        m_axi_dstPtr_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_ARVALID : OUT STD_LOGIC;
        m_axi_dstPtr_V_ARREADY : IN STD_LOGIC;
        m_axi_dstPtr_V_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_dstPtr_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_dstPtr_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_dstPtr_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_dstPtr_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_dstPtr_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_dstPtr_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_dstPtr_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_dstPtr_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_dstPtr_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_RVALID : IN STD_LOGIC;
        m_axi_dstPtr_V_RREADY : OUT STD_LOGIC;
        m_axi_dstPtr_V_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_dstPtr_V_RLAST : IN STD_LOGIC;
        m_axi_dstPtr_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_dstPtr_V_BVALID : IN STD_LOGIC;
        m_axi_dstPtr_V_BREADY : OUT STD_LOGIC;
        m_axi_dstPtr_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_dstPtr_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_dstPtr_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        dstPtr_V_offset_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        dstPtr_V_offset_empty_n : IN STD_LOGIC;
        dstPtr_V_offset_read : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        srcMat_data_V_empty_n : IN STD_LOGIC;
        srcMat_data_V_read : OUT STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component Canny_accel_imgIndEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (19 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (19 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component Canny_accel_imgOueOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (19 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (19 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component fifo_w32_d2_A_x_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w32_d4_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w32_d3_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Canny_accel_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        img_inp_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_out_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        low_threshold : OUT STD_LOGIC_VECTOR (31 downto 0);
        high_threshold : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Canny_accel_gmem0_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component Canny_accel_gmem1_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    Canny_accel_control_s_axi_U : component Canny_accel_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        img_inp_V => img_inp_V,
        img_out_V => img_out_V,
        rows => rows,
        cols => cols,
        low_threshold => low_threshold,
        high_threshold => high_threshold);

    Canny_accel_gmem0_m_axi_U : component Canny_accel_gmem0_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 8,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM0_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM0_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM0_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM0_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM0_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM0_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM0_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM0_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM0_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM0_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM0_CACHE_VALUE)
    port map (
        AWVALID => m_axi_gmem0_AWVALID,
        AWREADY => m_axi_gmem0_AWREADY,
        AWADDR => m_axi_gmem0_AWADDR,
        AWID => m_axi_gmem0_AWID,
        AWLEN => m_axi_gmem0_AWLEN,
        AWSIZE => m_axi_gmem0_AWSIZE,
        AWBURST => m_axi_gmem0_AWBURST,
        AWLOCK => m_axi_gmem0_AWLOCK,
        AWCACHE => m_axi_gmem0_AWCACHE,
        AWPROT => m_axi_gmem0_AWPROT,
        AWQOS => m_axi_gmem0_AWQOS,
        AWREGION => m_axi_gmem0_AWREGION,
        AWUSER => m_axi_gmem0_AWUSER,
        WVALID => m_axi_gmem0_WVALID,
        WREADY => m_axi_gmem0_WREADY,
        WDATA => m_axi_gmem0_WDATA,
        WSTRB => m_axi_gmem0_WSTRB,
        WLAST => m_axi_gmem0_WLAST,
        WID => m_axi_gmem0_WID,
        WUSER => m_axi_gmem0_WUSER,
        ARVALID => m_axi_gmem0_ARVALID,
        ARREADY => m_axi_gmem0_ARREADY,
        ARADDR => m_axi_gmem0_ARADDR,
        ARID => m_axi_gmem0_ARID,
        ARLEN => m_axi_gmem0_ARLEN,
        ARSIZE => m_axi_gmem0_ARSIZE,
        ARBURST => m_axi_gmem0_ARBURST,
        ARLOCK => m_axi_gmem0_ARLOCK,
        ARCACHE => m_axi_gmem0_ARCACHE,
        ARPROT => m_axi_gmem0_ARPROT,
        ARQOS => m_axi_gmem0_ARQOS,
        ARREGION => m_axi_gmem0_ARREGION,
        ARUSER => m_axi_gmem0_ARUSER,
        RVALID => m_axi_gmem0_RVALID,
        RREADY => m_axi_gmem0_RREADY,
        RDATA => m_axi_gmem0_RDATA,
        RLAST => m_axi_gmem0_RLAST,
        RID => m_axi_gmem0_RID,
        RUSER => m_axi_gmem0_RUSER,
        RRESP => m_axi_gmem0_RRESP,
        BVALID => m_axi_gmem0_BVALID,
        BREADY => m_axi_gmem0_BREADY,
        BRESP => m_axi_gmem0_BRESP,
        BID => m_axi_gmem0_BID,
        BUSER => m_axi_gmem0_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => Array2xfMat_U0_m_axi_srcPtr_V_ARVALID,
        I_ARREADY => gmem0_ARREADY,
        I_ARADDR => Array2xfMat_U0_m_axi_srcPtr_V_ARADDR,
        I_ARID => Array2xfMat_U0_m_axi_srcPtr_V_ARID,
        I_ARLEN => Array2xfMat_U0_m_axi_srcPtr_V_ARLEN,
        I_ARSIZE => Array2xfMat_U0_m_axi_srcPtr_V_ARSIZE,
        I_ARLOCK => Array2xfMat_U0_m_axi_srcPtr_V_ARLOCK,
        I_ARCACHE => Array2xfMat_U0_m_axi_srcPtr_V_ARCACHE,
        I_ARQOS => Array2xfMat_U0_m_axi_srcPtr_V_ARQOS,
        I_ARPROT => Array2xfMat_U0_m_axi_srcPtr_V_ARPROT,
        I_ARUSER => Array2xfMat_U0_m_axi_srcPtr_V_ARUSER,
        I_ARBURST => Array2xfMat_U0_m_axi_srcPtr_V_ARBURST,
        I_ARREGION => Array2xfMat_U0_m_axi_srcPtr_V_ARREGION,
        I_RVALID => gmem0_RVALID,
        I_RREADY => Array2xfMat_U0_m_axi_srcPtr_V_RREADY,
        I_RDATA => gmem0_RDATA,
        I_RID => gmem0_RID,
        I_RUSER => gmem0_RUSER,
        I_RRESP => gmem0_RRESP,
        I_RLAST => gmem0_RLAST,
        I_AWVALID => ap_const_logic_0,
        I_AWREADY => gmem0_AWREADY,
        I_AWADDR => ap_const_lv32_0,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_0,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => ap_const_logic_0,
        I_WREADY => gmem0_WREADY,
        I_WDATA => ap_const_lv8_0,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv1_0,
        I_BVALID => gmem0_BVALID,
        I_BREADY => ap_const_logic_0,
        I_BRESP => gmem0_BRESP,
        I_BID => gmem0_BID,
        I_BUSER => gmem0_BUSER);

    Canny_accel_gmem1_m_axi_U : component Canny_accel_gmem1_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 8,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM1_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM1_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM1_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM1_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM1_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM1_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM1_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM1_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM1_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM1_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM1_CACHE_VALUE)
    port map (
        AWVALID => m_axi_gmem1_AWVALID,
        AWREADY => m_axi_gmem1_AWREADY,
        AWADDR => m_axi_gmem1_AWADDR,
        AWID => m_axi_gmem1_AWID,
        AWLEN => m_axi_gmem1_AWLEN,
        AWSIZE => m_axi_gmem1_AWSIZE,
        AWBURST => m_axi_gmem1_AWBURST,
        AWLOCK => m_axi_gmem1_AWLOCK,
        AWCACHE => m_axi_gmem1_AWCACHE,
        AWPROT => m_axi_gmem1_AWPROT,
        AWQOS => m_axi_gmem1_AWQOS,
        AWREGION => m_axi_gmem1_AWREGION,
        AWUSER => m_axi_gmem1_AWUSER,
        WVALID => m_axi_gmem1_WVALID,
        WREADY => m_axi_gmem1_WREADY,
        WDATA => m_axi_gmem1_WDATA,
        WSTRB => m_axi_gmem1_WSTRB,
        WLAST => m_axi_gmem1_WLAST,
        WID => m_axi_gmem1_WID,
        WUSER => m_axi_gmem1_WUSER,
        ARVALID => m_axi_gmem1_ARVALID,
        ARREADY => m_axi_gmem1_ARREADY,
        ARADDR => m_axi_gmem1_ARADDR,
        ARID => m_axi_gmem1_ARID,
        ARLEN => m_axi_gmem1_ARLEN,
        ARSIZE => m_axi_gmem1_ARSIZE,
        ARBURST => m_axi_gmem1_ARBURST,
        ARLOCK => m_axi_gmem1_ARLOCK,
        ARCACHE => m_axi_gmem1_ARCACHE,
        ARPROT => m_axi_gmem1_ARPROT,
        ARQOS => m_axi_gmem1_ARQOS,
        ARREGION => m_axi_gmem1_ARREGION,
        ARUSER => m_axi_gmem1_ARUSER,
        RVALID => m_axi_gmem1_RVALID,
        RREADY => m_axi_gmem1_RREADY,
        RDATA => m_axi_gmem1_RDATA,
        RLAST => m_axi_gmem1_RLAST,
        RID => m_axi_gmem1_RID,
        RUSER => m_axi_gmem1_RUSER,
        RRESP => m_axi_gmem1_RRESP,
        BVALID => m_axi_gmem1_BVALID,
        BREADY => m_axi_gmem1_BREADY,
        BRESP => m_axi_gmem1_BRESP,
        BID => m_axi_gmem1_BID,
        BUSER => m_axi_gmem1_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => ap_const_logic_0,
        I_ARREADY => gmem1_ARREADY,
        I_ARADDR => ap_const_lv32_0,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_0,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => gmem1_RVALID,
        I_RREADY => ap_const_logic_0,
        I_RDATA => gmem1_RDATA,
        I_RID => gmem1_RID,
        I_RUSER => gmem1_RUSER,
        I_RRESP => gmem1_RRESP,
        I_RLAST => gmem1_RLAST,
        I_AWVALID => xfMat2Array_U0_m_axi_dstPtr_V_AWVALID,
        I_AWREADY => gmem1_AWREADY,
        I_AWADDR => xfMat2Array_U0_m_axi_dstPtr_V_AWADDR,
        I_AWID => xfMat2Array_U0_m_axi_dstPtr_V_AWID,
        I_AWLEN => xfMat2Array_U0_m_axi_dstPtr_V_AWLEN,
        I_AWSIZE => xfMat2Array_U0_m_axi_dstPtr_V_AWSIZE,
        I_AWLOCK => xfMat2Array_U0_m_axi_dstPtr_V_AWLOCK,
        I_AWCACHE => xfMat2Array_U0_m_axi_dstPtr_V_AWCACHE,
        I_AWQOS => xfMat2Array_U0_m_axi_dstPtr_V_AWQOS,
        I_AWPROT => xfMat2Array_U0_m_axi_dstPtr_V_AWPROT,
        I_AWUSER => xfMat2Array_U0_m_axi_dstPtr_V_AWUSER,
        I_AWBURST => xfMat2Array_U0_m_axi_dstPtr_V_AWBURST,
        I_AWREGION => xfMat2Array_U0_m_axi_dstPtr_V_AWREGION,
        I_WVALID => xfMat2Array_U0_m_axi_dstPtr_V_WVALID,
        I_WREADY => gmem1_WREADY,
        I_WDATA => xfMat2Array_U0_m_axi_dstPtr_V_WDATA,
        I_WID => xfMat2Array_U0_m_axi_dstPtr_V_WID,
        I_WUSER => xfMat2Array_U0_m_axi_dstPtr_V_WUSER,
        I_WLAST => xfMat2Array_U0_m_axi_dstPtr_V_WLAST,
        I_WSTRB => xfMat2Array_U0_m_axi_dstPtr_V_WSTRB,
        I_BVALID => gmem1_BVALID,
        I_BREADY => xfMat2Array_U0_m_axi_dstPtr_V_BREADY,
        I_BRESP => gmem1_BRESP,
        I_BID => gmem1_BID,
        I_BUSER => gmem1_BUSER);

    imgInput_data_V_U : component Canny_accel_imgIndEe
    generic map (
        DataWidth => 8,
        AddressRange => 921600,
        AddressWidth => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => Array2xfMat_U0_dstMat_data_V_address0,
        i_ce0 => Array2xfMat_U0_dstMat_data_V_ce0,
        i_we0 => Array2xfMat_U0_dstMat_data_V_we0,
        i_d0 => Array2xfMat_U0_dstMat_data_V_d0,
        i_q0 => imgInput_data_V_i_q0,
        t_address0 => binary_threshold_U0_src_data_V_address0,
        t_ce0 => binary_threshold_U0_src_data_V_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv8_0,
        t_q0 => imgInput_data_V_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => imgInput_data_V_i_full_n,
        i_write => Array2xfMat_U0_ap_done,
        t_empty_n => imgInput_data_V_t_empty_n,
        t_read => binary_threshold_U0_ap_ready);

    imgOutput_data_V_U : component Canny_accel_imgOueOg
    generic map (
        DataWidth => 1,
        AddressRange => 921600,
        AddressWidth => 20)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => binary_threshold_U0_dst_data_V_address0,
        i_ce0 => binary_threshold_U0_dst_data_V_ce0,
        i_we0 => binary_threshold_U0_dst_data_V_we0,
        i_d0 => binary_threshold_U0_dst_data_V_d0,
        i_q0 => imgOutput_data_V_i_q0,
        t_address0 => xfMat2Array_U0_srcMat_data_V_address0,
        t_ce0 => xfMat2Array_U0_srcMat_data_V_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv1_0,
        t_q0 => imgOutput_data_V_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => imgOutput_data_V_i_full_n,
        i_write => binary_threshold_U0_ap_done,
        t_empty_n => imgOutput_data_V_t_empty_n,
        t_read => xfMat2Array_U0_ap_ready);

    Block_Mat_exit45_pro_U0 : component Block_Mat_exit45_pro
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_Mat_exit45_pro_U0_ap_start,
        ap_done => Block_Mat_exit45_pro_U0_ap_done,
        ap_continue => Block_Mat_exit45_pro_U0_ap_continue,
        ap_idle => Block_Mat_exit45_pro_U0_ap_idle,
        ap_ready => Block_Mat_exit45_pro_U0_ap_ready,
        rows => rows,
        cols => cols,
        low_threshold => low_threshold,
        imgInput_rows_out_din => Block_Mat_exit45_pro_U0_imgInput_rows_out_din,
        imgInput_rows_out_full_n => imgInput_rows_c_full_n,
        imgInput_rows_out_write => Block_Mat_exit45_pro_U0_imgInput_rows_out_write,
        imgInput_cols_out_din => Block_Mat_exit45_pro_U0_imgInput_cols_out_din,
        imgInput_cols_out_full_n => imgInput_cols_c_full_n,
        imgInput_cols_out_write => Block_Mat_exit45_pro_U0_imgInput_cols_out_write,
        imgOutput_rows_out_din => Block_Mat_exit45_pro_U0_imgOutput_rows_out_din,
        imgOutput_rows_out_full_n => imgOutput_rows_c_full_n,
        imgOutput_rows_out_write => Block_Mat_exit45_pro_U0_imgOutput_rows_out_write,
        imgOutput_cols_out_din => Block_Mat_exit45_pro_U0_imgOutput_cols_out_din,
        imgOutput_cols_out_full_n => imgOutput_cols_c_full_n,
        imgOutput_cols_out_write => Block_Mat_exit45_pro_U0_imgOutput_cols_out_write,
        low_threshold_out_din => Block_Mat_exit45_pro_U0_low_threshold_out_din,
        low_threshold_out_full_n => low_threshold_c_full_n,
        low_threshold_out_write => Block_Mat_exit45_pro_U0_low_threshold_out_write,
        img_inp_V => img_inp_V,
        img_out_V => img_out_V,
        img_inp_V_out_din => Block_Mat_exit45_pro_U0_img_inp_V_out_din,
        img_inp_V_out_full_n => img_inp_V_c_full_n,
        img_inp_V_out_write => Block_Mat_exit45_pro_U0_img_inp_V_out_write,
        img_out_V_out_din => Block_Mat_exit45_pro_U0_img_out_V_out_din,
        img_out_V_out_full_n => img_out_V_c_full_n,
        img_out_V_out_write => Block_Mat_exit45_pro_U0_img_out_V_out_write);

    Array2xfMat_U0 : component Array2xfMat
    port map (
        m_axi_srcPtr_V_AWVALID => Array2xfMat_U0_m_axi_srcPtr_V_AWVALID,
        m_axi_srcPtr_V_AWREADY => ap_const_logic_0,
        m_axi_srcPtr_V_AWADDR => Array2xfMat_U0_m_axi_srcPtr_V_AWADDR,
        m_axi_srcPtr_V_AWID => Array2xfMat_U0_m_axi_srcPtr_V_AWID,
        m_axi_srcPtr_V_AWLEN => Array2xfMat_U0_m_axi_srcPtr_V_AWLEN,
        m_axi_srcPtr_V_AWSIZE => Array2xfMat_U0_m_axi_srcPtr_V_AWSIZE,
        m_axi_srcPtr_V_AWBURST => Array2xfMat_U0_m_axi_srcPtr_V_AWBURST,
        m_axi_srcPtr_V_AWLOCK => Array2xfMat_U0_m_axi_srcPtr_V_AWLOCK,
        m_axi_srcPtr_V_AWCACHE => Array2xfMat_U0_m_axi_srcPtr_V_AWCACHE,
        m_axi_srcPtr_V_AWPROT => Array2xfMat_U0_m_axi_srcPtr_V_AWPROT,
        m_axi_srcPtr_V_AWQOS => Array2xfMat_U0_m_axi_srcPtr_V_AWQOS,
        m_axi_srcPtr_V_AWREGION => Array2xfMat_U0_m_axi_srcPtr_V_AWREGION,
        m_axi_srcPtr_V_AWUSER => Array2xfMat_U0_m_axi_srcPtr_V_AWUSER,
        m_axi_srcPtr_V_WVALID => Array2xfMat_U0_m_axi_srcPtr_V_WVALID,
        m_axi_srcPtr_V_WREADY => ap_const_logic_0,
        m_axi_srcPtr_V_WDATA => Array2xfMat_U0_m_axi_srcPtr_V_WDATA,
        m_axi_srcPtr_V_WSTRB => Array2xfMat_U0_m_axi_srcPtr_V_WSTRB,
        m_axi_srcPtr_V_WLAST => Array2xfMat_U0_m_axi_srcPtr_V_WLAST,
        m_axi_srcPtr_V_WID => Array2xfMat_U0_m_axi_srcPtr_V_WID,
        m_axi_srcPtr_V_WUSER => Array2xfMat_U0_m_axi_srcPtr_V_WUSER,
        m_axi_srcPtr_V_ARVALID => Array2xfMat_U0_m_axi_srcPtr_V_ARVALID,
        m_axi_srcPtr_V_ARREADY => gmem0_ARREADY,
        m_axi_srcPtr_V_ARADDR => Array2xfMat_U0_m_axi_srcPtr_V_ARADDR,
        m_axi_srcPtr_V_ARID => Array2xfMat_U0_m_axi_srcPtr_V_ARID,
        m_axi_srcPtr_V_ARLEN => Array2xfMat_U0_m_axi_srcPtr_V_ARLEN,
        m_axi_srcPtr_V_ARSIZE => Array2xfMat_U0_m_axi_srcPtr_V_ARSIZE,
        m_axi_srcPtr_V_ARBURST => Array2xfMat_U0_m_axi_srcPtr_V_ARBURST,
        m_axi_srcPtr_V_ARLOCK => Array2xfMat_U0_m_axi_srcPtr_V_ARLOCK,
        m_axi_srcPtr_V_ARCACHE => Array2xfMat_U0_m_axi_srcPtr_V_ARCACHE,
        m_axi_srcPtr_V_ARPROT => Array2xfMat_U0_m_axi_srcPtr_V_ARPROT,
        m_axi_srcPtr_V_ARQOS => Array2xfMat_U0_m_axi_srcPtr_V_ARQOS,
        m_axi_srcPtr_V_ARREGION => Array2xfMat_U0_m_axi_srcPtr_V_ARREGION,
        m_axi_srcPtr_V_ARUSER => Array2xfMat_U0_m_axi_srcPtr_V_ARUSER,
        m_axi_srcPtr_V_RVALID => gmem0_RVALID,
        m_axi_srcPtr_V_RREADY => Array2xfMat_U0_m_axi_srcPtr_V_RREADY,
        m_axi_srcPtr_V_RDATA => gmem0_RDATA,
        m_axi_srcPtr_V_RLAST => gmem0_RLAST,
        m_axi_srcPtr_V_RID => gmem0_RID,
        m_axi_srcPtr_V_RUSER => gmem0_RUSER,
        m_axi_srcPtr_V_RRESP => gmem0_RRESP,
        m_axi_srcPtr_V_BVALID => ap_const_logic_0,
        m_axi_srcPtr_V_BREADY => Array2xfMat_U0_m_axi_srcPtr_V_BREADY,
        m_axi_srcPtr_V_BRESP => ap_const_lv2_0,
        m_axi_srcPtr_V_BID => ap_const_lv1_0,
        m_axi_srcPtr_V_BUSER => ap_const_lv1_0,
        srcPtr_V_offset_dout => img_inp_V_c_dout,
        srcPtr_V_offset_empty_n => img_inp_V_c_empty_n,
        srcPtr_V_offset_read => Array2xfMat_U0_srcPtr_V_offset_read,
        dstMat_rows_dout => imgInput_rows_c_dout,
        dstMat_rows_empty_n => imgInput_rows_c_empty_n,
        dstMat_rows_read => Array2xfMat_U0_dstMat_rows_read,
        dstMat_cols_dout => imgInput_cols_c_dout,
        dstMat_cols_empty_n => imgInput_cols_c_empty_n,
        dstMat_cols_read => Array2xfMat_U0_dstMat_cols_read,
        dstMat_data_V_address0 => Array2xfMat_U0_dstMat_data_V_address0,
        dstMat_data_V_ce0 => Array2xfMat_U0_dstMat_data_V_ce0,
        dstMat_data_V_d0 => Array2xfMat_U0_dstMat_data_V_d0,
        dstMat_data_V_q0 => ap_const_lv8_0,
        dstMat_data_V_we0 => Array2xfMat_U0_dstMat_data_V_we0,
        dstMat_data_V_address1 => Array2xfMat_U0_dstMat_data_V_address1,
        dstMat_data_V_ce1 => Array2xfMat_U0_dstMat_data_V_ce1,
        dstMat_data_V_d1 => Array2xfMat_U0_dstMat_data_V_d1,
        dstMat_data_V_q1 => ap_const_lv8_0,
        dstMat_data_V_we1 => Array2xfMat_U0_dstMat_data_V_we1,
        dstMat_rows_out_din => Array2xfMat_U0_dstMat_rows_out_din,
        dstMat_rows_out_full_n => imgInput_rows_c13_full_n,
        dstMat_rows_out_write => Array2xfMat_U0_dstMat_rows_out_write,
        dstMat_cols_out_din => Array2xfMat_U0_dstMat_cols_out_din,
        dstMat_cols_out_full_n => imgInput_cols_c14_full_n,
        dstMat_cols_out_write => Array2xfMat_U0_dstMat_cols_out_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Array2xfMat_U0_ap_start,
        ap_done => Array2xfMat_U0_ap_done,
        dstMat_data_V_full_n => imgInput_data_V_i_full_n,
        dstMat_data_V_write => Array2xfMat_U0_dstMat_data_V_write,
        ap_ready => Array2xfMat_U0_ap_ready,
        ap_idle => Array2xfMat_U0_ap_idle,
        ap_continue => Array2xfMat_U0_ap_continue);

    binary_threshold_U0 : component binary_threshold
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => binary_threshold_U0_ap_start,
        ap_done => binary_threshold_U0_ap_done,
        ap_continue => binary_threshold_U0_ap_continue,
        ap_idle => binary_threshold_U0_ap_idle,
        ap_ready => binary_threshold_U0_ap_ready,
        src_rows_dout => imgInput_rows_c13_dout,
        src_rows_empty_n => imgInput_rows_c13_empty_n,
        src_rows_read => binary_threshold_U0_src_rows_read,
        src_cols_dout => imgInput_cols_c14_dout,
        src_cols_empty_n => imgInput_cols_c14_empty_n,
        src_cols_read => binary_threshold_U0_src_cols_read,
        src_data_V_address0 => binary_threshold_U0_src_data_V_address0,
        src_data_V_ce0 => binary_threshold_U0_src_data_V_ce0,
        src_data_V_q0 => imgInput_data_V_t_q0,
        dst_data_V_address0 => binary_threshold_U0_dst_data_V_address0,
        dst_data_V_ce0 => binary_threshold_U0_dst_data_V_ce0,
        dst_data_V_we0 => binary_threshold_U0_dst_data_V_we0,
        dst_data_V_d0 => binary_threshold_U0_dst_data_V_d0,
        threshold_dout => low_threshold_c_dout,
        threshold_empty_n => low_threshold_c_empty_n,
        threshold_read => binary_threshold_U0_threshold_read);

    xfMat2Array_U0 : component xfMat2Array
    port map (
        srcMat_rows_dout => imgOutput_rows_c_dout,
        srcMat_rows_empty_n => imgOutput_rows_c_empty_n,
        srcMat_rows_read => xfMat2Array_U0_srcMat_rows_read,
        srcMat_cols_dout => imgOutput_cols_c_dout,
        srcMat_cols_empty_n => imgOutput_cols_c_empty_n,
        srcMat_cols_read => xfMat2Array_U0_srcMat_cols_read,
        srcMat_data_V_address0 => xfMat2Array_U0_srcMat_data_V_address0,
        srcMat_data_V_ce0 => xfMat2Array_U0_srcMat_data_V_ce0,
        srcMat_data_V_d0 => xfMat2Array_U0_srcMat_data_V_d0,
        srcMat_data_V_q0 => imgOutput_data_V_t_q0,
        srcMat_data_V_we0 => xfMat2Array_U0_srcMat_data_V_we0,
        srcMat_data_V_address1 => xfMat2Array_U0_srcMat_data_V_address1,
        srcMat_data_V_ce1 => xfMat2Array_U0_srcMat_data_V_ce1,
        srcMat_data_V_d1 => xfMat2Array_U0_srcMat_data_V_d1,
        srcMat_data_V_q1 => ap_const_lv1_0,
        srcMat_data_V_we1 => xfMat2Array_U0_srcMat_data_V_we1,
        m_axi_dstPtr_V_AWVALID => xfMat2Array_U0_m_axi_dstPtr_V_AWVALID,
        m_axi_dstPtr_V_AWREADY => gmem1_AWREADY,
        m_axi_dstPtr_V_AWADDR => xfMat2Array_U0_m_axi_dstPtr_V_AWADDR,
        m_axi_dstPtr_V_AWID => xfMat2Array_U0_m_axi_dstPtr_V_AWID,
        m_axi_dstPtr_V_AWLEN => xfMat2Array_U0_m_axi_dstPtr_V_AWLEN,
        m_axi_dstPtr_V_AWSIZE => xfMat2Array_U0_m_axi_dstPtr_V_AWSIZE,
        m_axi_dstPtr_V_AWBURST => xfMat2Array_U0_m_axi_dstPtr_V_AWBURST,
        m_axi_dstPtr_V_AWLOCK => xfMat2Array_U0_m_axi_dstPtr_V_AWLOCK,
        m_axi_dstPtr_V_AWCACHE => xfMat2Array_U0_m_axi_dstPtr_V_AWCACHE,
        m_axi_dstPtr_V_AWPROT => xfMat2Array_U0_m_axi_dstPtr_V_AWPROT,
        m_axi_dstPtr_V_AWQOS => xfMat2Array_U0_m_axi_dstPtr_V_AWQOS,
        m_axi_dstPtr_V_AWREGION => xfMat2Array_U0_m_axi_dstPtr_V_AWREGION,
        m_axi_dstPtr_V_AWUSER => xfMat2Array_U0_m_axi_dstPtr_V_AWUSER,
        m_axi_dstPtr_V_WVALID => xfMat2Array_U0_m_axi_dstPtr_V_WVALID,
        m_axi_dstPtr_V_WREADY => gmem1_WREADY,
        m_axi_dstPtr_V_WDATA => xfMat2Array_U0_m_axi_dstPtr_V_WDATA,
        m_axi_dstPtr_V_WSTRB => xfMat2Array_U0_m_axi_dstPtr_V_WSTRB,
        m_axi_dstPtr_V_WLAST => xfMat2Array_U0_m_axi_dstPtr_V_WLAST,
        m_axi_dstPtr_V_WID => xfMat2Array_U0_m_axi_dstPtr_V_WID,
        m_axi_dstPtr_V_WUSER => xfMat2Array_U0_m_axi_dstPtr_V_WUSER,
        m_axi_dstPtr_V_ARVALID => xfMat2Array_U0_m_axi_dstPtr_V_ARVALID,
        m_axi_dstPtr_V_ARREADY => ap_const_logic_0,
        m_axi_dstPtr_V_ARADDR => xfMat2Array_U0_m_axi_dstPtr_V_ARADDR,
        m_axi_dstPtr_V_ARID => xfMat2Array_U0_m_axi_dstPtr_V_ARID,
        m_axi_dstPtr_V_ARLEN => xfMat2Array_U0_m_axi_dstPtr_V_ARLEN,
        m_axi_dstPtr_V_ARSIZE => xfMat2Array_U0_m_axi_dstPtr_V_ARSIZE,
        m_axi_dstPtr_V_ARBURST => xfMat2Array_U0_m_axi_dstPtr_V_ARBURST,
        m_axi_dstPtr_V_ARLOCK => xfMat2Array_U0_m_axi_dstPtr_V_ARLOCK,
        m_axi_dstPtr_V_ARCACHE => xfMat2Array_U0_m_axi_dstPtr_V_ARCACHE,
        m_axi_dstPtr_V_ARPROT => xfMat2Array_U0_m_axi_dstPtr_V_ARPROT,
        m_axi_dstPtr_V_ARQOS => xfMat2Array_U0_m_axi_dstPtr_V_ARQOS,
        m_axi_dstPtr_V_ARREGION => xfMat2Array_U0_m_axi_dstPtr_V_ARREGION,
        m_axi_dstPtr_V_ARUSER => xfMat2Array_U0_m_axi_dstPtr_V_ARUSER,
        m_axi_dstPtr_V_RVALID => ap_const_logic_0,
        m_axi_dstPtr_V_RREADY => xfMat2Array_U0_m_axi_dstPtr_V_RREADY,
        m_axi_dstPtr_V_RDATA => ap_const_lv8_0,
        m_axi_dstPtr_V_RLAST => ap_const_logic_0,
        m_axi_dstPtr_V_RID => ap_const_lv1_0,
        m_axi_dstPtr_V_RUSER => ap_const_lv1_0,
        m_axi_dstPtr_V_RRESP => ap_const_lv2_0,
        m_axi_dstPtr_V_BVALID => gmem1_BVALID,
        m_axi_dstPtr_V_BREADY => xfMat2Array_U0_m_axi_dstPtr_V_BREADY,
        m_axi_dstPtr_V_BRESP => gmem1_BRESP,
        m_axi_dstPtr_V_BID => gmem1_BID,
        m_axi_dstPtr_V_BUSER => gmem1_BUSER,
        dstPtr_V_offset_dout => img_out_V_c_dout,
        dstPtr_V_offset_empty_n => img_out_V_c_empty_n,
        dstPtr_V_offset_read => xfMat2Array_U0_dstPtr_V_offset_read,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        srcMat_data_V_empty_n => ap_const_logic_0,
        srcMat_data_V_read => xfMat2Array_U0_srcMat_data_V_read,
        ap_start => xfMat2Array_U0_ap_start,
        ap_done => xfMat2Array_U0_ap_done,
        ap_ready => xfMat2Array_U0_ap_ready,
        ap_idle => xfMat2Array_U0_ap_idle,
        ap_continue => xfMat2Array_U0_ap_continue);

    imgInput_rows_c_U : component fifo_w32_d2_A_x_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit45_pro_U0_imgInput_rows_out_din,
        if_full_n => imgInput_rows_c_full_n,
        if_write => Block_Mat_exit45_pro_U0_imgInput_rows_out_write,
        if_dout => imgInput_rows_c_dout,
        if_empty_n => imgInput_rows_c_empty_n,
        if_read => Array2xfMat_U0_dstMat_rows_read);

    imgInput_cols_c_U : component fifo_w32_d2_A_x_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit45_pro_U0_imgInput_cols_out_din,
        if_full_n => imgInput_cols_c_full_n,
        if_write => Block_Mat_exit45_pro_U0_imgInput_cols_out_write,
        if_dout => imgInput_cols_c_dout,
        if_empty_n => imgInput_cols_c_empty_n,
        if_read => Array2xfMat_U0_dstMat_cols_read);

    imgOutput_rows_c_U : component fifo_w32_d4_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit45_pro_U0_imgOutput_rows_out_din,
        if_full_n => imgOutput_rows_c_full_n,
        if_write => Block_Mat_exit45_pro_U0_imgOutput_rows_out_write,
        if_dout => imgOutput_rows_c_dout,
        if_empty_n => imgOutput_rows_c_empty_n,
        if_read => xfMat2Array_U0_srcMat_rows_read);

    imgOutput_cols_c_U : component fifo_w32_d4_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit45_pro_U0_imgOutput_cols_out_din,
        if_full_n => imgOutput_cols_c_full_n,
        if_write => Block_Mat_exit45_pro_U0_imgOutput_cols_out_write,
        if_dout => imgOutput_cols_c_dout,
        if_empty_n => imgOutput_cols_c_empty_n,
        if_read => xfMat2Array_U0_srcMat_cols_read);

    low_threshold_c_U : component fifo_w32_d3_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit45_pro_U0_low_threshold_out_din,
        if_full_n => low_threshold_c_full_n,
        if_write => Block_Mat_exit45_pro_U0_low_threshold_out_write,
        if_dout => low_threshold_c_dout,
        if_empty_n => low_threshold_c_empty_n,
        if_read => binary_threshold_U0_threshold_read);

    img_inp_V_c_U : component fifo_w32_d2_A_x_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit45_pro_U0_img_inp_V_out_din,
        if_full_n => img_inp_V_c_full_n,
        if_write => Block_Mat_exit45_pro_U0_img_inp_V_out_write,
        if_dout => img_inp_V_c_dout,
        if_empty_n => img_inp_V_c_empty_n,
        if_read => Array2xfMat_U0_srcPtr_V_offset_read);

    img_out_V_c_U : component fifo_w32_d4_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_Mat_exit45_pro_U0_img_out_V_out_din,
        if_full_n => img_out_V_c_full_n,
        if_write => Block_Mat_exit45_pro_U0_img_out_V_out_write,
        if_dout => img_out_V_c_dout,
        if_empty_n => img_out_V_c_empty_n,
        if_read => xfMat2Array_U0_dstPtr_V_offset_read);

    imgInput_rows_c13_U : component fifo_w32_d2_A_x_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Array2xfMat_U0_dstMat_rows_out_din,
        if_full_n => imgInput_rows_c13_full_n,
        if_write => Array2xfMat_U0_dstMat_rows_out_write,
        if_dout => imgInput_rows_c13_dout,
        if_empty_n => imgInput_rows_c13_empty_n,
        if_read => binary_threshold_U0_src_rows_read);

    imgInput_cols_c14_U : component fifo_w32_d2_A_x_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Array2xfMat_U0_dstMat_cols_out_din,
        if_full_n => imgInput_cols_c14_full_n,
        if_write => Array2xfMat_U0_dstMat_cols_out_write,
        if_dout => imgInput_cols_c14_dout,
        if_empty_n => imgInput_cols_c14_empty_n,
        if_read => binary_threshold_U0_src_cols_read);





    ap_sync_reg_Array2xfMat_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Array2xfMat_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Array2xfMat_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Array2xfMat_U0_ap_ready <= ap_sync_Array2xfMat_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_Block_Mat_exit45_pro_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Block_Mat_exit45_pro_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Block_Mat_exit45_pro_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Block_Mat_exit45_pro_U0_ap_ready <= ap_sync_Block_Mat_exit45_pro_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    Array2xfMat_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_0 = Array2xfMat_U0_ap_ready) and (ap_sync_ready = ap_const_logic_1))) then 
                Array2xfMat_U0_ap_ready_count <= std_logic_vector(unsigned(Array2xfMat_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (ap_const_logic_1 = Array2xfMat_U0_ap_ready))) then 
                Array2xfMat_U0_ap_ready_count <= std_logic_vector(unsigned(Array2xfMat_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    Block_Mat_exit45_pro_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_sync_ready = ap_const_logic_1) and (ap_const_logic_0 = Block_Mat_exit45_pro_U0_ap_ready))) then 
                Block_Mat_exit45_pro_U0_ap_ready_count <= std_logic_vector(unsigned(Block_Mat_exit45_pro_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (ap_const_logic_1 = Block_Mat_exit45_pro_U0_ap_ready))) then 
                Block_Mat_exit45_pro_U0_ap_ready_count <= std_logic_vector(unsigned(Block_Mat_exit45_pro_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    Array2xfMat_U0_ap_continue <= Array2xfMat_U0_dstMat_data_V_full_n;
    Array2xfMat_U0_ap_start <= ((ap_sync_reg_Array2xfMat_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Array2xfMat_U0_dstMat_data_V_full_n <= imgInput_data_V_i_full_n;
    Array2xfMat_U0_start_full_n <= ap_const_logic_1;
    Array2xfMat_U0_start_write <= ap_const_logic_0;
    Block_Mat_exit45_pro_U0_ap_continue <= ap_const_logic_1;
    Block_Mat_exit45_pro_U0_ap_start <= ((ap_sync_reg_Block_Mat_exit45_pro_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Block_Mat_exit45_pro_U0_start_full_n <= ap_const_logic_1;
    Block_Mat_exit45_pro_U0_start_write <= ap_const_logic_0;
    ap_channel_done_imgInput_data_V <= Array2xfMat_U0_ap_done;
    ap_channel_done_imgOutput_data_V <= binary_threshold_U0_ap_done;
    ap_done <= xfMat2Array_U0_ap_done;
    ap_idle <= (xfMat2Array_U0_ap_idle and (imgOutput_data_V_t_empty_n xor ap_const_logic_1) and (imgInput_data_V_t_empty_n xor ap_const_logic_1) and binary_threshold_U0_ap_idle and Block_Mat_exit45_pro_U0_ap_idle and Array2xfMat_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_Array2xfMat_U0_ap_ready <= (ap_sync_reg_Array2xfMat_U0_ap_ready or Array2xfMat_U0_ap_ready);
    ap_sync_Block_Mat_exit45_pro_U0_ap_ready <= (ap_sync_reg_Block_Mat_exit45_pro_U0_ap_ready or Block_Mat_exit45_pro_U0_ap_ready);
    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= xfMat2Array_U0_ap_done;
    ap_sync_ready <= (ap_sync_Block_Mat_exit45_pro_U0_ap_ready and ap_sync_Array2xfMat_U0_ap_ready);
    binary_threshold_U0_ap_continue <= imgOutput_data_V_i_full_n;
    binary_threshold_U0_ap_start <= imgInput_data_V_t_empty_n;
    binary_threshold_U0_dst_data_V_full_n <= imgOutput_data_V_i_full_n;
    binary_threshold_U0_start_full_n <= ap_const_logic_1;
    binary_threshold_U0_start_write <= ap_const_logic_0;
    xfMat2Array_U0_ap_continue <= ap_const_logic_1;
    xfMat2Array_U0_ap_start <= imgOutput_data_V_t_empty_n;
    xfMat2Array_U0_start_full_n <= ap_const_logic_1;
    xfMat2Array_U0_start_write <= ap_const_logic_0;
end behav;
