-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Array2hlsStrm54 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    scalar_dstMat_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    scalar_dstMat_cols_empty_n : IN STD_LOGIC;
    scalar_dstMat_cols_read : OUT STD_LOGIC;
    dstMat_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dstMat_cols_out_full_n : IN STD_LOGIC;
    dstMat_cols_out_write : OUT STD_LOGIC;
    scalar_dstMat_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    scalar_dstMat_rows_empty_n : IN STD_LOGIC;
    scalar_dstMat_rows_read : OUT STD_LOGIC;
    dstMat_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dstMat_rows_out_full_n : IN STD_LOGIC;
    dstMat_rows_out_write : OUT STD_LOGIC;
    m_axi_srcPtr_V_AWVALID : OUT STD_LOGIC;
    m_axi_srcPtr_V_AWREADY : IN STD_LOGIC;
    m_axi_srcPtr_V_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_srcPtr_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_srcPtr_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_srcPtr_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_srcPtr_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_srcPtr_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_srcPtr_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_srcPtr_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_srcPtr_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_srcPtr_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_WVALID : OUT STD_LOGIC;
    m_axi_srcPtr_V_WREADY : IN STD_LOGIC;
    m_axi_srcPtr_V_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_srcPtr_V_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_WLAST : OUT STD_LOGIC;
    m_axi_srcPtr_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_ARVALID : OUT STD_LOGIC;
    m_axi_srcPtr_V_ARREADY : IN STD_LOGIC;
    m_axi_srcPtr_V_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_srcPtr_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_srcPtr_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_srcPtr_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_srcPtr_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_srcPtr_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_srcPtr_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_srcPtr_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_srcPtr_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_srcPtr_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_RVALID : IN STD_LOGIC;
    m_axi_srcPtr_V_RREADY : OUT STD_LOGIC;
    m_axi_srcPtr_V_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_srcPtr_V_RLAST : IN STD_LOGIC;
    m_axi_srcPtr_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_srcPtr_V_BVALID : IN STD_LOGIC;
    m_axi_srcPtr_V_BREADY : OUT STD_LOGIC;
    m_axi_srcPtr_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_srcPtr_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_srcPtr_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    srcPtr_V_offset_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    srcPtr_V_offset_empty_n : IN STD_LOGIC;
    srcPtr_V_offset_read : OUT STD_LOGIC;
    strm_V_V_i_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    strm_V_V_i_full_n : IN STD_LOGIC;
    strm_V_V_i_write : OUT STD_LOGIC;
    dstMat_rows_c_i_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dstMat_rows_c_i_full_n : IN STD_LOGIC;
    dstMat_rows_c_i_write : OUT STD_LOGIC;
    dstMat_cols_c_i_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dstMat_cols_c_i_full_n : IN STD_LOGIC;
    dstMat_cols_c_i_write : OUT STD_LOGIC );
end;


architecture behav of Array2hlsStrm54 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv29_1 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal scalar_dstMat_cols_blk_n : STD_LOGIC;
    signal dstMat_cols_out_blk_n : STD_LOGIC;
    signal scalar_dstMat_rows_blk_n : STD_LOGIC;
    signal dstMat_rows_out_blk_n : STD_LOGIC;
    signal srcPtr_V_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal srcPtr_V_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_14_i_i_i_i_i_reg_289 : STD_LOGIC_VECTOR (0 downto 0);
    signal srcPtr_V_offset_blk_n : STD_LOGIC;
    signal strm_V_V_i_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dstMat_rows_c_i_blk_n : STD_LOGIC;
    signal dstMat_cols_c_i_blk_n : STD_LOGIC;
    signal i_i_i_i_i_i_reg_150 : STD_LOGIC_VECTOR (28 downto 0);
    signal srcPtr_V_addr_reg_247 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal scalar_dstMat_cols_r_reg_253 : STD_LOGIC_VECTOR (31 downto 0);
    signal scalar_dstMat_rows_r_reg_258 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_i_i_i_i_i_fu_171_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_i_i_i_i_i_reg_263 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_175_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_reg_268 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_8_reg_273 : STD_LOGIC_VECTOR (0 downto 0);
    signal loop_count_fu_221_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal loop_count_reg_278 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_sig_ioackin_m_axi_srcPtr_V_ARREADY : STD_LOGIC;
    signal tmp_14_i_i_i_i_i_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state11_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_241_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_V_reg_298 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state11 : STD_LOGIC;
    signal tmp_i_fu_161_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_m_axi_srcPtr_V_ARREADY : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_7_fu_190_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_neg_i_i_i_i_i_fu_195_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_i_fu_201_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_lshr_cast_i_i_i_i_i_fu_211_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_neg_t_i_i_i_i_i_fu_215_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_13_cast_i_i_i_i_s_fu_187_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal i_cast_i_i_i_i_i_fu_232_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state11) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state11)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state11);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_srcPtr_V_ARREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_srcPtr_V_ARREADY <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                    if ((ap_sig_ioackin_m_axi_srcPtr_V_ARREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_srcPtr_V_ARREADY <= ap_const_logic_0;
                    elsif ((m_axi_srcPtr_V_ARREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_srcPtr_V_ARREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_i_i_i_i_i_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_14_i_i_i_i_i_fu_236_p2 = ap_const_lv1_1))) then 
                i_i_i_i_i_i_reg_150 <= i_fu_241_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                i_i_i_i_i_i_reg_150 <= ap_const_lv29_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                loop_count_reg_278 <= loop_count_fu_221_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                scalar_dstMat_cols_r_reg_253 <= scalar_dstMat_cols_dout;
                scalar_dstMat_rows_r_reg_258 <= scalar_dstMat_rows_dout;
                srcPtr_V_addr_reg_247 <= tmp_i_fu_161_p1(32 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_14_i_i_i_i_i_reg_289 <= tmp_14_i_i_i_i_i_fu_236_p2;
                tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg <= tmp_14_i_i_i_i_i_reg_289;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_1_i_i_i_i_i_reg_263 <= tmp_1_i_i_i_i_i_fu_171_p2;
                tmp_8_reg_273 <= tmp_1_i_i_i_i_i_fu_171_p2(28 downto 28);
                tmp_reg_268 <= tmp_fu_175_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_14_i_i_i_i_i_reg_289 = ap_const_lv1_1))) then
                tmp_V_reg_298 <= m_axi_srcPtr_V_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n, ap_CS_fsm_state4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_sig_ioackin_m_axi_srcPtr_V_ARREADY, tmp_14_i_i_i_i_i_fu_236_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_sig_ioackin_m_axi_srcPtr_V_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (tmp_14_i_i_i_i_i_fu_236_p2 = ap_const_lv1_0))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (tmp_14_i_i_i_i_i_fu_236_p2 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(10);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state14 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(m_axi_srcPtr_V_RVALID, strm_V_V_i_full_n, ap_enable_reg_pp0_iter1, tmp_14_i_i_i_i_i_reg_289, ap_enable_reg_pp0_iter2, tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((strm_V_V_i_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg = ap_const_lv1_1)) or ((m_axi_srcPtr_V_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_14_i_i_i_i_i_reg_289 = ap_const_lv1_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(m_axi_srcPtr_V_RVALID, strm_V_V_i_full_n, ap_enable_reg_pp0_iter1, tmp_14_i_i_i_i_i_reg_289, ap_enable_reg_pp0_iter2, tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((strm_V_V_i_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg = ap_const_lv1_1)) or ((m_axi_srcPtr_V_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_14_i_i_i_i_i_reg_289 = ap_const_lv1_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(m_axi_srcPtr_V_RVALID, strm_V_V_i_full_n, ap_enable_reg_pp0_iter1, tmp_14_i_i_i_i_i_reg_289, ap_enable_reg_pp0_iter2, tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((strm_V_V_i_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg = ap_const_lv1_1)) or ((m_axi_srcPtr_V_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_14_i_i_i_i_i_reg_289 = ap_const_lv1_1)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0));
    end process;

        ap_block_state11_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state12_pp0_stage0_iter1_assign_proc : process(m_axi_srcPtr_V_RVALID, tmp_14_i_i_i_i_i_reg_289)
    begin
                ap_block_state12_pp0_stage0_iter1 <= ((m_axi_srcPtr_V_RVALID = ap_const_logic_0) and (tmp_14_i_i_i_i_i_reg_289 = ap_const_lv1_1));
    end process;


    ap_block_state13_pp0_stage0_iter2_assign_proc : process(strm_V_V_i_full_n, tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg)
    begin
                ap_block_state13_pp0_stage0_iter2 <= ((strm_V_V_i_full_n = ap_const_logic_0) and (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_condition_pp0_exit_iter0_state11_assign_proc : process(tmp_14_i_i_i_i_i_fu_236_p2)
    begin
        if ((tmp_14_i_i_i_i_i_fu_236_p2 = ap_const_lv1_0)) then 
            ap_condition_pp0_exit_iter0_state11 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state11 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    ap_sig_ioackin_m_axi_srcPtr_V_ARREADY_assign_proc : process(m_axi_srcPtr_V_ARREADY, ap_reg_ioackin_m_axi_srcPtr_V_ARREADY)
    begin
        if ((ap_reg_ioackin_m_axi_srcPtr_V_ARREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_srcPtr_V_ARREADY <= m_axi_srcPtr_V_ARREADY;
        else 
            ap_sig_ioackin_m_axi_srcPtr_V_ARREADY <= ap_const_logic_1;
        end if; 
    end process;


    dstMat_cols_c_i_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstMat_cols_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_cols_c_i_blk_n <= dstMat_cols_c_i_full_n;
        else 
            dstMat_cols_c_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstMat_cols_c_i_din <= scalar_dstMat_cols_dout;

    dstMat_cols_c_i_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_cols_c_i_write <= ap_const_logic_1;
        else 
            dstMat_cols_c_i_write <= ap_const_logic_0;
        end if; 
    end process;


    dstMat_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstMat_cols_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_cols_out_blk_n <= dstMat_cols_out_full_n;
        else 
            dstMat_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstMat_cols_out_din <= scalar_dstMat_cols_dout;

    dstMat_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_cols_out_write <= ap_const_logic_1;
        else 
            dstMat_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    dstMat_rows_c_i_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstMat_rows_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_rows_c_i_blk_n <= dstMat_rows_c_i_full_n;
        else 
            dstMat_rows_c_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstMat_rows_c_i_din <= scalar_dstMat_rows_dout;

    dstMat_rows_c_i_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_rows_c_i_write <= ap_const_logic_1;
        else 
            dstMat_rows_c_i_write <= ap_const_logic_0;
        end if; 
    end process;


    dstMat_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstMat_rows_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_rows_out_blk_n <= dstMat_rows_out_full_n;
        else 
            dstMat_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstMat_rows_out_din <= scalar_dstMat_rows_dout;

    dstMat_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstMat_rows_out_write <= ap_const_logic_1;
        else 
            dstMat_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;

    i_cast_i_i_i_i_i_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_i_i_i_i_i_reg_150),30));
    i_fu_241_p2 <= std_logic_vector(unsigned(i_i_i_i_i_i_reg_150) + unsigned(ap_const_lv29_1));

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loop_count_fu_221_p3 <= 
        p_neg_t_i_i_i_i_i_fu_215_p2 when (tmp_8_reg_273(0) = '1') else 
        tmp_13_cast_i_i_i_i_s_fu_187_p1;
    m_axi_srcPtr_V_ARADDR <= srcPtr_V_addr_reg_247;
    m_axi_srcPtr_V_ARBURST <= ap_const_lv2_0;
    m_axi_srcPtr_V_ARCACHE <= ap_const_lv4_0;
    m_axi_srcPtr_V_ARID <= ap_const_lv1_0;
    m_axi_srcPtr_V_ARLEN <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loop_count_reg_278),32));
    m_axi_srcPtr_V_ARLOCK <= ap_const_lv2_0;
    m_axi_srcPtr_V_ARPROT <= ap_const_lv3_0;
    m_axi_srcPtr_V_ARQOS <= ap_const_lv4_0;
    m_axi_srcPtr_V_ARREGION <= ap_const_lv4_0;
    m_axi_srcPtr_V_ARSIZE <= ap_const_lv3_0;
    m_axi_srcPtr_V_ARUSER <= ap_const_lv1_0;

    m_axi_srcPtr_V_ARVALID_assign_proc : process(ap_CS_fsm_state4, ap_reg_ioackin_m_axi_srcPtr_V_ARREADY)
    begin
        if (((ap_reg_ioackin_m_axi_srcPtr_V_ARREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_srcPtr_V_ARVALID <= ap_const_logic_1;
        else 
            m_axi_srcPtr_V_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_srcPtr_V_AWADDR <= ap_const_lv32_0;
    m_axi_srcPtr_V_AWBURST <= ap_const_lv2_0;
    m_axi_srcPtr_V_AWCACHE <= ap_const_lv4_0;
    m_axi_srcPtr_V_AWID <= ap_const_lv1_0;
    m_axi_srcPtr_V_AWLEN <= ap_const_lv32_0;
    m_axi_srcPtr_V_AWLOCK <= ap_const_lv2_0;
    m_axi_srcPtr_V_AWPROT <= ap_const_lv3_0;
    m_axi_srcPtr_V_AWQOS <= ap_const_lv4_0;
    m_axi_srcPtr_V_AWREGION <= ap_const_lv4_0;
    m_axi_srcPtr_V_AWSIZE <= ap_const_lv3_0;
    m_axi_srcPtr_V_AWUSER <= ap_const_lv1_0;
    m_axi_srcPtr_V_AWVALID <= ap_const_logic_0;
    m_axi_srcPtr_V_BREADY <= ap_const_logic_0;

    m_axi_srcPtr_V_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_14_i_i_i_i_i_reg_289, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_14_i_i_i_i_i_reg_289 = ap_const_lv1_1))) then 
            m_axi_srcPtr_V_RREADY <= ap_const_logic_1;
        else 
            m_axi_srcPtr_V_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_srcPtr_V_WDATA <= ap_const_lv8_0;
    m_axi_srcPtr_V_WID <= ap_const_lv1_0;
    m_axi_srcPtr_V_WLAST <= ap_const_logic_0;
    m_axi_srcPtr_V_WSTRB <= ap_const_lv1_0;
    m_axi_srcPtr_V_WUSER <= ap_const_lv1_0;
    m_axi_srcPtr_V_WVALID <= ap_const_logic_0;
    p_lshr_cast_i_i_i_i_i_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_i_fu_201_p4),30));
    p_neg_i_i_i_i_i_fu_195_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(tmp_7_fu_190_p2));
    p_neg_t_i_i_i_i_i_fu_215_p2 <= std_logic_vector(unsigned(ap_const_lv30_0) - unsigned(p_lshr_cast_i_i_i_i_i_fu_211_p1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    scalar_dstMat_cols_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            scalar_dstMat_cols_blk_n <= scalar_dstMat_cols_empty_n;
        else 
            scalar_dstMat_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    scalar_dstMat_cols_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            scalar_dstMat_cols_read <= ap_const_logic_1;
        else 
            scalar_dstMat_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    scalar_dstMat_rows_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            scalar_dstMat_rows_blk_n <= scalar_dstMat_rows_empty_n;
        else 
            scalar_dstMat_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    scalar_dstMat_rows_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            scalar_dstMat_rows_read <= ap_const_logic_1;
        else 
            scalar_dstMat_rows_read <= ap_const_logic_0;
        end if; 
    end process;


    srcPtr_V_blk_n_AR_assign_proc : process(m_axi_srcPtr_V_ARREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            srcPtr_V_blk_n_AR <= m_axi_srcPtr_V_ARREADY;
        else 
            srcPtr_V_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    srcPtr_V_blk_n_R_assign_proc : process(m_axi_srcPtr_V_RVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_14_i_i_i_i_i_reg_289)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_14_i_i_i_i_i_reg_289 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            srcPtr_V_blk_n_R <= m_axi_srcPtr_V_RVALID;
        else 
            srcPtr_V_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    srcPtr_V_offset_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcPtr_V_offset_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcPtr_V_offset_blk_n <= srcPtr_V_offset_empty_n;
        else 
            srcPtr_V_offset_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    srcPtr_V_offset_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, scalar_dstMat_cols_empty_n, dstMat_cols_out_full_n, scalar_dstMat_rows_empty_n, dstMat_rows_out_full_n, srcPtr_V_offset_empty_n, dstMat_rows_c_i_full_n, dstMat_cols_c_i_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (dstMat_rows_out_full_n = ap_const_logic_0) or (scalar_dstMat_rows_empty_n = ap_const_logic_0) or (dstMat_cols_out_full_n = ap_const_logic_0) or (scalar_dstMat_cols_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (dstMat_cols_c_i_full_n = ap_const_logic_0) or (dstMat_rows_c_i_full_n = ap_const_logic_0) or (srcPtr_V_offset_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcPtr_V_offset_read <= ap_const_logic_1;
        else 
            srcPtr_V_offset_read <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    strm_V_V_i_blk_n_assign_proc : process(strm_V_V_i_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            strm_V_V_i_blk_n <= strm_V_V_i_full_n;
        else 
            strm_V_V_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    strm_V_V_i_din <= tmp_V_reg_298;

    strm_V_V_i_write_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg = ap_const_lv1_1))) then 
            strm_V_V_i_write <= ap_const_logic_1;
        else 
            strm_V_V_i_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_13_cast_i_i_i_i_s_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_268),30));
    tmp_14_i_i_i_i_i_fu_236_p2 <= "1" when (signed(i_cast_i_i_i_i_i_fu_232_p1) < signed(loop_count_reg_278)) else "0";
    tmp_1_i_i_i_i_i_fu_171_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(scalar_dstMat_cols_r_reg_253) * signed(scalar_dstMat_rows_r_reg_258))), 32));
    tmp_6_i_fu_201_p4 <= p_neg_i_i_i_i_i_fu_195_p2(31 downto 3);
    tmp_7_fu_190_p2 <= std_logic_vector(shift_left(unsigned(tmp_1_i_i_i_i_i_reg_263),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    tmp_fu_175_p1 <= tmp_1_i_i_i_i_i_fu_171_p2(29 - 1 downto 0);
        tmp_i_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(srcPtr_V_offset_dout),64));

end behav;
