-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hlsStrm2Array is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    srcStrm_V_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    srcStrm_V_V_empty_n : IN STD_LOGIC;
    srcStrm_V_V_read : OUT STD_LOGIC;
    m_axi_dstPtr_V_AWVALID : OUT STD_LOGIC;
    m_axi_dstPtr_V_AWREADY : IN STD_LOGIC;
    m_axi_dstPtr_V_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dstPtr_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dstPtr_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dstPtr_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dstPtr_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dstPtr_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dstPtr_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dstPtr_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dstPtr_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dstPtr_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_WVALID : OUT STD_LOGIC;
    m_axi_dstPtr_V_WREADY : IN STD_LOGIC;
    m_axi_dstPtr_V_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_dstPtr_V_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_WLAST : OUT STD_LOGIC;
    m_axi_dstPtr_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_ARVALID : OUT STD_LOGIC;
    m_axi_dstPtr_V_ARREADY : IN STD_LOGIC;
    m_axi_dstPtr_V_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dstPtr_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dstPtr_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dstPtr_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dstPtr_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dstPtr_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dstPtr_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dstPtr_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dstPtr_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dstPtr_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_RVALID : IN STD_LOGIC;
    m_axi_dstPtr_V_RREADY : OUT STD_LOGIC;
    m_axi_dstPtr_V_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_dstPtr_V_RLAST : IN STD_LOGIC;
    m_axi_dstPtr_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dstPtr_V_BVALID : IN STD_LOGIC;
    m_axi_dstPtr_V_BREADY : OUT STD_LOGIC;
    m_axi_dstPtr_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dstPtr_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dstPtr_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    dstPtr_V_offset_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    dstPtr_V_offset_empty_n : IN STD_LOGIC;
    dstPtr_V_offset_read : OUT STD_LOGIC;
    srcMat_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    srcMat_rows_empty_n : IN STD_LOGIC;
    srcMat_rows_read : OUT STD_LOGIC;
    srcMat_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    srcMat_cols_empty_n : IN STD_LOGIC;
    srcMat_cols_read : OUT STD_LOGIC );
end;


architecture behav of hlsStrm2Array is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv29_1 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000001";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal srcStrm_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_10_i_i_i_reg_249 : STD_LOGIC_VECTOR (0 downto 0);
    signal dstPtr_V_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal dstPtr_V_blk_n_W : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal tmp_10_i_i_i_reg_249_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dstPtr_V_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal dstPtr_V_offset_blk_n : STD_LOGIC;
    signal srcMat_rows_blk_n : STD_LOGIC;
    signal srcMat_cols_blk_n : STD_LOGIC;
    signal i_i_i_i_reg_115 : STD_LOGIC_VECTOR (28 downto 0);
    signal dstPtr_V_addr_reg_212 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal srcMat_rows_read_reg_218 : STD_LOGIC_VECTOR (31 downto 0);
    signal srcMat_cols_read_reg_223 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_i_i_i_fu_136_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_i_i_i_reg_228 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_140_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_reg_233 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_6_reg_238 : STD_LOGIC_VECTOR (0 downto 0);
    signal loop_count_fu_186_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal loop_count_reg_243 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_10_i_i_i_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter2 : BOOLEAN;
    signal ap_sig_ioackin_m_axi_dstPtr_V_WREADY : STD_LOGIC;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_206_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_V_reg_258 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_ioackin_m_axi_dstPtr_V_AWREADY : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state5 : STD_LOGIC;
    signal tmp_i_fu_126_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_m_axi_dstPtr_V_AWREADY : STD_LOGIC := '0';
    signal ap_reg_ioackin_m_axi_dstPtr_V_WREADY : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_5_fu_155_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_neg_i_i_i_fu_160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_i_fu_166_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_lshr_cast_i_i_i_fu_176_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_neg_t_i_i_i_fu_180_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_9_cast_i_i_i_fu_152_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal i_cast_i_i_i_fu_197_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((m_axi_dstPtr_V_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_sig_ioackin_m_axi_dstPtr_V_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state5)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state5);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_sig_ioackin_m_axi_dstPtr_V_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_dstPtr_V_AWREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_dstPtr_V_AWREADY <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                    if ((ap_sig_ioackin_m_axi_dstPtr_V_AWREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_dstPtr_V_AWREADY <= ap_const_logic_0;
                    elsif ((m_axi_dstPtr_V_AWREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_dstPtr_V_AWREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_dstPtr_V_WREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_dstPtr_V_WREADY <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (tmp_10_i_i_i_reg_249_pp0_iter1_reg = ap_const_lv1_1))) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                        ap_reg_ioackin_m_axi_dstPtr_V_WREADY <= ap_const_logic_0;
                    elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (m_axi_dstPtr_V_WREADY = ap_const_logic_1))) then 
                        ap_reg_ioackin_m_axi_dstPtr_V_WREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    i_i_i_i_reg_115_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_10_i_i_i_fu_201_p2 = ap_const_lv1_1))) then 
                i_i_i_i_reg_115 <= i_fu_206_p2;
            elsif (((ap_sig_ioackin_m_axi_dstPtr_V_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_i_i_i_reg_115 <= ap_const_lv29_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((srcMat_rows_empty_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                dstPtr_V_addr_reg_212 <= tmp_i_fu_126_p1(32 - 1 downto 0);
                srcMat_cols_read_reg_223 <= srcMat_cols_dout;
                srcMat_rows_read_reg_218 <= srcMat_rows_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                loop_count_reg_243 <= loop_count_fu_186_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_10_i_i_i_reg_249 <= tmp_10_i_i_i_fu_201_p2;
                tmp_10_i_i_i_reg_249_pp0_iter1_reg <= tmp_10_i_i_i_reg_249;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_1_i_i_i_reg_228 <= tmp_1_i_i_i_fu_136_p2;
                tmp_6_reg_238 <= tmp_1_i_i_i_fu_136_p2(28 downto 28);
                tmp_reg_233 <= tmp_fu_140_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_10_i_i_i_reg_249 = ap_const_lv1_1))) then
                tmp_V_reg_258 <= srcStrm_V_V_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, m_axi_dstPtr_V_BVALID, dstPtr_V_offset_empty_n, srcMat_rows_empty_n, srcMat_cols_empty_n, ap_enable_reg_pp0_iter1, ap_CS_fsm_state4, ap_enable_reg_pp0_iter2, ap_CS_fsm_state12, tmp_10_i_i_i_fu_201_p2, ap_enable_reg_pp0_iter0, ap_sig_ioackin_m_axi_dstPtr_V_AWREADY, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((srcMat_rows_empty_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_sig_ioackin_m_axi_dstPtr_V_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((tmp_10_i_i_i_fu_201_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((tmp_10_i_i_i_fu_201_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((m_axi_dstPtr_V_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(srcStrm_V_V_empty_n, ap_enable_reg_pp0_iter1, tmp_10_i_i_i_reg_249)
    begin
                ap_block_pp0_stage0_01001 <= ((srcStrm_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_10_i_i_i_reg_249 = ap_const_lv1_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(srcStrm_V_V_empty_n, ap_enable_reg_pp0_iter1, tmp_10_i_i_i_reg_249, ap_enable_reg_pp0_iter2, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state7_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((srcStrm_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_10_i_i_i_reg_249 = ap_const_lv1_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(srcStrm_V_V_empty_n, ap_enable_reg_pp0_iter1, tmp_10_i_i_i_reg_249, ap_enable_reg_pp0_iter2, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state7_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((srcStrm_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_10_i_i_i_reg_249 = ap_const_lv1_1)));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, dstPtr_V_offset_empty_n, srcMat_rows_empty_n, srcMat_cols_empty_n)
    begin
                ap_block_state1 <= ((srcMat_rows_empty_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state5_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_pp0_stage0_iter1_assign_proc : process(srcStrm_V_V_empty_n, tmp_10_i_i_i_reg_249)
    begin
                ap_block_state6_pp0_stage0_iter1 <= ((srcStrm_V_V_empty_n = ap_const_logic_0) and (tmp_10_i_i_i_reg_249 = ap_const_lv1_1));
    end process;


    ap_block_state7_io_assign_proc : process(tmp_10_i_i_i_reg_249_pp0_iter1_reg, ap_sig_ioackin_m_axi_dstPtr_V_WREADY)
    begin
                ap_block_state7_io <= ((ap_sig_ioackin_m_axi_dstPtr_V_WREADY = ap_const_logic_0) and (tmp_10_i_i_i_reg_249_pp0_iter1_reg = ap_const_lv1_1));
    end process;

        ap_block_state7_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state5_assign_proc : process(tmp_10_i_i_i_fu_201_p2)
    begin
        if ((tmp_10_i_i_i_fu_201_p2 = ap_const_lv1_0)) then 
            ap_condition_pp0_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, m_axi_dstPtr_V_BVALID, ap_CS_fsm_state12)
    begin
        if (((m_axi_dstPtr_V_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axi_dstPtr_V_BVALID, ap_CS_fsm_state12)
    begin
        if (((m_axi_dstPtr_V_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_ioackin_m_axi_dstPtr_V_AWREADY_assign_proc : process(m_axi_dstPtr_V_AWREADY, ap_reg_ioackin_m_axi_dstPtr_V_AWREADY)
    begin
        if ((ap_reg_ioackin_m_axi_dstPtr_V_AWREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_dstPtr_V_AWREADY <= m_axi_dstPtr_V_AWREADY;
        else 
            ap_sig_ioackin_m_axi_dstPtr_V_AWREADY <= ap_const_logic_1;
        end if; 
    end process;


    ap_sig_ioackin_m_axi_dstPtr_V_WREADY_assign_proc : process(m_axi_dstPtr_V_WREADY, ap_reg_ioackin_m_axi_dstPtr_V_WREADY)
    begin
        if ((ap_reg_ioackin_m_axi_dstPtr_V_WREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_dstPtr_V_WREADY <= m_axi_dstPtr_V_WREADY;
        else 
            ap_sig_ioackin_m_axi_dstPtr_V_WREADY <= ap_const_logic_1;
        end if; 
    end process;


    dstPtr_V_blk_n_AW_assign_proc : process(m_axi_dstPtr_V_AWREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dstPtr_V_blk_n_AW <= m_axi_dstPtr_V_AWREADY;
        else 
            dstPtr_V_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    dstPtr_V_blk_n_B_assign_proc : process(m_axi_dstPtr_V_BVALID, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            dstPtr_V_blk_n_B <= m_axi_dstPtr_V_BVALID;
        else 
            dstPtr_V_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    dstPtr_V_blk_n_W_assign_proc : process(m_axi_dstPtr_V_WREADY, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, tmp_10_i_i_i_reg_249_pp0_iter1_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (tmp_10_i_i_i_reg_249_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            dstPtr_V_blk_n_W <= m_axi_dstPtr_V_WREADY;
        else 
            dstPtr_V_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    dstPtr_V_offset_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, dstPtr_V_offset_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstPtr_V_offset_blk_n <= dstPtr_V_offset_empty_n;
        else 
            dstPtr_V_offset_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dstPtr_V_offset_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, dstPtr_V_offset_empty_n, srcMat_rows_empty_n, srcMat_cols_empty_n)
    begin
        if ((not(((srcMat_rows_empty_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstPtr_V_offset_read <= ap_const_logic_1;
        else 
            dstPtr_V_offset_read <= ap_const_logic_0;
        end if; 
    end process;

    i_cast_i_i_i_fu_197_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_i_i_i_reg_115),30));
    i_fu_206_p2 <= std_logic_vector(unsigned(i_i_i_i_reg_115) + unsigned(ap_const_lv29_1));
    loop_count_fu_186_p3 <= 
        p_neg_t_i_i_i_fu_180_p2 when (tmp_6_reg_238(0) = '1') else 
        tmp_9_cast_i_i_i_fu_152_p1;
    m_axi_dstPtr_V_ARADDR <= ap_const_lv32_0;
    m_axi_dstPtr_V_ARBURST <= ap_const_lv2_0;
    m_axi_dstPtr_V_ARCACHE <= ap_const_lv4_0;
    m_axi_dstPtr_V_ARID <= ap_const_lv1_0;
    m_axi_dstPtr_V_ARLEN <= ap_const_lv32_0;
    m_axi_dstPtr_V_ARLOCK <= ap_const_lv2_0;
    m_axi_dstPtr_V_ARPROT <= ap_const_lv3_0;
    m_axi_dstPtr_V_ARQOS <= ap_const_lv4_0;
    m_axi_dstPtr_V_ARREGION <= ap_const_lv4_0;
    m_axi_dstPtr_V_ARSIZE <= ap_const_lv3_0;
    m_axi_dstPtr_V_ARUSER <= ap_const_lv1_0;
    m_axi_dstPtr_V_ARVALID <= ap_const_logic_0;
    m_axi_dstPtr_V_AWADDR <= dstPtr_V_addr_reg_212;
    m_axi_dstPtr_V_AWBURST <= ap_const_lv2_0;
    m_axi_dstPtr_V_AWCACHE <= ap_const_lv4_0;
    m_axi_dstPtr_V_AWID <= ap_const_lv1_0;
    m_axi_dstPtr_V_AWLEN <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loop_count_reg_243),32));
    m_axi_dstPtr_V_AWLOCK <= ap_const_lv2_0;
    m_axi_dstPtr_V_AWPROT <= ap_const_lv3_0;
    m_axi_dstPtr_V_AWQOS <= ap_const_lv4_0;
    m_axi_dstPtr_V_AWREGION <= ap_const_lv4_0;
    m_axi_dstPtr_V_AWSIZE <= ap_const_lv3_0;
    m_axi_dstPtr_V_AWUSER <= ap_const_lv1_0;

    m_axi_dstPtr_V_AWVALID_assign_proc : process(ap_CS_fsm_state4, ap_reg_ioackin_m_axi_dstPtr_V_AWREADY)
    begin
        if (((ap_reg_ioackin_m_axi_dstPtr_V_AWREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_dstPtr_V_AWVALID <= ap_const_logic_1;
        else 
            m_axi_dstPtr_V_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_dstPtr_V_BREADY_assign_proc : process(m_axi_dstPtr_V_BVALID, ap_CS_fsm_state12)
    begin
        if (((m_axi_dstPtr_V_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            m_axi_dstPtr_V_BREADY <= ap_const_logic_1;
        else 
            m_axi_dstPtr_V_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_dstPtr_V_RREADY <= ap_const_logic_0;
    m_axi_dstPtr_V_WDATA <= tmp_V_reg_258;
    m_axi_dstPtr_V_WID <= ap_const_lv1_0;
    m_axi_dstPtr_V_WLAST <= ap_const_logic_0;
    m_axi_dstPtr_V_WSTRB <= ap_const_lv1_1;
    m_axi_dstPtr_V_WUSER <= ap_const_lv1_0;

    m_axi_dstPtr_V_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_10_i_i_i_reg_249_pp0_iter1_reg, ap_reg_ioackin_m_axi_dstPtr_V_WREADY, ap_block_pp0_stage0_01001)
    begin
        if (((ap_reg_ioackin_m_axi_dstPtr_V_WREADY = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (tmp_10_i_i_i_reg_249_pp0_iter1_reg = ap_const_lv1_1))) then 
            m_axi_dstPtr_V_WVALID <= ap_const_logic_1;
        else 
            m_axi_dstPtr_V_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_lshr_cast_i_i_i_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_i_fu_166_p4),30));
    p_neg_i_i_i_fu_160_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(tmp_5_fu_155_p2));
    p_neg_t_i_i_i_fu_180_p2 <= std_logic_vector(unsigned(ap_const_lv30_0) - unsigned(p_lshr_cast_i_i_i_fu_176_p1));

    srcMat_cols_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, srcMat_cols_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_cols_blk_n <= srcMat_cols_empty_n;
        else 
            srcMat_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    srcMat_cols_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, dstPtr_V_offset_empty_n, srcMat_rows_empty_n, srcMat_cols_empty_n)
    begin
        if ((not(((srcMat_rows_empty_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_cols_read <= ap_const_logic_1;
        else 
            srcMat_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    srcMat_rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_rows_blk_n <= srcMat_rows_empty_n;
        else 
            srcMat_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    srcMat_rows_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, dstPtr_V_offset_empty_n, srcMat_rows_empty_n, srcMat_cols_empty_n)
    begin
        if ((not(((srcMat_rows_empty_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_rows_read <= ap_const_logic_1;
        else 
            srcMat_rows_read <= ap_const_logic_0;
        end if; 
    end process;


    srcStrm_V_V_blk_n_assign_proc : process(srcStrm_V_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_10_i_i_i_reg_249)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_10_i_i_i_reg_249 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            srcStrm_V_V_blk_n <= srcStrm_V_V_empty_n;
        else 
            srcStrm_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    srcStrm_V_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_10_i_i_i_reg_249, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_10_i_i_i_reg_249 = ap_const_lv1_1))) then 
            srcStrm_V_V_read <= ap_const_logic_1;
        else 
            srcStrm_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_i_i_i_fu_201_p2 <= "1" when (signed(i_cast_i_i_i_fu_197_p1) < signed(loop_count_reg_243)) else "0";
    tmp_1_i_i_i_fu_136_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(srcMat_cols_read_reg_223) * signed(srcMat_rows_read_reg_218))), 32));
    tmp_4_i_fu_166_p4 <= p_neg_i_i_i_fu_160_p2(31 downto 3);
    tmp_5_fu_155_p2 <= std_logic_vector(shift_left(unsigned(tmp_1_i_i_i_reg_228),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    tmp_9_cast_i_i_i_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_233),30));
    tmp_fu_140_p1 <= tmp_1_i_i_i_fu_136_p2(29 - 1 downto 0);
        tmp_i_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(dstPtr_V_offset_dout),64));

end behav;
