// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Array2hlsStrm54_HH_
#define _Array2hlsStrm54_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Array2hlsStrm54 : public sc_module {
    // Port declarations 79
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<32> > scalar_dstMat_cols_dout;
    sc_in< sc_logic > scalar_dstMat_cols_empty_n;
    sc_out< sc_logic > scalar_dstMat_cols_read;
    sc_out< sc_lv<32> > dstMat_cols_out_din;
    sc_in< sc_logic > dstMat_cols_out_full_n;
    sc_out< sc_logic > dstMat_cols_out_write;
    sc_in< sc_lv<32> > scalar_dstMat_rows_dout;
    sc_in< sc_logic > scalar_dstMat_rows_empty_n;
    sc_out< sc_logic > scalar_dstMat_rows_read;
    sc_out< sc_lv<32> > dstMat_rows_out_din;
    sc_in< sc_logic > dstMat_rows_out_full_n;
    sc_out< sc_logic > dstMat_rows_out_write;
    sc_out< sc_logic > m_axi_srcPtr_V_AWVALID;
    sc_in< sc_logic > m_axi_srcPtr_V_AWREADY;
    sc_out< sc_lv<32> > m_axi_srcPtr_V_AWADDR;
    sc_out< sc_lv<1> > m_axi_srcPtr_V_AWID;
    sc_out< sc_lv<32> > m_axi_srcPtr_V_AWLEN;
    sc_out< sc_lv<3> > m_axi_srcPtr_V_AWSIZE;
    sc_out< sc_lv<2> > m_axi_srcPtr_V_AWBURST;
    sc_out< sc_lv<2> > m_axi_srcPtr_V_AWLOCK;
    sc_out< sc_lv<4> > m_axi_srcPtr_V_AWCACHE;
    sc_out< sc_lv<3> > m_axi_srcPtr_V_AWPROT;
    sc_out< sc_lv<4> > m_axi_srcPtr_V_AWQOS;
    sc_out< sc_lv<4> > m_axi_srcPtr_V_AWREGION;
    sc_out< sc_lv<1> > m_axi_srcPtr_V_AWUSER;
    sc_out< sc_logic > m_axi_srcPtr_V_WVALID;
    sc_in< sc_logic > m_axi_srcPtr_V_WREADY;
    sc_out< sc_lv<8> > m_axi_srcPtr_V_WDATA;
    sc_out< sc_lv<1> > m_axi_srcPtr_V_WSTRB;
    sc_out< sc_logic > m_axi_srcPtr_V_WLAST;
    sc_out< sc_lv<1> > m_axi_srcPtr_V_WID;
    sc_out< sc_lv<1> > m_axi_srcPtr_V_WUSER;
    sc_out< sc_logic > m_axi_srcPtr_V_ARVALID;
    sc_in< sc_logic > m_axi_srcPtr_V_ARREADY;
    sc_out< sc_lv<32> > m_axi_srcPtr_V_ARADDR;
    sc_out< sc_lv<1> > m_axi_srcPtr_V_ARID;
    sc_out< sc_lv<32> > m_axi_srcPtr_V_ARLEN;
    sc_out< sc_lv<3> > m_axi_srcPtr_V_ARSIZE;
    sc_out< sc_lv<2> > m_axi_srcPtr_V_ARBURST;
    sc_out< sc_lv<2> > m_axi_srcPtr_V_ARLOCK;
    sc_out< sc_lv<4> > m_axi_srcPtr_V_ARCACHE;
    sc_out< sc_lv<3> > m_axi_srcPtr_V_ARPROT;
    sc_out< sc_lv<4> > m_axi_srcPtr_V_ARQOS;
    sc_out< sc_lv<4> > m_axi_srcPtr_V_ARREGION;
    sc_out< sc_lv<1> > m_axi_srcPtr_V_ARUSER;
    sc_in< sc_logic > m_axi_srcPtr_V_RVALID;
    sc_out< sc_logic > m_axi_srcPtr_V_RREADY;
    sc_in< sc_lv<8> > m_axi_srcPtr_V_RDATA;
    sc_in< sc_logic > m_axi_srcPtr_V_RLAST;
    sc_in< sc_lv<1> > m_axi_srcPtr_V_RID;
    sc_in< sc_lv<1> > m_axi_srcPtr_V_RUSER;
    sc_in< sc_lv<2> > m_axi_srcPtr_V_RRESP;
    sc_in< sc_logic > m_axi_srcPtr_V_BVALID;
    sc_out< sc_logic > m_axi_srcPtr_V_BREADY;
    sc_in< sc_lv<2> > m_axi_srcPtr_V_BRESP;
    sc_in< sc_lv<1> > m_axi_srcPtr_V_BID;
    sc_in< sc_lv<1> > m_axi_srcPtr_V_BUSER;
    sc_in< sc_lv<32> > srcPtr_V_offset_dout;
    sc_in< sc_logic > srcPtr_V_offset_empty_n;
    sc_out< sc_logic > srcPtr_V_offset_read;
    sc_out< sc_lv<8> > strm_V_V_i_din;
    sc_in< sc_logic > strm_V_V_i_full_n;
    sc_out< sc_logic > strm_V_V_i_write;
    sc_out< sc_lv<32> > dstMat_rows_c_i_din;
    sc_in< sc_logic > dstMat_rows_c_i_full_n;
    sc_out< sc_logic > dstMat_rows_c_i_write;
    sc_out< sc_lv<32> > dstMat_cols_c_i_din;
    sc_in< sc_logic > dstMat_cols_c_i_full_n;
    sc_out< sc_logic > dstMat_cols_c_i_write;


    // Module declarations
    Array2hlsStrm54(sc_module_name name);
    SC_HAS_PROCESS(Array2hlsStrm54);

    ~Array2hlsStrm54();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<12> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > scalar_dstMat_cols_blk_n;
    sc_signal< sc_logic > dstMat_cols_out_blk_n;
    sc_signal< sc_logic > scalar_dstMat_rows_blk_n;
    sc_signal< sc_logic > dstMat_rows_out_blk_n;
    sc_signal< sc_logic > srcPtr_V_blk_n_AR;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > srcPtr_V_blk_n_R;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > tmp_14_i_i_i_i_i_reg_289;
    sc_signal< sc_logic > srcPtr_V_offset_blk_n;
    sc_signal< sc_logic > strm_V_V_i_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg;
    sc_signal< sc_logic > dstMat_rows_c_i_blk_n;
    sc_signal< sc_logic > dstMat_cols_c_i_blk_n;
    sc_signal< sc_lv<29> > i_i_i_i_i_i_reg_150;
    sc_signal< sc_lv<32> > srcPtr_V_addr_reg_247;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > scalar_dstMat_cols_r_reg_253;
    sc_signal< sc_lv<32> > scalar_dstMat_rows_r_reg_258;
    sc_signal< sc_lv<32> > tmp_1_i_i_i_i_i_fu_171_p2;
    sc_signal< sc_lv<32> > tmp_1_i_i_i_i_i_reg_263;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<29> > tmp_fu_175_p1;
    sc_signal< sc_lv<29> > tmp_reg_268;
    sc_signal< sc_lv<1> > tmp_8_reg_273;
    sc_signal< sc_lv<30> > loop_count_fu_221_p3;
    sc_signal< sc_lv<30> > loop_count_reg_278;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_sig_ioackin_m_axi_srcPtr_V_ARREADY;
    sc_signal< sc_lv<1> > tmp_14_i_i_i_i_i_fu_236_p2;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state12_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state13_pp0_stage0_iter2;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<29> > i_fu_241_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<8> > tmp_V_reg_298;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state11;
    sc_signal< sc_lv<64> > tmp_i_fu_161_p1;
    sc_signal< sc_logic > ap_reg_ioackin_m_axi_srcPtr_V_ARREADY;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<32> > tmp_7_fu_190_p2;
    sc_signal< sc_lv<32> > p_neg_i_i_i_i_i_fu_195_p2;
    sc_signal< sc_lv<29> > tmp_6_i_fu_201_p4;
    sc_signal< sc_lv<30> > p_lshr_cast_i_i_i_i_i_fu_211_p1;
    sc_signal< sc_lv<30> > p_neg_t_i_i_i_i_i_fu_215_p2;
    sc_signal< sc_lv<30> > tmp_13_cast_i_i_i_i_s_fu_187_p1;
    sc_signal< sc_lv<30> > i_cast_i_i_i_i_i_fu_232_p1;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<12> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<12> ap_ST_fsm_state1;
    static const sc_lv<12> ap_ST_fsm_state2;
    static const sc_lv<12> ap_ST_fsm_state3;
    static const sc_lv<12> ap_ST_fsm_state4;
    static const sc_lv<12> ap_ST_fsm_state5;
    static const sc_lv<12> ap_ST_fsm_state6;
    static const sc_lv<12> ap_ST_fsm_state7;
    static const sc_lv<12> ap_ST_fsm_state8;
    static const sc_lv<12> ap_ST_fsm_state9;
    static const sc_lv<12> ap_ST_fsm_state10;
    static const sc_lv<12> ap_ST_fsm_pp0_stage0;
    static const sc_lv<12> ap_ST_fsm_state14;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_A;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<29> ap_const_lv29_0;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<30> ap_const_lv30_0;
    static const sc_lv<29> ap_const_lv29_1;
    static const sc_lv<32> ap_const_lv32_B;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state11_pp0_stage0_iter0();
    void thread_ap_block_state12_pp0_stage0_iter1();
    void thread_ap_block_state13_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter0_state11();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_ap_sig_ioackin_m_axi_srcPtr_V_ARREADY();
    void thread_dstMat_cols_c_i_blk_n();
    void thread_dstMat_cols_c_i_din();
    void thread_dstMat_cols_c_i_write();
    void thread_dstMat_cols_out_blk_n();
    void thread_dstMat_cols_out_din();
    void thread_dstMat_cols_out_write();
    void thread_dstMat_rows_c_i_blk_n();
    void thread_dstMat_rows_c_i_din();
    void thread_dstMat_rows_c_i_write();
    void thread_dstMat_rows_out_blk_n();
    void thread_dstMat_rows_out_din();
    void thread_dstMat_rows_out_write();
    void thread_i_cast_i_i_i_i_i_fu_232_p1();
    void thread_i_fu_241_p2();
    void thread_internal_ap_ready();
    void thread_loop_count_fu_221_p3();
    void thread_m_axi_srcPtr_V_ARADDR();
    void thread_m_axi_srcPtr_V_ARBURST();
    void thread_m_axi_srcPtr_V_ARCACHE();
    void thread_m_axi_srcPtr_V_ARID();
    void thread_m_axi_srcPtr_V_ARLEN();
    void thread_m_axi_srcPtr_V_ARLOCK();
    void thread_m_axi_srcPtr_V_ARPROT();
    void thread_m_axi_srcPtr_V_ARQOS();
    void thread_m_axi_srcPtr_V_ARREGION();
    void thread_m_axi_srcPtr_V_ARSIZE();
    void thread_m_axi_srcPtr_V_ARUSER();
    void thread_m_axi_srcPtr_V_ARVALID();
    void thread_m_axi_srcPtr_V_AWADDR();
    void thread_m_axi_srcPtr_V_AWBURST();
    void thread_m_axi_srcPtr_V_AWCACHE();
    void thread_m_axi_srcPtr_V_AWID();
    void thread_m_axi_srcPtr_V_AWLEN();
    void thread_m_axi_srcPtr_V_AWLOCK();
    void thread_m_axi_srcPtr_V_AWPROT();
    void thread_m_axi_srcPtr_V_AWQOS();
    void thread_m_axi_srcPtr_V_AWREGION();
    void thread_m_axi_srcPtr_V_AWSIZE();
    void thread_m_axi_srcPtr_V_AWUSER();
    void thread_m_axi_srcPtr_V_AWVALID();
    void thread_m_axi_srcPtr_V_BREADY();
    void thread_m_axi_srcPtr_V_RREADY();
    void thread_m_axi_srcPtr_V_WDATA();
    void thread_m_axi_srcPtr_V_WID();
    void thread_m_axi_srcPtr_V_WLAST();
    void thread_m_axi_srcPtr_V_WSTRB();
    void thread_m_axi_srcPtr_V_WUSER();
    void thread_m_axi_srcPtr_V_WVALID();
    void thread_p_lshr_cast_i_i_i_i_i_fu_211_p1();
    void thread_p_neg_i_i_i_i_i_fu_195_p2();
    void thread_p_neg_t_i_i_i_i_i_fu_215_p2();
    void thread_real_start();
    void thread_scalar_dstMat_cols_blk_n();
    void thread_scalar_dstMat_cols_read();
    void thread_scalar_dstMat_rows_blk_n();
    void thread_scalar_dstMat_rows_read();
    void thread_srcPtr_V_blk_n_AR();
    void thread_srcPtr_V_blk_n_R();
    void thread_srcPtr_V_offset_blk_n();
    void thread_srcPtr_V_offset_read();
    void thread_start_out();
    void thread_start_write();
    void thread_strm_V_V_i_blk_n();
    void thread_strm_V_V_i_din();
    void thread_strm_V_V_i_write();
    void thread_tmp_13_cast_i_i_i_i_s_fu_187_p1();
    void thread_tmp_14_i_i_i_i_i_fu_236_p2();
    void thread_tmp_1_i_i_i_i_i_fu_171_p2();
    void thread_tmp_6_i_fu_201_p4();
    void thread_tmp_7_fu_190_p2();
    void thread_tmp_fu_175_p1();
    void thread_tmp_i_fu_161_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
