// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Block_Mat_exit45_pro.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Block_Mat_exit45_pro::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Block_Mat_exit45_pro::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> Block_Mat_exit45_pro::ap_ST_fsm_state1 = "1";
const sc_lv<32> Block_Mat_exit45_pro::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Block_Mat_exit45_pro::ap_const_boolean_1 = true;

Block_Mat_exit45_pro::Block_Mat_exit45_pro(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_imgInput_cols_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_cols_out_full_n );

    SC_METHOD(thread_imgInput_cols_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cols );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_imgInput_cols_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_imgInput_rows_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );

    SC_METHOD(thread_imgInput_rows_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_imgInput_rows_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_imgOutput_cols_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgOutput_cols_out_full_n );

    SC_METHOD(thread_imgOutput_cols_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cols );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_imgOutput_cols_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_imgOutput_rows_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgOutput_rows_out_full_n );

    SC_METHOD(thread_imgOutput_rows_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_imgOutput_rows_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_img_inp_V_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_inp_V_out_full_n );

    SC_METHOD(thread_img_inp_V_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_img_inp_V_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_img_out_V_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_img_out_V_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_out_V );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_img_out_V_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_low_threshold_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( low_threshold_out_full_n );

    SC_METHOD(thread_low_threshold_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( low_threshold );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_low_threshold_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imgInput_rows_out_full_n );
    sensitive << ( imgInput_cols_out_full_n );
    sensitive << ( imgOutput_rows_out_full_n );
    sensitive << ( imgOutput_cols_out_full_n );
    sensitive << ( low_threshold_out_full_n );
    sensitive << ( img_inp_V_out_full_n );
    sensitive << ( img_out_V_out_full_n );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Block_Mat_exit45_pro_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, low_threshold, "(port)low_threshold");
    sc_trace(mVcdFile, imgInput_rows_out_din, "(port)imgInput_rows_out_din");
    sc_trace(mVcdFile, imgInput_rows_out_full_n, "(port)imgInput_rows_out_full_n");
    sc_trace(mVcdFile, imgInput_rows_out_write, "(port)imgInput_rows_out_write");
    sc_trace(mVcdFile, imgInput_cols_out_din, "(port)imgInput_cols_out_din");
    sc_trace(mVcdFile, imgInput_cols_out_full_n, "(port)imgInput_cols_out_full_n");
    sc_trace(mVcdFile, imgInput_cols_out_write, "(port)imgInput_cols_out_write");
    sc_trace(mVcdFile, imgOutput_rows_out_din, "(port)imgOutput_rows_out_din");
    sc_trace(mVcdFile, imgOutput_rows_out_full_n, "(port)imgOutput_rows_out_full_n");
    sc_trace(mVcdFile, imgOutput_rows_out_write, "(port)imgOutput_rows_out_write");
    sc_trace(mVcdFile, imgOutput_cols_out_din, "(port)imgOutput_cols_out_din");
    sc_trace(mVcdFile, imgOutput_cols_out_full_n, "(port)imgOutput_cols_out_full_n");
    sc_trace(mVcdFile, imgOutput_cols_out_write, "(port)imgOutput_cols_out_write");
    sc_trace(mVcdFile, low_threshold_out_din, "(port)low_threshold_out_din");
    sc_trace(mVcdFile, low_threshold_out_full_n, "(port)low_threshold_out_full_n");
    sc_trace(mVcdFile, low_threshold_out_write, "(port)low_threshold_out_write");
    sc_trace(mVcdFile, img_inp_V, "(port)img_inp_V");
    sc_trace(mVcdFile, img_out_V, "(port)img_out_V");
    sc_trace(mVcdFile, img_inp_V_out_din, "(port)img_inp_V_out_din");
    sc_trace(mVcdFile, img_inp_V_out_full_n, "(port)img_inp_V_out_full_n");
    sc_trace(mVcdFile, img_inp_V_out_write, "(port)img_inp_V_out_write");
    sc_trace(mVcdFile, img_out_V_out_din, "(port)img_out_V_out_din");
    sc_trace(mVcdFile, img_out_V_out_full_n, "(port)img_out_V_out_full_n");
    sc_trace(mVcdFile, img_out_V_out_write, "(port)img_out_V_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, imgInput_rows_out_blk_n, "imgInput_rows_out_blk_n");
    sc_trace(mVcdFile, imgInput_cols_out_blk_n, "imgInput_cols_out_blk_n");
    sc_trace(mVcdFile, imgOutput_rows_out_blk_n, "imgOutput_rows_out_blk_n");
    sc_trace(mVcdFile, imgOutput_cols_out_blk_n, "imgOutput_cols_out_blk_n");
    sc_trace(mVcdFile, low_threshold_out_blk_n, "low_threshold_out_blk_n");
    sc_trace(mVcdFile, img_inp_V_out_blk_n, "img_inp_V_out_blk_n");
    sc_trace(mVcdFile, img_out_V_out_blk_n, "img_out_V_out_blk_n");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Block_Mat_exit45_pro::~Block_Mat_exit45_pro() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Block_Mat_exit45_pro::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
}

void Block_Mat_exit45_pro::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Block_Mat_exit45_pro::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read()));
}

void Block_Mat_exit45_pro::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Block_Mat_exit45_pro::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_imgInput_cols_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        imgInput_cols_out_blk_n = imgInput_cols_out_full_n.read();
    } else {
        imgInput_cols_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_imgInput_cols_out_din() {
    imgInput_cols_out_din = cols.read();
}

void Block_Mat_exit45_pro::thread_imgInput_cols_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        imgInput_cols_out_write = ap_const_logic_1;
    } else {
        imgInput_cols_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_imgInput_rows_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        imgInput_rows_out_blk_n = imgInput_rows_out_full_n.read();
    } else {
        imgInput_rows_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_imgInput_rows_out_din() {
    imgInput_rows_out_din = rows.read();
}

void Block_Mat_exit45_pro::thread_imgInput_rows_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        imgInput_rows_out_write = ap_const_logic_1;
    } else {
        imgInput_rows_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_imgOutput_cols_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        imgOutput_cols_out_blk_n = imgOutput_cols_out_full_n.read();
    } else {
        imgOutput_cols_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_imgOutput_cols_out_din() {
    imgOutput_cols_out_din = cols.read();
}

void Block_Mat_exit45_pro::thread_imgOutput_cols_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        imgOutput_cols_out_write = ap_const_logic_1;
    } else {
        imgOutput_cols_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_imgOutput_rows_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        imgOutput_rows_out_blk_n = imgOutput_rows_out_full_n.read();
    } else {
        imgOutput_rows_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_imgOutput_rows_out_din() {
    imgOutput_rows_out_din = rows.read();
}

void Block_Mat_exit45_pro::thread_imgOutput_rows_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        imgOutput_rows_out_write = ap_const_logic_1;
    } else {
        imgOutput_rows_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_img_inp_V_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_inp_V_out_blk_n = img_inp_V_out_full_n.read();
    } else {
        img_inp_V_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_img_inp_V_out_din() {
    img_inp_V_out_din = img_inp_V.read();
}

void Block_Mat_exit45_pro::thread_img_inp_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        img_inp_V_out_write = ap_const_logic_1;
    } else {
        img_inp_V_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_img_out_V_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_out_V_out_blk_n = img_out_V_out_full_n.read();
    } else {
        img_out_V_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_img_out_V_out_din() {
    img_out_V_out_din = img_out_V.read();
}

void Block_Mat_exit45_pro::thread_img_out_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        img_out_V_out_write = ap_const_logic_1;
    } else {
        img_out_V_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_low_threshold_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        low_threshold_out_blk_n = low_threshold_out_full_n.read();
    } else {
        low_threshold_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_low_threshold_out_din() {
    low_threshold_out_din = low_threshold.read();
}

void Block_Mat_exit45_pro::thread_low_threshold_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_inp_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, low_threshold_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgInput_cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, imgOutput_cols_out_full_n.read())))) {
        low_threshold_out_write = ap_const_logic_1;
    } else {
        low_threshold_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

