// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hlsStrm2xfMat_HH_
#define _hlsStrm2xfMat_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct hlsStrm2xfMat : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > srcStrm_V_V_dout;
    sc_in< sc_logic > srcStrm_V_V_empty_n;
    sc_out< sc_logic > srcStrm_V_V_read;
    sc_in< sc_lv<32> > dstMat_rows_dout;
    sc_in< sc_logic > dstMat_rows_empty_n;
    sc_out< sc_logic > dstMat_rows_read;
    sc_in< sc_lv<32> > dstMat_cols_dout;
    sc_in< sc_logic > dstMat_cols_empty_n;
    sc_out< sc_logic > dstMat_cols_read;
    sc_out< sc_lv<20> > dstMat_data_V_address0;
    sc_out< sc_logic > dstMat_data_V_ce0;
    sc_out< sc_logic > dstMat_data_V_we0;
    sc_out< sc_lv<8> > dstMat_data_V_d0;


    // Module declarations
    hlsStrm2xfMat(sc_module_name name);
    SC_HAS_PROCESS(hlsStrm2xfMat);

    ~hlsStrm2xfMat();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > srcStrm_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > tmp_5_i_reg_215;
    sc_signal< sc_logic > dstMat_rows_blk_n;
    sc_signal< sc_logic > dstMat_cols_blk_n;
    sc_signal< sc_lv<29> > i_i_reg_96;
    sc_signal< sc_lv<32> > rows_reg_185;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > cols_reg_190;
    sc_signal< sc_lv<32> > tmp_1_i_fu_108_p2;
    sc_signal< sc_lv<32> > tmp_1_i_reg_195;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<29> > tmp_fu_112_p1;
    sc_signal< sc_lv<29> > tmp_reg_200;
    sc_signal< sc_lv<1> > tmp_4_reg_205;
    sc_signal< sc_lv<30> > loop_count_fu_158_p3;
    sc_signal< sc_lv<30> > loop_count_reg_210;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_5_i_fu_169_p2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<29> > i_fu_174_p2;
    sc_signal< sc_lv<29> > i_reg_219;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state4;
    sc_signal< sc_lv<29> > ap_phi_mux_i_i_phi_fu_100_p4;
    sc_signal< sc_lv<64> > tmp_10_i_fu_180_p1;
    sc_signal< sc_lv<32> > tmp_3_fu_127_p2;
    sc_signal< sc_lv<32> > p_neg_i_fu_132_p2;
    sc_signal< sc_lv<29> > tmp_2_fu_138_p4;
    sc_signal< sc_lv<30> > p_lshr_cast_i_fu_148_p1;
    sc_signal< sc_lv<30> > p_neg_t_i_fu_152_p2;
    sc_signal< sc_lv<30> > tmp_7_cast_i_fu_124_p1;
    sc_signal< sc_lv<30> > i_cast_i_fu_165_p1;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_pp0_stage0;
    static const sc_lv<5> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<29> ap_const_lv29_0;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<30> ap_const_lv30_0;
    static const sc_lv<29> ap_const_lv29_1;
    static const sc_lv<32> ap_const_lv32_4;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state4_pp0_stage0_iter0();
    void thread_ap_block_state5_pp0_stage0_iter1();
    void thread_ap_condition_pp0_exit_iter0_state4();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_i_i_phi_fu_100_p4();
    void thread_ap_ready();
    void thread_dstMat_cols_blk_n();
    void thread_dstMat_cols_read();
    void thread_dstMat_data_V_address0();
    void thread_dstMat_data_V_ce0();
    void thread_dstMat_data_V_d0();
    void thread_dstMat_data_V_we0();
    void thread_dstMat_rows_blk_n();
    void thread_dstMat_rows_read();
    void thread_i_cast_i_fu_165_p1();
    void thread_i_fu_174_p2();
    void thread_loop_count_fu_158_p3();
    void thread_p_lshr_cast_i_fu_148_p1();
    void thread_p_neg_i_fu_132_p2();
    void thread_p_neg_t_i_fu_152_p2();
    void thread_srcStrm_V_V_blk_n();
    void thread_srcStrm_V_V_read();
    void thread_tmp_10_i_fu_180_p1();
    void thread_tmp_1_i_fu_108_p2();
    void thread_tmp_2_fu_138_p4();
    void thread_tmp_3_fu_127_p2();
    void thread_tmp_5_i_fu_169_p2();
    void thread_tmp_7_cast_i_fu_124_p1();
    void thread_tmp_fu_112_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
