// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hlsStrm2xfMat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hlsStrm2xfMat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic hlsStrm2xfMat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> hlsStrm2xfMat::ap_ST_fsm_state1 = "1";
const sc_lv<5> hlsStrm2xfMat::ap_ST_fsm_state2 = "10";
const sc_lv<5> hlsStrm2xfMat::ap_ST_fsm_state3 = "100";
const sc_lv<5> hlsStrm2xfMat::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<5> hlsStrm2xfMat::ap_ST_fsm_state6 = "10000";
const sc_lv<32> hlsStrm2xfMat::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool hlsStrm2xfMat::ap_const_boolean_1 = true;
const sc_lv<32> hlsStrm2xfMat::ap_const_lv32_3 = "11";
const bool hlsStrm2xfMat::ap_const_boolean_0 = false;
const sc_lv<1> hlsStrm2xfMat::ap_const_lv1_1 = "1";
const sc_lv<32> hlsStrm2xfMat::ap_const_lv32_1 = "1";
const sc_lv<32> hlsStrm2xfMat::ap_const_lv32_2 = "10";
const sc_lv<1> hlsStrm2xfMat::ap_const_lv1_0 = "0";
const sc_lv<29> hlsStrm2xfMat::ap_const_lv29_0 = "00000000000000000000000000000";
const sc_lv<32> hlsStrm2xfMat::ap_const_lv32_1C = "11100";
const sc_lv<32> hlsStrm2xfMat::ap_const_lv32_1F = "11111";
const sc_lv<30> hlsStrm2xfMat::ap_const_lv30_0 = "000000000000000000000000000000";
const sc_lv<29> hlsStrm2xfMat::ap_const_lv29_1 = "1";
const sc_lv<32> hlsStrm2xfMat::ap_const_lv32_4 = "100";

hlsStrm2xfMat::hlsStrm2xfMat(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( srcStrm_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_5_i_reg_215 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( srcStrm_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_5_i_reg_215 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( dstMat_rows_empty_n );
    sensitive << ( dstMat_cols_empty_n );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);
    sensitive << ( srcStrm_V_V_empty_n );
    sensitive << ( tmp_5_i_reg_215 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( tmp_5_i_fu_169_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_phi_mux_i_i_phi_fu_100_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_5_i_reg_215 );
    sensitive << ( i_i_reg_96 );
    sensitive << ( i_reg_219 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_dstMat_cols_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( dstMat_cols_empty_n );

    SC_METHOD(thread_dstMat_cols_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( dstMat_rows_empty_n );
    sensitive << ( dstMat_cols_empty_n );

    SC_METHOD(thread_dstMat_data_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_10_i_fu_180_p1 );

    SC_METHOD(thread_dstMat_data_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_dstMat_data_V_d0);
    sensitive << ( srcStrm_V_V_dout );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_dstMat_data_V_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_5_i_reg_215 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_dstMat_rows_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( dstMat_rows_empty_n );

    SC_METHOD(thread_dstMat_rows_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( dstMat_rows_empty_n );
    sensitive << ( dstMat_cols_empty_n );

    SC_METHOD(thread_i_cast_i_fu_165_p1);
    sensitive << ( ap_phi_mux_i_i_phi_fu_100_p4 );

    SC_METHOD(thread_i_fu_174_p2);
    sensitive << ( ap_phi_mux_i_i_phi_fu_100_p4 );

    SC_METHOD(thread_loop_count_fu_158_p3);
    sensitive << ( tmp_4_reg_205 );
    sensitive << ( p_neg_t_i_fu_152_p2 );
    sensitive << ( tmp_7_cast_i_fu_124_p1 );

    SC_METHOD(thread_p_lshr_cast_i_fu_148_p1);
    sensitive << ( tmp_2_fu_138_p4 );

    SC_METHOD(thread_p_neg_i_fu_132_p2);
    sensitive << ( tmp_3_fu_127_p2 );

    SC_METHOD(thread_p_neg_t_i_fu_152_p2);
    sensitive << ( p_lshr_cast_i_fu_148_p1 );

    SC_METHOD(thread_srcStrm_V_V_blk_n);
    sensitive << ( srcStrm_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_5_i_reg_215 );

    SC_METHOD(thread_srcStrm_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_5_i_reg_215 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_10_i_fu_180_p1);
    sensitive << ( i_i_reg_96 );

    SC_METHOD(thread_tmp_1_i_fu_108_p2);
    sensitive << ( rows_reg_185 );
    sensitive << ( cols_reg_190 );

    SC_METHOD(thread_tmp_2_fu_138_p4);
    sensitive << ( p_neg_i_fu_132_p2 );

    SC_METHOD(thread_tmp_3_fu_127_p2);
    sensitive << ( tmp_1_i_reg_195 );

    SC_METHOD(thread_tmp_5_i_fu_169_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( loop_count_reg_210 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( i_cast_i_fu_165_p1 );

    SC_METHOD(thread_tmp_7_cast_i_fu_124_p1);
    sensitive << ( tmp_reg_200 );

    SC_METHOD(thread_tmp_fu_112_p1);
    sensitive << ( tmp_1_i_fu_108_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( dstMat_rows_empty_n );
    sensitive << ( dstMat_cols_empty_n );
    sensitive << ( tmp_5_i_fu_169_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hlsStrm2xfMat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, srcStrm_V_V_dout, "(port)srcStrm_V_V_dout");
    sc_trace(mVcdFile, srcStrm_V_V_empty_n, "(port)srcStrm_V_V_empty_n");
    sc_trace(mVcdFile, srcStrm_V_V_read, "(port)srcStrm_V_V_read");
    sc_trace(mVcdFile, dstMat_rows_dout, "(port)dstMat_rows_dout");
    sc_trace(mVcdFile, dstMat_rows_empty_n, "(port)dstMat_rows_empty_n");
    sc_trace(mVcdFile, dstMat_rows_read, "(port)dstMat_rows_read");
    sc_trace(mVcdFile, dstMat_cols_dout, "(port)dstMat_cols_dout");
    sc_trace(mVcdFile, dstMat_cols_empty_n, "(port)dstMat_cols_empty_n");
    sc_trace(mVcdFile, dstMat_cols_read, "(port)dstMat_cols_read");
    sc_trace(mVcdFile, dstMat_data_V_address0, "(port)dstMat_data_V_address0");
    sc_trace(mVcdFile, dstMat_data_V_ce0, "(port)dstMat_data_V_ce0");
    sc_trace(mVcdFile, dstMat_data_V_we0, "(port)dstMat_data_V_we0");
    sc_trace(mVcdFile, dstMat_data_V_d0, "(port)dstMat_data_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, srcStrm_V_V_blk_n, "srcStrm_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_5_i_reg_215, "tmp_5_i_reg_215");
    sc_trace(mVcdFile, dstMat_rows_blk_n, "dstMat_rows_blk_n");
    sc_trace(mVcdFile, dstMat_cols_blk_n, "dstMat_cols_blk_n");
    sc_trace(mVcdFile, i_i_reg_96, "i_i_reg_96");
    sc_trace(mVcdFile, rows_reg_185, "rows_reg_185");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, cols_reg_190, "cols_reg_190");
    sc_trace(mVcdFile, tmp_1_i_fu_108_p2, "tmp_1_i_fu_108_p2");
    sc_trace(mVcdFile, tmp_1_i_reg_195, "tmp_1_i_reg_195");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_112_p1, "tmp_fu_112_p1");
    sc_trace(mVcdFile, tmp_reg_200, "tmp_reg_200");
    sc_trace(mVcdFile, tmp_4_reg_205, "tmp_4_reg_205");
    sc_trace(mVcdFile, loop_count_fu_158_p3, "loop_count_fu_158_p3");
    sc_trace(mVcdFile, loop_count_reg_210, "loop_count_reg_210");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_5_i_fu_169_p2, "tmp_5_i_fu_169_p2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_174_p2, "i_fu_174_p2");
    sc_trace(mVcdFile, i_reg_219, "i_reg_219");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, ap_phi_mux_i_i_phi_fu_100_p4, "ap_phi_mux_i_i_phi_fu_100_p4");
    sc_trace(mVcdFile, tmp_10_i_fu_180_p1, "tmp_10_i_fu_180_p1");
    sc_trace(mVcdFile, tmp_3_fu_127_p2, "tmp_3_fu_127_p2");
    sc_trace(mVcdFile, p_neg_i_fu_132_p2, "p_neg_i_fu_132_p2");
    sc_trace(mVcdFile, tmp_2_fu_138_p4, "tmp_2_fu_138_p4");
    sc_trace(mVcdFile, p_lshr_cast_i_fu_148_p1, "p_lshr_cast_i_fu_148_p1");
    sc_trace(mVcdFile, p_neg_t_i_fu_152_p2, "p_neg_t_i_fu_152_p2");
    sc_trace(mVcdFile, tmp_7_cast_i_fu_124_p1, "tmp_7_cast_i_fu_124_p1");
    sc_trace(mVcdFile, i_cast_i_fu_165_p1, "i_cast_i_fu_165_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

hlsStrm2xfMat::~hlsStrm2xfMat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void hlsStrm2xfMat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state4.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_5_i_reg_215.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_i_reg_96 = i_reg_219.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_i_reg_96 = ap_const_lv29_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_cols_empty_n.read())))) {
        cols_reg_190 = dstMat_cols_dout.read();
        rows_reg_185 = dstMat_rows_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        i_reg_219 = i_fu_174_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        loop_count_reg_210 = loop_count_fu_158_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        tmp_1_i_reg_195 = tmp_1_i_fu_108_p2.read();
        tmp_4_reg_205 = tmp_1_i_fu_108_p2.read().range(28, 28);
        tmp_reg_200 = tmp_fu_112_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_5_i_reg_215 = tmp_5_i_fu_169_p2.read();
    }
}

void hlsStrm2xfMat::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void hlsStrm2xfMat::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void hlsStrm2xfMat::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void hlsStrm2xfMat::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void hlsStrm2xfMat::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void hlsStrm2xfMat::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hlsStrm2xfMat::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_5_i_reg_215.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, srcStrm_V_V_empty_n.read()));
}

void hlsStrm2xfMat::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_5_i_reg_215.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, srcStrm_V_V_empty_n.read()));
}

void hlsStrm2xfMat::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_cols_empty_n.read()));
}

void hlsStrm2xfMat::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hlsStrm2xfMat::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = (esl_seteq<1,1,1>(tmp_5_i_reg_215.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, srcStrm_V_V_empty_n.read()));
}

void hlsStrm2xfMat::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(tmp_5_i_fu_169_p2.read(), ap_const_lv1_0)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void hlsStrm2xfMat::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void hlsStrm2xfMat::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_ap_phi_mux_i_i_phi_fu_100_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_5_i_reg_215.read(), ap_const_lv1_1))) {
        ap_phi_mux_i_i_phi_fu_100_p4 = i_reg_219.read();
    } else {
        ap_phi_mux_i_i_phi_fu_100_p4 = i_i_reg_96.read();
    }
}

void hlsStrm2xfMat::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_dstMat_cols_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        dstMat_cols_blk_n = dstMat_cols_empty_n.read();
    } else {
        dstMat_cols_blk_n = ap_const_logic_1;
    }
}

void hlsStrm2xfMat::thread_dstMat_cols_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_cols_empty_n.read())))) {
        dstMat_cols_read = ap_const_logic_1;
    } else {
        dstMat_cols_read = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_dstMat_data_V_address0() {
    dstMat_data_V_address0 =  (sc_lv<20>) (tmp_10_i_fu_180_p1.read());
}

void hlsStrm2xfMat::thread_dstMat_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        dstMat_data_V_ce0 = ap_const_logic_1;
    } else {
        dstMat_data_V_ce0 = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_dstMat_data_V_d0() {
    dstMat_data_V_d0 = srcStrm_V_V_dout.read();
}

void hlsStrm2xfMat::thread_dstMat_data_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_5_i_reg_215.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        dstMat_data_V_we0 = ap_const_logic_1;
    } else {
        dstMat_data_V_we0 = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_dstMat_rows_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        dstMat_rows_blk_n = dstMat_rows_empty_n.read();
    } else {
        dstMat_rows_blk_n = ap_const_logic_1;
    }
}

void hlsStrm2xfMat::thread_dstMat_rows_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_cols_empty_n.read())))) {
        dstMat_rows_read = ap_const_logic_1;
    } else {
        dstMat_rows_read = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_i_cast_i_fu_165_p1() {
    i_cast_i_fu_165_p1 = esl_zext<30,29>(ap_phi_mux_i_i_phi_fu_100_p4.read());
}

void hlsStrm2xfMat::thread_i_fu_174_p2() {
    i_fu_174_p2 = (!ap_phi_mux_i_i_phi_fu_100_p4.read().is_01() || !ap_const_lv29_1.is_01())? sc_lv<29>(): (sc_biguint<29>(ap_phi_mux_i_i_phi_fu_100_p4.read()) + sc_biguint<29>(ap_const_lv29_1));
}

void hlsStrm2xfMat::thread_loop_count_fu_158_p3() {
    loop_count_fu_158_p3 = (!tmp_4_reg_205.read()[0].is_01())? sc_lv<30>(): ((tmp_4_reg_205.read()[0].to_bool())? p_neg_t_i_fu_152_p2.read(): tmp_7_cast_i_fu_124_p1.read());
}

void hlsStrm2xfMat::thread_p_lshr_cast_i_fu_148_p1() {
    p_lshr_cast_i_fu_148_p1 = esl_zext<30,29>(tmp_2_fu_138_p4.read());
}

void hlsStrm2xfMat::thread_p_neg_i_fu_132_p2() {
    p_neg_i_fu_132_p2 = (!ap_const_lv32_0.is_01() || !tmp_3_fu_127_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_3_fu_127_p2.read()));
}

void hlsStrm2xfMat::thread_p_neg_t_i_fu_152_p2() {
    p_neg_t_i_fu_152_p2 = (!ap_const_lv30_0.is_01() || !p_lshr_cast_i_fu_148_p1.read().is_01())? sc_lv<30>(): (sc_biguint<30>(ap_const_lv30_0) - sc_biguint<30>(p_lshr_cast_i_fu_148_p1.read()));
}

void hlsStrm2xfMat::thread_srcStrm_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_5_i_reg_215.read(), ap_const_lv1_1))) {
        srcStrm_V_V_blk_n = srcStrm_V_V_empty_n.read();
    } else {
        srcStrm_V_V_blk_n = ap_const_logic_1;
    }
}

void hlsStrm2xfMat::thread_srcStrm_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_5_i_reg_215.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        srcStrm_V_V_read = ap_const_logic_1;
    } else {
        srcStrm_V_V_read = ap_const_logic_0;
    }
}

void hlsStrm2xfMat::thread_tmp_10_i_fu_180_p1() {
    tmp_10_i_fu_180_p1 = esl_zext<64,29>(i_i_reg_96.read());
}

void hlsStrm2xfMat::thread_tmp_1_i_fu_108_p2() {
    tmp_1_i_fu_108_p2 = (!rows_reg_185.read().is_01() || !cols_reg_190.read().is_01())? sc_lv<32>(): sc_bigint<32>(rows_reg_185.read()) * sc_bigint<32>(cols_reg_190.read());
}

void hlsStrm2xfMat::thread_tmp_2_fu_138_p4() {
    tmp_2_fu_138_p4 = p_neg_i_fu_132_p2.read().range(31, 3);
}

void hlsStrm2xfMat::thread_tmp_3_fu_127_p2() {
    tmp_3_fu_127_p2 = (!ap_const_lv32_3.is_01())? sc_lv<32>(): tmp_1_i_reg_195.read() << (unsigned short)ap_const_lv32_3.to_uint();
}

void hlsStrm2xfMat::thread_tmp_5_i_fu_169_p2() {
    tmp_5_i_fu_169_p2 = (!i_cast_i_fu_165_p1.read().is_01() || !loop_count_reg_210.read().is_01())? sc_lv<1>(): (sc_bigint<30>(i_cast_i_fu_165_p1.read()) < sc_bigint<30>(loop_count_reg_210.read()));
}

void hlsStrm2xfMat::thread_tmp_7_cast_i_fu_124_p1() {
    tmp_7_cast_i_fu_124_p1 = esl_zext<30,29>(tmp_reg_200.read());
}

void hlsStrm2xfMat::thread_tmp_fu_112_p1() {
    tmp_fu_112_p1 = tmp_1_i_fu_108_p2.read().range(29-1, 0);
}

void hlsStrm2xfMat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_rows_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dstMat_cols_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_5_i_fu_169_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_5_i_fu_169_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

}

