-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xfMat2hlsStrm9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    srcMat_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    srcMat_rows_empty_n : IN STD_LOGIC;
    srcMat_rows_read : OUT STD_LOGIC;
    srcMat_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    srcMat_cols_empty_n : IN STD_LOGIC;
    srcMat_cols_read : OUT STD_LOGIC;
    srcMat_data_V_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    srcMat_data_V_ce0 : OUT STD_LOGIC;
    srcMat_data_V_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    dstStrm_V_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dstStrm_V_V_full_n : IN STD_LOGIC;
    dstStrm_V_V_write : OUT STD_LOGIC;
    srcMat_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    srcMat_rows_out_full_n : IN STD_LOGIC;
    srcMat_rows_out_write : OUT STD_LOGIC;
    srcMat_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    srcMat_cols_out_full_n : IN STD_LOGIC;
    srcMat_cols_out_write : OUT STD_LOGIC;
    dstPtr_V_offset_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    dstPtr_V_offset_empty_n : IN STD_LOGIC;
    dstPtr_V_offset_read : OUT STD_LOGIC;
    dstPtr_V_offset_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dstPtr_V_offset_out_full_n : IN STD_LOGIC;
    dstPtr_V_offset_out_write : OUT STD_LOGIC );
end;


architecture behav of xfMat2hlsStrm9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv30_1 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000001";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal srcMat_rows_blk_n : STD_LOGIC;
    signal srcMat_cols_blk_n : STD_LOGIC;
    signal dstStrm_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_3_i_i_i_i_reg_282 : STD_LOGIC_VECTOR (0 downto 0);
    signal srcMat_rows_out_blk_n : STD_LOGIC;
    signal srcMat_cols_out_blk_n : STD_LOGIC;
    signal dstPtr_V_offset_blk_n : STD_LOGIC;
    signal dstPtr_V_offset_out_blk_n : STD_LOGIC;
    signal indvars_iv_i_i_i_i_reg_138 : STD_LOGIC_VECTOR (29 downto 0);
    signal idx_out_i_i_i_i_reg_150 : STD_LOGIC_VECTOR (29 downto 0);
    signal rows_reg_252 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal cols_reg_257 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_i_i_i_fu_162_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_i_i_i_reg_262 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_166_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_reg_267 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_2_reg_272 : STD_LOGIC_VECTOR (0 downto 0);
    signal loop_count_cast_i_i_s_fu_219_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal loop_count_cast_i_i_s_reg_277 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_3_i_i_i_i_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal indvars_iv_next_i_i_s_fu_237_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal indvars_iv_next_i_i_s_reg_291 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state4 : STD_LOGIC;
    signal ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_6_i_i_i_i_fu_232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_1_fu_181_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_neg_i_i_i_i_fu_186_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_i_i_i_fu_192_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_lshr_cast_i_i_i_i_fu_202_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_neg_t_i_i_i_i_fu_206_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_4_cast_i_i_i_i_fu_178_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal loop_count_fu_212_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal idx_out_cast_i_i_i_i_fu_223_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state4);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    idx_out_i_i_i_i_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                idx_out_i_i_i_i_reg_150 <= ap_const_lv30_0;
            elsif (((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                idx_out_i_i_i_i_reg_150 <= indvars_iv_i_i_i_i_reg_138;
            end if; 
        end if;
    end process;

    indvars_iv_i_i_i_i_reg_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                indvars_iv_i_i_i_i_reg_138 <= ap_const_lv30_1;
            elsif (((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvars_iv_i_i_i_i_reg_138 <= indvars_iv_next_i_i_s_reg_291;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cols_reg_257 <= srcMat_cols_dout;
                rows_reg_252 <= srcMat_rows_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_3_i_i_i_i_fu_227_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                indvars_iv_next_i_i_s_reg_291 <= indvars_iv_next_i_i_s_fu_237_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                loop_count_cast_i_i_s_reg_277 <= loop_count_cast_i_i_s_fu_219_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_2_reg_272 <= tmp_i_i_i_i_fu_162_p2(28 downto 28);
                tmp_i_i_i_i_reg_262 <= tmp_i_i_i_i_fu_162_p2;
                tmp_reg_267 <= tmp_fu_166_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_3_i_i_i_i_reg_282 <= tmp_3_i_i_i_i_fu_227_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, srcMat_rows_empty_n, srcMat_cols_empty_n, srcMat_rows_out_full_n, srcMat_cols_out_full_n, dstPtr_V_offset_empty_n, dstPtr_V_offset_out_full_n, tmp_3_i_i_i_i_fu_227_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (tmp_3_i_i_i_i_fu_227_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (tmp_3_i_i_i_i_fu_227_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(dstStrm_V_V_full_n, ap_enable_reg_pp0_iter1, tmp_3_i_i_i_i_reg_282)
    begin
                ap_block_pp0_stage0_01001 <= ((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (dstStrm_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(dstStrm_V_V_full_n, ap_enable_reg_pp0_iter1, tmp_3_i_i_i_i_reg_282)
    begin
                ap_block_pp0_stage0_11001 <= ((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (dstStrm_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(dstStrm_V_V_full_n, ap_enable_reg_pp0_iter1, tmp_3_i_i_i_i_reg_282)
    begin
                ap_block_pp0_stage0_subdone <= ((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (dstStrm_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, srcMat_rows_empty_n, srcMat_cols_empty_n, srcMat_rows_out_full_n, srcMat_cols_out_full_n, dstPtr_V_offset_empty_n, dstPtr_V_offset_out_full_n)
    begin
                ap_block_state1 <= ((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter1_assign_proc : process(dstStrm_V_V_full_n, tmp_3_i_i_i_i_reg_282)
    begin
                ap_block_state5_pp0_stage0_iter1 <= ((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (dstStrm_V_V_full_n = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state4_assign_proc : process(tmp_3_i_i_i_i_fu_227_p2)
    begin
        if ((tmp_3_i_i_i_i_fu_227_p2 = ap_const_lv1_0)) then 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_3_i_i_i_i_reg_282, indvars_iv_i_i_i_i_reg_138, idx_out_i_i_i_i_reg_150)
    begin
        if (((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4 <= indvars_iv_i_i_i_i_reg_138;
        else 
            ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4 <= idx_out_i_i_i_i_reg_150;
        end if; 
    end process;


    ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_3_i_i_i_i_reg_282, indvars_iv_i_i_i_i_reg_138, indvars_iv_next_i_i_s_reg_291)
    begin
        if (((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4 <= indvars_iv_next_i_i_s_reg_291;
        else 
            ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4 <= indvars_iv_i_i_i_i_reg_138;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    dstPtr_V_offset_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstPtr_V_offset_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstPtr_V_offset_blk_n <= dstPtr_V_offset_empty_n;
        else 
            dstPtr_V_offset_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dstPtr_V_offset_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, dstPtr_V_offset_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstPtr_V_offset_out_blk_n <= dstPtr_V_offset_out_full_n;
        else 
            dstPtr_V_offset_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstPtr_V_offset_out_din <= dstPtr_V_offset_dout;

    dstPtr_V_offset_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_empty_n, srcMat_cols_empty_n, srcMat_rows_out_full_n, srcMat_cols_out_full_n, dstPtr_V_offset_empty_n, dstPtr_V_offset_out_full_n)
    begin
        if ((not(((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstPtr_V_offset_out_write <= ap_const_logic_1;
        else 
            dstPtr_V_offset_out_write <= ap_const_logic_0;
        end if; 
    end process;


    dstPtr_V_offset_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_empty_n, srcMat_cols_empty_n, srcMat_rows_out_full_n, srcMat_cols_out_full_n, dstPtr_V_offset_empty_n, dstPtr_V_offset_out_full_n)
    begin
        if ((not(((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstPtr_V_offset_read <= ap_const_logic_1;
        else 
            dstPtr_V_offset_read <= ap_const_logic_0;
        end if; 
    end process;


    dstStrm_V_V_blk_n_assign_proc : process(dstStrm_V_V_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, tmp_3_i_i_i_i_reg_282)
    begin
        if (((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dstStrm_V_V_blk_n <= dstStrm_V_V_full_n;
        else 
            dstStrm_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dstStrm_V_V_din <= 
        ap_const_lv8_FF when (srcMat_data_V_q0(0) = '1') else 
        ap_const_lv8_0;

    dstStrm_V_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_3_i_i_i_i_reg_282, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_3_i_i_i_i_reg_282 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dstStrm_V_V_write <= ap_const_logic_1;
        else 
            dstStrm_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    idx_out_cast_i_i_i_i_fu_223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4),31));
    indvars_iv_next_i_i_s_fu_237_p2 <= std_logic_vector(unsigned(ap_const_lv30_1) + unsigned(ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4));

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        loop_count_cast_i_i_s_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(loop_count_fu_212_p3),31));

    loop_count_fu_212_p3 <= 
        p_neg_t_i_i_i_i_fu_206_p2 when (tmp_2_reg_272(0) = '1') else 
        tmp_4_cast_i_i_i_i_fu_178_p1;
    p_lshr_cast_i_i_i_i_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_i_i_i_fu_192_p4),30));
    p_neg_i_i_i_i_fu_186_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(tmp_1_fu_181_p2));
    p_neg_t_i_i_i_i_fu_206_p2 <= std_logic_vector(unsigned(ap_const_lv30_0) - unsigned(p_lshr_cast_i_i_i_i_fu_202_p1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    srcMat_cols_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_cols_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_cols_blk_n <= srcMat_cols_empty_n;
        else 
            srcMat_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    srcMat_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_cols_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_cols_out_blk_n <= srcMat_cols_out_full_n;
        else 
            srcMat_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    srcMat_cols_out_din <= srcMat_cols_dout;

    srcMat_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_empty_n, srcMat_cols_empty_n, srcMat_rows_out_full_n, srcMat_cols_out_full_n, dstPtr_V_offset_empty_n, dstPtr_V_offset_out_full_n)
    begin
        if ((not(((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_cols_out_write <= ap_const_logic_1;
        else 
            srcMat_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    srcMat_cols_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_empty_n, srcMat_cols_empty_n, srcMat_rows_out_full_n, srcMat_cols_out_full_n, dstPtr_V_offset_empty_n, dstPtr_V_offset_out_full_n)
    begin
        if ((not(((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_cols_read <= ap_const_logic_1;
        else 
            srcMat_cols_read <= ap_const_logic_0;
        end if; 
    end process;

    srcMat_data_V_address0 <= tmp_6_i_i_i_i_fu_232_p1(20 - 1 downto 0);

    srcMat_data_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            srcMat_data_V_ce0 <= ap_const_logic_1;
        else 
            srcMat_data_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    srcMat_rows_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_rows_blk_n <= srcMat_rows_empty_n;
        else 
            srcMat_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    srcMat_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_rows_out_blk_n <= srcMat_rows_out_full_n;
        else 
            srcMat_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    srcMat_rows_out_din <= srcMat_rows_dout;

    srcMat_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_empty_n, srcMat_cols_empty_n, srcMat_rows_out_full_n, srcMat_cols_out_full_n, dstPtr_V_offset_empty_n, dstPtr_V_offset_out_full_n)
    begin
        if ((not(((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_rows_out_write <= ap_const_logic_1;
        else 
            srcMat_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    srcMat_rows_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, srcMat_rows_empty_n, srcMat_cols_empty_n, srcMat_rows_out_full_n, srcMat_cols_out_full_n, dstPtr_V_offset_empty_n, dstPtr_V_offset_out_full_n)
    begin
        if ((not(((dstPtr_V_offset_out_full_n = ap_const_logic_0) or (dstPtr_V_offset_empty_n = ap_const_logic_0) or (srcMat_cols_out_full_n = ap_const_logic_0) or (srcMat_rows_out_full_n = ap_const_logic_0) or (srcMat_cols_empty_n = ap_const_logic_0) or (srcMat_rows_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            srcMat_rows_read <= ap_const_logic_1;
        else 
            srcMat_rows_read <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_181_p2 <= std_logic_vector(shift_left(unsigned(tmp_i_i_i_i_reg_262),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    tmp_1_i_i_i_fu_192_p4 <= p_neg_i_i_i_i_fu_186_p2(31 downto 3);
    tmp_3_i_i_i_i_fu_227_p2 <= "1" when (signed(idx_out_cast_i_i_i_i_fu_223_p1) < signed(loop_count_cast_i_i_s_reg_277)) else "0";
    tmp_4_cast_i_i_i_i_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_267),30));
    tmp_6_i_i_i_i_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4),64));
    tmp_fu_166_p1 <= tmp_i_i_i_i_fu_162_p2(29 - 1 downto 0);
    tmp_i_i_i_i_fu_162_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(rows_reg_252) * signed(cols_reg_257))), 32));
end behav;
