// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Array2hlsStrm54 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        scalar_dstMat_cols_dout,
        scalar_dstMat_cols_empty_n,
        scalar_dstMat_cols_read,
        dstMat_cols_out_din,
        dstMat_cols_out_full_n,
        dstMat_cols_out_write,
        scalar_dstMat_rows_dout,
        scalar_dstMat_rows_empty_n,
        scalar_dstMat_rows_read,
        dstMat_rows_out_din,
        dstMat_rows_out_full_n,
        dstMat_rows_out_write,
        m_axi_srcPtr_V_AWVALID,
        m_axi_srcPtr_V_AWREADY,
        m_axi_srcPtr_V_AWADDR,
        m_axi_srcPtr_V_AWID,
        m_axi_srcPtr_V_AWLEN,
        m_axi_srcPtr_V_AWSIZE,
        m_axi_srcPtr_V_AWBURST,
        m_axi_srcPtr_V_AWLOCK,
        m_axi_srcPtr_V_AWCACHE,
        m_axi_srcPtr_V_AWPROT,
        m_axi_srcPtr_V_AWQOS,
        m_axi_srcPtr_V_AWREGION,
        m_axi_srcPtr_V_AWUSER,
        m_axi_srcPtr_V_WVALID,
        m_axi_srcPtr_V_WREADY,
        m_axi_srcPtr_V_WDATA,
        m_axi_srcPtr_V_WSTRB,
        m_axi_srcPtr_V_WLAST,
        m_axi_srcPtr_V_WID,
        m_axi_srcPtr_V_WUSER,
        m_axi_srcPtr_V_ARVALID,
        m_axi_srcPtr_V_ARREADY,
        m_axi_srcPtr_V_ARADDR,
        m_axi_srcPtr_V_ARID,
        m_axi_srcPtr_V_ARLEN,
        m_axi_srcPtr_V_ARSIZE,
        m_axi_srcPtr_V_ARBURST,
        m_axi_srcPtr_V_ARLOCK,
        m_axi_srcPtr_V_ARCACHE,
        m_axi_srcPtr_V_ARPROT,
        m_axi_srcPtr_V_ARQOS,
        m_axi_srcPtr_V_ARREGION,
        m_axi_srcPtr_V_ARUSER,
        m_axi_srcPtr_V_RVALID,
        m_axi_srcPtr_V_RREADY,
        m_axi_srcPtr_V_RDATA,
        m_axi_srcPtr_V_RLAST,
        m_axi_srcPtr_V_RID,
        m_axi_srcPtr_V_RUSER,
        m_axi_srcPtr_V_RRESP,
        m_axi_srcPtr_V_BVALID,
        m_axi_srcPtr_V_BREADY,
        m_axi_srcPtr_V_BRESP,
        m_axi_srcPtr_V_BID,
        m_axi_srcPtr_V_BUSER,
        srcPtr_V_offset_dout,
        srcPtr_V_offset_empty_n,
        srcPtr_V_offset_read,
        strm_V_V_i_din,
        strm_V_V_i_full_n,
        strm_V_V_i_write,
        dstMat_rows_c_i_din,
        dstMat_rows_c_i_full_n,
        dstMat_rows_c_i_write,
        dstMat_cols_c_i_din,
        dstMat_cols_c_i_full_n,
        dstMat_cols_c_i_write
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_pp0_stage0 = 12'd1024;
parameter    ap_ST_fsm_state14 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] scalar_dstMat_cols_dout;
input   scalar_dstMat_cols_empty_n;
output   scalar_dstMat_cols_read;
output  [31:0] dstMat_cols_out_din;
input   dstMat_cols_out_full_n;
output   dstMat_cols_out_write;
input  [31:0] scalar_dstMat_rows_dout;
input   scalar_dstMat_rows_empty_n;
output   scalar_dstMat_rows_read;
output  [31:0] dstMat_rows_out_din;
input   dstMat_rows_out_full_n;
output   dstMat_rows_out_write;
output   m_axi_srcPtr_V_AWVALID;
input   m_axi_srcPtr_V_AWREADY;
output  [31:0] m_axi_srcPtr_V_AWADDR;
output  [0:0] m_axi_srcPtr_V_AWID;
output  [31:0] m_axi_srcPtr_V_AWLEN;
output  [2:0] m_axi_srcPtr_V_AWSIZE;
output  [1:0] m_axi_srcPtr_V_AWBURST;
output  [1:0] m_axi_srcPtr_V_AWLOCK;
output  [3:0] m_axi_srcPtr_V_AWCACHE;
output  [2:0] m_axi_srcPtr_V_AWPROT;
output  [3:0] m_axi_srcPtr_V_AWQOS;
output  [3:0] m_axi_srcPtr_V_AWREGION;
output  [0:0] m_axi_srcPtr_V_AWUSER;
output   m_axi_srcPtr_V_WVALID;
input   m_axi_srcPtr_V_WREADY;
output  [7:0] m_axi_srcPtr_V_WDATA;
output  [0:0] m_axi_srcPtr_V_WSTRB;
output   m_axi_srcPtr_V_WLAST;
output  [0:0] m_axi_srcPtr_V_WID;
output  [0:0] m_axi_srcPtr_V_WUSER;
output   m_axi_srcPtr_V_ARVALID;
input   m_axi_srcPtr_V_ARREADY;
output  [31:0] m_axi_srcPtr_V_ARADDR;
output  [0:0] m_axi_srcPtr_V_ARID;
output  [31:0] m_axi_srcPtr_V_ARLEN;
output  [2:0] m_axi_srcPtr_V_ARSIZE;
output  [1:0] m_axi_srcPtr_V_ARBURST;
output  [1:0] m_axi_srcPtr_V_ARLOCK;
output  [3:0] m_axi_srcPtr_V_ARCACHE;
output  [2:0] m_axi_srcPtr_V_ARPROT;
output  [3:0] m_axi_srcPtr_V_ARQOS;
output  [3:0] m_axi_srcPtr_V_ARREGION;
output  [0:0] m_axi_srcPtr_V_ARUSER;
input   m_axi_srcPtr_V_RVALID;
output   m_axi_srcPtr_V_RREADY;
input  [7:0] m_axi_srcPtr_V_RDATA;
input   m_axi_srcPtr_V_RLAST;
input  [0:0] m_axi_srcPtr_V_RID;
input  [0:0] m_axi_srcPtr_V_RUSER;
input  [1:0] m_axi_srcPtr_V_RRESP;
input   m_axi_srcPtr_V_BVALID;
output   m_axi_srcPtr_V_BREADY;
input  [1:0] m_axi_srcPtr_V_BRESP;
input  [0:0] m_axi_srcPtr_V_BID;
input  [0:0] m_axi_srcPtr_V_BUSER;
input  [31:0] srcPtr_V_offset_dout;
input   srcPtr_V_offset_empty_n;
output   srcPtr_V_offset_read;
output  [7:0] strm_V_V_i_din;
input   strm_V_V_i_full_n;
output   strm_V_V_i_write;
output  [31:0] dstMat_rows_c_i_din;
input   dstMat_rows_c_i_full_n;
output   dstMat_rows_c_i_write;
output  [31:0] dstMat_cols_c_i_din;
input   dstMat_cols_c_i_full_n;
output   dstMat_cols_c_i_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg scalar_dstMat_cols_read;
reg dstMat_cols_out_write;
reg scalar_dstMat_rows_read;
reg dstMat_rows_out_write;
reg m_axi_srcPtr_V_ARVALID;
reg m_axi_srcPtr_V_RREADY;
reg srcPtr_V_offset_read;
reg strm_V_V_i_write;
reg dstMat_rows_c_i_write;
reg dstMat_cols_c_i_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    scalar_dstMat_cols_blk_n;
reg    dstMat_cols_out_blk_n;
reg    scalar_dstMat_rows_blk_n;
reg    dstMat_rows_out_blk_n;
reg    srcPtr_V_blk_n_AR;
wire    ap_CS_fsm_state4;
reg    srcPtr_V_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_14_i_i_i_i_i_reg_289;
reg    srcPtr_V_offset_blk_n;
reg    strm_V_V_i_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg;
reg    dstMat_rows_c_i_blk_n;
reg    dstMat_cols_c_i_blk_n;
reg   [28:0] i_i_i_i_i_i_reg_150;
reg   [31:0] srcPtr_V_addr_reg_247;
reg    ap_block_state1;
reg  signed [31:0] scalar_dstMat_cols_r_reg_253;
reg  signed [31:0] scalar_dstMat_rows_r_reg_258;
wire   [31:0] tmp_1_i_i_i_i_i_fu_171_p2;
reg   [31:0] tmp_1_i_i_i_i_i_reg_263;
wire    ap_CS_fsm_state2;
wire   [28:0] tmp_fu_175_p1;
reg   [28:0] tmp_reg_268;
reg   [0:0] tmp_8_reg_273;
wire   [29:0] loop_count_fu_221_p3;
reg   [29:0] loop_count_reg_278;
wire    ap_CS_fsm_state3;
reg    ap_sig_ioackin_m_axi_srcPtr_V_ARREADY;
wire   [0:0] tmp_14_i_i_i_i_i_fu_236_p2;
wire    ap_block_state11_pp0_stage0_iter0;
reg    ap_block_state12_pp0_stage0_iter1;
reg    ap_block_state13_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [28:0] i_fu_241_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_V_reg_298;
wire    ap_CS_fsm_state10;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state11;
wire  signed [63:0] tmp_i_fu_161_p1;
reg    ap_reg_ioackin_m_axi_srcPtr_V_ARREADY;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_7_fu_190_p2;
wire   [31:0] p_neg_i_i_i_i_i_fu_195_p2;
wire   [28:0] tmp_6_i_fu_201_p4;
wire   [29:0] p_lshr_cast_i_i_i_i_i_fu_211_p1;
wire   [29:0] p_neg_t_i_i_i_i_i_fu_215_p2;
wire   [29:0] tmp_13_cast_i_i_i_i_s_fu_187_p1;
wire   [29:0] i_cast_i_i_i_i_i_fu_232_p1;
wire    ap_CS_fsm_state14;
reg   [11:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_reg_ioackin_m_axi_srcPtr_V_ARREADY = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state11) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state11)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state11);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_srcPtr_V_ARREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            if ((ap_sig_ioackin_m_axi_srcPtr_V_ARREADY == 1'b1)) begin
                ap_reg_ioackin_m_axi_srcPtr_V_ARREADY <= 1'b0;
            end else if ((m_axi_srcPtr_V_ARREADY == 1'b1)) begin
                ap_reg_ioackin_m_axi_srcPtr_V_ARREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_14_i_i_i_i_i_fu_236_p2 == 1'd1))) begin
        i_i_i_i_i_i_reg_150 <= i_fu_241_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        i_i_i_i_i_i_reg_150 <= 29'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        loop_count_reg_278 <= loop_count_fu_221_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scalar_dstMat_cols_r_reg_253 <= scalar_dstMat_cols_dout;
        scalar_dstMat_rows_r_reg_258 <= scalar_dstMat_rows_dout;
        srcPtr_V_addr_reg_247 <= tmp_i_fu_161_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_14_i_i_i_i_i_reg_289 <= tmp_14_i_i_i_i_i_fu_236_p2;
        tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg <= tmp_14_i_i_i_i_i_reg_289;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_1_i_i_i_i_i_reg_263 <= tmp_1_i_i_i_i_i_fu_171_p2;
        tmp_8_reg_273 <= tmp_1_i_i_i_i_i_fu_171_p2[32'd28];
        tmp_reg_268 <= tmp_fu_175_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_14_i_i_i_i_i_reg_289 == 1'd1))) begin
        tmp_V_reg_298 <= m_axi_srcPtr_V_RDATA;
    end
end

always @ (*) begin
    if ((tmp_14_i_i_i_i_i_fu_236_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state11 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state11 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_m_axi_srcPtr_V_ARREADY == 1'b0)) begin
        ap_sig_ioackin_m_axi_srcPtr_V_ARREADY = m_axi_srcPtr_V_ARREADY;
    end else begin
        ap_sig_ioackin_m_axi_srcPtr_V_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstMat_cols_c_i_blk_n = dstMat_cols_c_i_full_n;
    end else begin
        dstMat_cols_c_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstMat_cols_c_i_write = 1'b1;
    end else begin
        dstMat_cols_c_i_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstMat_cols_out_blk_n = dstMat_cols_out_full_n;
    end else begin
        dstMat_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstMat_cols_out_write = 1'b1;
    end else begin
        dstMat_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstMat_rows_c_i_blk_n = dstMat_rows_c_i_full_n;
    end else begin
        dstMat_rows_c_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstMat_rows_c_i_write = 1'b1;
    end else begin
        dstMat_rows_c_i_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstMat_rows_out_blk_n = dstMat_rows_out_full_n;
    end else begin
        dstMat_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstMat_rows_out_write = 1'b1;
    end else begin
        dstMat_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_m_axi_srcPtr_V_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_srcPtr_V_ARVALID = 1'b1;
    end else begin
        m_axi_srcPtr_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_14_i_i_i_i_i_reg_289 == 1'd1))) begin
        m_axi_srcPtr_V_RREADY = 1'b1;
    end else begin
        m_axi_srcPtr_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scalar_dstMat_cols_blk_n = scalar_dstMat_cols_empty_n;
    end else begin
        scalar_dstMat_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scalar_dstMat_cols_read = 1'b1;
    end else begin
        scalar_dstMat_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scalar_dstMat_rows_blk_n = scalar_dstMat_rows_empty_n;
    end else begin
        scalar_dstMat_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scalar_dstMat_rows_read = 1'b1;
    end else begin
        scalar_dstMat_rows_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        srcPtr_V_blk_n_AR = m_axi_srcPtr_V_ARREADY;
    end else begin
        srcPtr_V_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_14_i_i_i_i_i_reg_289 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        srcPtr_V_blk_n_R = m_axi_srcPtr_V_RVALID;
    end else begin
        srcPtr_V_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcPtr_V_offset_blk_n = srcPtr_V_offset_empty_n;
    end else begin
        srcPtr_V_offset_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcPtr_V_offset_read = 1'b1;
    end else begin
        srcPtr_V_offset_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        strm_V_V_i_blk_n = strm_V_V_i_full_n;
    end else begin
        strm_V_V_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg == 1'd1))) begin
        strm_V_V_i_write = 1'b1;
    end else begin
        strm_V_V_i_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((ap_sig_ioackin_m_axi_srcPtr_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (tmp_14_i_i_i_i_i_fu_236_p2 == 1'd0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (tmp_14_i_i_i_i_i_fu_236_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((strm_V_V_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg == 1'd1)) | ((m_axi_srcPtr_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_14_i_i_i_i_i_reg_289 == 1'd1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((strm_V_V_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg == 1'd1)) | ((m_axi_srcPtr_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_14_i_i_i_i_i_reg_289 == 1'd1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((strm_V_V_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg == 1'd1)) | ((m_axi_srcPtr_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_14_i_i_i_i_i_reg_289 == 1'd1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (dstMat_rows_out_full_n == 1'b0) | (scalar_dstMat_rows_empty_n == 1'b0) | (dstMat_cols_out_full_n == 1'b0) | (scalar_dstMat_cols_empty_n == 1'b0) | (real_start == 1'b0) | (dstMat_cols_c_i_full_n == 1'b0) | (dstMat_rows_c_i_full_n == 1'b0) | (srcPtr_V_offset_empty_n == 1'b0));
end

assign ap_block_state11_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter1 = ((m_axi_srcPtr_V_RVALID == 1'b0) & (tmp_14_i_i_i_i_i_reg_289 == 1'd1));
end

always @ (*) begin
    ap_block_state13_pp0_stage0_iter2 = ((strm_V_V_i_full_n == 1'b0) & (tmp_14_i_i_i_i_i_reg_289_pp0_iter1_reg == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign dstMat_cols_c_i_din = scalar_dstMat_cols_dout;

assign dstMat_cols_out_din = scalar_dstMat_cols_dout;

assign dstMat_rows_c_i_din = scalar_dstMat_rows_dout;

assign dstMat_rows_out_din = scalar_dstMat_rows_dout;

assign i_cast_i_i_i_i_i_fu_232_p1 = i_i_i_i_i_i_reg_150;

assign i_fu_241_p2 = (i_i_i_i_i_i_reg_150 + 29'd1);

assign loop_count_fu_221_p3 = ((tmp_8_reg_273[0:0] === 1'b1) ? p_neg_t_i_i_i_i_i_fu_215_p2 : tmp_13_cast_i_i_i_i_s_fu_187_p1);

assign m_axi_srcPtr_V_ARADDR = srcPtr_V_addr_reg_247;

assign m_axi_srcPtr_V_ARBURST = 2'd0;

assign m_axi_srcPtr_V_ARCACHE = 4'd0;

assign m_axi_srcPtr_V_ARID = 1'd0;

assign m_axi_srcPtr_V_ARLEN = loop_count_reg_278;

assign m_axi_srcPtr_V_ARLOCK = 2'd0;

assign m_axi_srcPtr_V_ARPROT = 3'd0;

assign m_axi_srcPtr_V_ARQOS = 4'd0;

assign m_axi_srcPtr_V_ARREGION = 4'd0;

assign m_axi_srcPtr_V_ARSIZE = 3'd0;

assign m_axi_srcPtr_V_ARUSER = 1'd0;

assign m_axi_srcPtr_V_AWADDR = 32'd0;

assign m_axi_srcPtr_V_AWBURST = 2'd0;

assign m_axi_srcPtr_V_AWCACHE = 4'd0;

assign m_axi_srcPtr_V_AWID = 1'd0;

assign m_axi_srcPtr_V_AWLEN = 32'd0;

assign m_axi_srcPtr_V_AWLOCK = 2'd0;

assign m_axi_srcPtr_V_AWPROT = 3'd0;

assign m_axi_srcPtr_V_AWQOS = 4'd0;

assign m_axi_srcPtr_V_AWREGION = 4'd0;

assign m_axi_srcPtr_V_AWSIZE = 3'd0;

assign m_axi_srcPtr_V_AWUSER = 1'd0;

assign m_axi_srcPtr_V_AWVALID = 1'b0;

assign m_axi_srcPtr_V_BREADY = 1'b0;

assign m_axi_srcPtr_V_WDATA = 8'd0;

assign m_axi_srcPtr_V_WID = 1'd0;

assign m_axi_srcPtr_V_WLAST = 1'b0;

assign m_axi_srcPtr_V_WSTRB = 1'd0;

assign m_axi_srcPtr_V_WUSER = 1'd0;

assign m_axi_srcPtr_V_WVALID = 1'b0;

assign p_lshr_cast_i_i_i_i_i_fu_211_p1 = tmp_6_i_fu_201_p4;

assign p_neg_i_i_i_i_i_fu_195_p2 = (32'd0 - tmp_7_fu_190_p2);

assign p_neg_t_i_i_i_i_i_fu_215_p2 = (30'd0 - p_lshr_cast_i_i_i_i_i_fu_211_p1);

assign start_out = real_start;

assign strm_V_V_i_din = tmp_V_reg_298;

assign tmp_13_cast_i_i_i_i_s_fu_187_p1 = tmp_reg_268;

assign tmp_14_i_i_i_i_i_fu_236_p2 = (($signed(i_cast_i_i_i_i_i_fu_232_p1) < $signed(loop_count_reg_278)) ? 1'b1 : 1'b0);

assign tmp_1_i_i_i_i_i_fu_171_p2 = ($signed(scalar_dstMat_cols_r_reg_253) * $signed(scalar_dstMat_rows_r_reg_258));

assign tmp_6_i_fu_201_p4 = {{p_neg_i_i_i_i_i_fu_195_p2[31:3]}};

assign tmp_7_fu_190_p2 = tmp_1_i_i_i_i_i_reg_263 << 32'd3;

assign tmp_fu_175_p1 = tmp_1_i_i_i_i_i_fu_171_p2[28:0];

assign tmp_i_fu_161_p1 = $signed(srcPtr_V_offset_dout);

endmodule //Array2hlsStrm54
