// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xfMat2Array (
        srcMat_rows_dout,
        srcMat_rows_empty_n,
        srcMat_rows_read,
        srcMat_cols_dout,
        srcMat_cols_empty_n,
        srcMat_cols_read,
        srcMat_data_V_address0,
        srcMat_data_V_ce0,
        srcMat_data_V_d0,
        srcMat_data_V_q0,
        srcMat_data_V_we0,
        srcMat_data_V_address1,
        srcMat_data_V_ce1,
        srcMat_data_V_d1,
        srcMat_data_V_q1,
        srcMat_data_V_we1,
        m_axi_dstPtr_V_AWVALID,
        m_axi_dstPtr_V_AWREADY,
        m_axi_dstPtr_V_AWADDR,
        m_axi_dstPtr_V_AWID,
        m_axi_dstPtr_V_AWLEN,
        m_axi_dstPtr_V_AWSIZE,
        m_axi_dstPtr_V_AWBURST,
        m_axi_dstPtr_V_AWLOCK,
        m_axi_dstPtr_V_AWCACHE,
        m_axi_dstPtr_V_AWPROT,
        m_axi_dstPtr_V_AWQOS,
        m_axi_dstPtr_V_AWREGION,
        m_axi_dstPtr_V_AWUSER,
        m_axi_dstPtr_V_WVALID,
        m_axi_dstPtr_V_WREADY,
        m_axi_dstPtr_V_WDATA,
        m_axi_dstPtr_V_WSTRB,
        m_axi_dstPtr_V_WLAST,
        m_axi_dstPtr_V_WID,
        m_axi_dstPtr_V_WUSER,
        m_axi_dstPtr_V_ARVALID,
        m_axi_dstPtr_V_ARREADY,
        m_axi_dstPtr_V_ARADDR,
        m_axi_dstPtr_V_ARID,
        m_axi_dstPtr_V_ARLEN,
        m_axi_dstPtr_V_ARSIZE,
        m_axi_dstPtr_V_ARBURST,
        m_axi_dstPtr_V_ARLOCK,
        m_axi_dstPtr_V_ARCACHE,
        m_axi_dstPtr_V_ARPROT,
        m_axi_dstPtr_V_ARQOS,
        m_axi_dstPtr_V_ARREGION,
        m_axi_dstPtr_V_ARUSER,
        m_axi_dstPtr_V_RVALID,
        m_axi_dstPtr_V_RREADY,
        m_axi_dstPtr_V_RDATA,
        m_axi_dstPtr_V_RLAST,
        m_axi_dstPtr_V_RID,
        m_axi_dstPtr_V_RUSER,
        m_axi_dstPtr_V_RRESP,
        m_axi_dstPtr_V_BVALID,
        m_axi_dstPtr_V_BREADY,
        m_axi_dstPtr_V_BRESP,
        m_axi_dstPtr_V_BID,
        m_axi_dstPtr_V_BUSER,
        dstPtr_V_offset_dout,
        dstPtr_V_offset_empty_n,
        dstPtr_V_offset_read,
        ap_clk,
        ap_rst,
        srcMat_data_V_empty_n,
        srcMat_data_V_read,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] srcMat_rows_dout;
input   srcMat_rows_empty_n;
output   srcMat_rows_read;
input  [31:0] srcMat_cols_dout;
input   srcMat_cols_empty_n;
output   srcMat_cols_read;
output  [19:0] srcMat_data_V_address0;
output   srcMat_data_V_ce0;
output  [0:0] srcMat_data_V_d0;
input  [0:0] srcMat_data_V_q0;
output   srcMat_data_V_we0;
output  [19:0] srcMat_data_V_address1;
output   srcMat_data_V_ce1;
output  [0:0] srcMat_data_V_d1;
input  [0:0] srcMat_data_V_q1;
output   srcMat_data_V_we1;
output   m_axi_dstPtr_V_AWVALID;
input   m_axi_dstPtr_V_AWREADY;
output  [31:0] m_axi_dstPtr_V_AWADDR;
output  [0:0] m_axi_dstPtr_V_AWID;
output  [31:0] m_axi_dstPtr_V_AWLEN;
output  [2:0] m_axi_dstPtr_V_AWSIZE;
output  [1:0] m_axi_dstPtr_V_AWBURST;
output  [1:0] m_axi_dstPtr_V_AWLOCK;
output  [3:0] m_axi_dstPtr_V_AWCACHE;
output  [2:0] m_axi_dstPtr_V_AWPROT;
output  [3:0] m_axi_dstPtr_V_AWQOS;
output  [3:0] m_axi_dstPtr_V_AWREGION;
output  [0:0] m_axi_dstPtr_V_AWUSER;
output   m_axi_dstPtr_V_WVALID;
input   m_axi_dstPtr_V_WREADY;
output  [7:0] m_axi_dstPtr_V_WDATA;
output  [0:0] m_axi_dstPtr_V_WSTRB;
output   m_axi_dstPtr_V_WLAST;
output  [0:0] m_axi_dstPtr_V_WID;
output  [0:0] m_axi_dstPtr_V_WUSER;
output   m_axi_dstPtr_V_ARVALID;
input   m_axi_dstPtr_V_ARREADY;
output  [31:0] m_axi_dstPtr_V_ARADDR;
output  [0:0] m_axi_dstPtr_V_ARID;
output  [31:0] m_axi_dstPtr_V_ARLEN;
output  [2:0] m_axi_dstPtr_V_ARSIZE;
output  [1:0] m_axi_dstPtr_V_ARBURST;
output  [1:0] m_axi_dstPtr_V_ARLOCK;
output  [3:0] m_axi_dstPtr_V_ARCACHE;
output  [2:0] m_axi_dstPtr_V_ARPROT;
output  [3:0] m_axi_dstPtr_V_ARQOS;
output  [3:0] m_axi_dstPtr_V_ARREGION;
output  [0:0] m_axi_dstPtr_V_ARUSER;
input   m_axi_dstPtr_V_RVALID;
output   m_axi_dstPtr_V_RREADY;
input  [7:0] m_axi_dstPtr_V_RDATA;
input   m_axi_dstPtr_V_RLAST;
input  [0:0] m_axi_dstPtr_V_RID;
input  [0:0] m_axi_dstPtr_V_RUSER;
input  [1:0] m_axi_dstPtr_V_RRESP;
input   m_axi_dstPtr_V_BVALID;
output   m_axi_dstPtr_V_BREADY;
input  [1:0] m_axi_dstPtr_V_BRESP;
input  [0:0] m_axi_dstPtr_V_BID;
input  [0:0] m_axi_dstPtr_V_BUSER;
input  [31:0] dstPtr_V_offset_dout;
input   dstPtr_V_offset_empty_n;
output   dstPtr_V_offset_read;
input   ap_clk;
input   ap_rst;
input   srcMat_data_V_empty_n;
output   srcMat_data_V_read;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    xfMat2hlsStrm9_U0_ap_start;
wire    xfMat2hlsStrm9_U0_ap_done;
wire    xfMat2hlsStrm9_U0_ap_continue;
wire    xfMat2hlsStrm9_U0_ap_idle;
wire    xfMat2hlsStrm9_U0_ap_ready;
wire    xfMat2hlsStrm9_U0_start_out;
wire    xfMat2hlsStrm9_U0_start_write;
wire    xfMat2hlsStrm9_U0_srcMat_rows_read;
wire    xfMat2hlsStrm9_U0_srcMat_cols_read;
wire   [19:0] xfMat2hlsStrm9_U0_srcMat_data_V_address0;
wire    xfMat2hlsStrm9_U0_srcMat_data_V_ce0;
wire   [7:0] xfMat2hlsStrm9_U0_dstStrm_V_V_din;
wire    xfMat2hlsStrm9_U0_dstStrm_V_V_write;
wire   [31:0] xfMat2hlsStrm9_U0_srcMat_rows_out_din;
wire    xfMat2hlsStrm9_U0_srcMat_rows_out_write;
wire   [31:0] xfMat2hlsStrm9_U0_srcMat_cols_out_din;
wire    xfMat2hlsStrm9_U0_srcMat_cols_out_write;
wire    xfMat2hlsStrm9_U0_dstPtr_V_offset_read;
wire   [31:0] xfMat2hlsStrm9_U0_dstPtr_V_offset_out_din;
wire    xfMat2hlsStrm9_U0_dstPtr_V_offset_out_write;
wire    xfMat2hlsStrm9_U0_srcMat_data_V_full_n;
wire    xfMat2hlsStrm9_U0_srcMat_data_V_write;
wire    hlsStrm2Array_U0_ap_start;
wire    hlsStrm2Array_U0_ap_done;
wire    hlsStrm2Array_U0_ap_continue;
wire    hlsStrm2Array_U0_ap_idle;
wire    hlsStrm2Array_U0_ap_ready;
wire    hlsStrm2Array_U0_srcStrm_V_V_read;
wire    hlsStrm2Array_U0_m_axi_dstPtr_V_AWVALID;
wire   [31:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWADDR;
wire   [0:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWID;
wire   [31:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWLEN;
wire   [2:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWSIZE;
wire   [1:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWBURST;
wire   [1:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWLOCK;
wire   [3:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWCACHE;
wire   [2:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWPROT;
wire   [3:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWQOS;
wire   [3:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWREGION;
wire   [0:0] hlsStrm2Array_U0_m_axi_dstPtr_V_AWUSER;
wire    hlsStrm2Array_U0_m_axi_dstPtr_V_WVALID;
wire   [7:0] hlsStrm2Array_U0_m_axi_dstPtr_V_WDATA;
wire   [0:0] hlsStrm2Array_U0_m_axi_dstPtr_V_WSTRB;
wire    hlsStrm2Array_U0_m_axi_dstPtr_V_WLAST;
wire   [0:0] hlsStrm2Array_U0_m_axi_dstPtr_V_WID;
wire   [0:0] hlsStrm2Array_U0_m_axi_dstPtr_V_WUSER;
wire    hlsStrm2Array_U0_m_axi_dstPtr_V_ARVALID;
wire   [31:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARADDR;
wire   [0:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARID;
wire   [31:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARLEN;
wire   [2:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARSIZE;
wire   [1:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARBURST;
wire   [1:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARLOCK;
wire   [3:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARCACHE;
wire   [2:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARPROT;
wire   [3:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARQOS;
wire   [3:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARREGION;
wire   [0:0] hlsStrm2Array_U0_m_axi_dstPtr_V_ARUSER;
wire    hlsStrm2Array_U0_m_axi_dstPtr_V_RREADY;
wire    hlsStrm2Array_U0_m_axi_dstPtr_V_BREADY;
wire    hlsStrm2Array_U0_dstPtr_V_offset_read;
wire    hlsStrm2Array_U0_srcMat_rows_read;
wire    hlsStrm2Array_U0_srcMat_cols_read;
wire    ap_sync_continue;
wire    strm_V_V_full_n;
wire   [7:0] strm_V_V_dout;
wire    strm_V_V_empty_n;
wire    srcMat_rows_c_i_i_full_n;
wire   [31:0] srcMat_rows_c_i_i_dout;
wire    srcMat_rows_c_i_i_empty_n;
wire    srcMat_cols_c_i_i_full_n;
wire   [31:0] srcMat_cols_c_i_i_dout;
wire    srcMat_cols_c_i_i_empty_n;
wire    dstPtr_V_offset_c_i_full_n;
wire   [31:0] dstPtr_V_offset_c_i_dout;
wire    dstPtr_V_offset_c_i_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_hlsStrm2Array_U0_din;
wire    start_for_hlsStrm2Array_U0_full_n;
wire   [0:0] start_for_hlsStrm2Array_U0_dout;
wire    start_for_hlsStrm2Array_U0_empty_n;
wire    hlsStrm2Array_U0_start_full_n;
wire    hlsStrm2Array_U0_start_write;

xfMat2hlsStrm9 xfMat2hlsStrm9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xfMat2hlsStrm9_U0_ap_start),
    .start_full_n(start_for_hlsStrm2Array_U0_full_n),
    .ap_done(xfMat2hlsStrm9_U0_ap_done),
    .ap_continue(xfMat2hlsStrm9_U0_ap_continue),
    .ap_idle(xfMat2hlsStrm9_U0_ap_idle),
    .ap_ready(xfMat2hlsStrm9_U0_ap_ready),
    .start_out(xfMat2hlsStrm9_U0_start_out),
    .start_write(xfMat2hlsStrm9_U0_start_write),
    .srcMat_rows_dout(srcMat_rows_dout),
    .srcMat_rows_empty_n(srcMat_rows_empty_n),
    .srcMat_rows_read(xfMat2hlsStrm9_U0_srcMat_rows_read),
    .srcMat_cols_dout(srcMat_cols_dout),
    .srcMat_cols_empty_n(srcMat_cols_empty_n),
    .srcMat_cols_read(xfMat2hlsStrm9_U0_srcMat_cols_read),
    .srcMat_data_V_address0(xfMat2hlsStrm9_U0_srcMat_data_V_address0),
    .srcMat_data_V_ce0(xfMat2hlsStrm9_U0_srcMat_data_V_ce0),
    .srcMat_data_V_q0(srcMat_data_V_q0),
    .dstStrm_V_V_din(xfMat2hlsStrm9_U0_dstStrm_V_V_din),
    .dstStrm_V_V_full_n(strm_V_V_full_n),
    .dstStrm_V_V_write(xfMat2hlsStrm9_U0_dstStrm_V_V_write),
    .srcMat_rows_out_din(xfMat2hlsStrm9_U0_srcMat_rows_out_din),
    .srcMat_rows_out_full_n(srcMat_rows_c_i_i_full_n),
    .srcMat_rows_out_write(xfMat2hlsStrm9_U0_srcMat_rows_out_write),
    .srcMat_cols_out_din(xfMat2hlsStrm9_U0_srcMat_cols_out_din),
    .srcMat_cols_out_full_n(srcMat_cols_c_i_i_full_n),
    .srcMat_cols_out_write(xfMat2hlsStrm9_U0_srcMat_cols_out_write),
    .dstPtr_V_offset_dout(dstPtr_V_offset_dout),
    .dstPtr_V_offset_empty_n(dstPtr_V_offset_empty_n),
    .dstPtr_V_offset_read(xfMat2hlsStrm9_U0_dstPtr_V_offset_read),
    .dstPtr_V_offset_out_din(xfMat2hlsStrm9_U0_dstPtr_V_offset_out_din),
    .dstPtr_V_offset_out_full_n(dstPtr_V_offset_c_i_full_n),
    .dstPtr_V_offset_out_write(xfMat2hlsStrm9_U0_dstPtr_V_offset_out_write)
);

hlsStrm2Array hlsStrm2Array_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(hlsStrm2Array_U0_ap_start),
    .ap_done(hlsStrm2Array_U0_ap_done),
    .ap_continue(hlsStrm2Array_U0_ap_continue),
    .ap_idle(hlsStrm2Array_U0_ap_idle),
    .ap_ready(hlsStrm2Array_U0_ap_ready),
    .srcStrm_V_V_dout(strm_V_V_dout),
    .srcStrm_V_V_empty_n(strm_V_V_empty_n),
    .srcStrm_V_V_read(hlsStrm2Array_U0_srcStrm_V_V_read),
    .m_axi_dstPtr_V_AWVALID(hlsStrm2Array_U0_m_axi_dstPtr_V_AWVALID),
    .m_axi_dstPtr_V_AWREADY(m_axi_dstPtr_V_AWREADY),
    .m_axi_dstPtr_V_AWADDR(hlsStrm2Array_U0_m_axi_dstPtr_V_AWADDR),
    .m_axi_dstPtr_V_AWID(hlsStrm2Array_U0_m_axi_dstPtr_V_AWID),
    .m_axi_dstPtr_V_AWLEN(hlsStrm2Array_U0_m_axi_dstPtr_V_AWLEN),
    .m_axi_dstPtr_V_AWSIZE(hlsStrm2Array_U0_m_axi_dstPtr_V_AWSIZE),
    .m_axi_dstPtr_V_AWBURST(hlsStrm2Array_U0_m_axi_dstPtr_V_AWBURST),
    .m_axi_dstPtr_V_AWLOCK(hlsStrm2Array_U0_m_axi_dstPtr_V_AWLOCK),
    .m_axi_dstPtr_V_AWCACHE(hlsStrm2Array_U0_m_axi_dstPtr_V_AWCACHE),
    .m_axi_dstPtr_V_AWPROT(hlsStrm2Array_U0_m_axi_dstPtr_V_AWPROT),
    .m_axi_dstPtr_V_AWQOS(hlsStrm2Array_U0_m_axi_dstPtr_V_AWQOS),
    .m_axi_dstPtr_V_AWREGION(hlsStrm2Array_U0_m_axi_dstPtr_V_AWREGION),
    .m_axi_dstPtr_V_AWUSER(hlsStrm2Array_U0_m_axi_dstPtr_V_AWUSER),
    .m_axi_dstPtr_V_WVALID(hlsStrm2Array_U0_m_axi_dstPtr_V_WVALID),
    .m_axi_dstPtr_V_WREADY(m_axi_dstPtr_V_WREADY),
    .m_axi_dstPtr_V_WDATA(hlsStrm2Array_U0_m_axi_dstPtr_V_WDATA),
    .m_axi_dstPtr_V_WSTRB(hlsStrm2Array_U0_m_axi_dstPtr_V_WSTRB),
    .m_axi_dstPtr_V_WLAST(hlsStrm2Array_U0_m_axi_dstPtr_V_WLAST),
    .m_axi_dstPtr_V_WID(hlsStrm2Array_U0_m_axi_dstPtr_V_WID),
    .m_axi_dstPtr_V_WUSER(hlsStrm2Array_U0_m_axi_dstPtr_V_WUSER),
    .m_axi_dstPtr_V_ARVALID(hlsStrm2Array_U0_m_axi_dstPtr_V_ARVALID),
    .m_axi_dstPtr_V_ARREADY(1'b0),
    .m_axi_dstPtr_V_ARADDR(hlsStrm2Array_U0_m_axi_dstPtr_V_ARADDR),
    .m_axi_dstPtr_V_ARID(hlsStrm2Array_U0_m_axi_dstPtr_V_ARID),
    .m_axi_dstPtr_V_ARLEN(hlsStrm2Array_U0_m_axi_dstPtr_V_ARLEN),
    .m_axi_dstPtr_V_ARSIZE(hlsStrm2Array_U0_m_axi_dstPtr_V_ARSIZE),
    .m_axi_dstPtr_V_ARBURST(hlsStrm2Array_U0_m_axi_dstPtr_V_ARBURST),
    .m_axi_dstPtr_V_ARLOCK(hlsStrm2Array_U0_m_axi_dstPtr_V_ARLOCK),
    .m_axi_dstPtr_V_ARCACHE(hlsStrm2Array_U0_m_axi_dstPtr_V_ARCACHE),
    .m_axi_dstPtr_V_ARPROT(hlsStrm2Array_U0_m_axi_dstPtr_V_ARPROT),
    .m_axi_dstPtr_V_ARQOS(hlsStrm2Array_U0_m_axi_dstPtr_V_ARQOS),
    .m_axi_dstPtr_V_ARREGION(hlsStrm2Array_U0_m_axi_dstPtr_V_ARREGION),
    .m_axi_dstPtr_V_ARUSER(hlsStrm2Array_U0_m_axi_dstPtr_V_ARUSER),
    .m_axi_dstPtr_V_RVALID(1'b0),
    .m_axi_dstPtr_V_RREADY(hlsStrm2Array_U0_m_axi_dstPtr_V_RREADY),
    .m_axi_dstPtr_V_RDATA(8'd0),
    .m_axi_dstPtr_V_RLAST(1'b0),
    .m_axi_dstPtr_V_RID(1'd0),
    .m_axi_dstPtr_V_RUSER(1'd0),
    .m_axi_dstPtr_V_RRESP(2'd0),
    .m_axi_dstPtr_V_BVALID(m_axi_dstPtr_V_BVALID),
    .m_axi_dstPtr_V_BREADY(hlsStrm2Array_U0_m_axi_dstPtr_V_BREADY),
    .m_axi_dstPtr_V_BRESP(m_axi_dstPtr_V_BRESP),
    .m_axi_dstPtr_V_BID(m_axi_dstPtr_V_BID),
    .m_axi_dstPtr_V_BUSER(m_axi_dstPtr_V_BUSER),
    .dstPtr_V_offset_dout(dstPtr_V_offset_c_i_dout),
    .dstPtr_V_offset_empty_n(dstPtr_V_offset_c_i_empty_n),
    .dstPtr_V_offset_read(hlsStrm2Array_U0_dstPtr_V_offset_read),
    .srcMat_rows_dout(srcMat_rows_c_i_i_dout),
    .srcMat_rows_empty_n(srcMat_rows_c_i_i_empty_n),
    .srcMat_rows_read(hlsStrm2Array_U0_srcMat_rows_read),
    .srcMat_cols_dout(srcMat_cols_c_i_i_dout),
    .srcMat_cols_empty_n(srcMat_cols_c_i_i_empty_n),
    .srcMat_cols_read(hlsStrm2Array_U0_srcMat_cols_read)
);

fifo_w8_d2_A_x strm_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xfMat2hlsStrm9_U0_dstStrm_V_V_din),
    .if_full_n(strm_V_V_full_n),
    .if_write(xfMat2hlsStrm9_U0_dstStrm_V_V_write),
    .if_dout(strm_V_V_dout),
    .if_empty_n(strm_V_V_empty_n),
    .if_read(hlsStrm2Array_U0_srcStrm_V_V_read)
);

fifo_w32_d2_A_x srcMat_rows_c_i_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xfMat2hlsStrm9_U0_srcMat_rows_out_din),
    .if_full_n(srcMat_rows_c_i_i_full_n),
    .if_write(xfMat2hlsStrm9_U0_srcMat_rows_out_write),
    .if_dout(srcMat_rows_c_i_i_dout),
    .if_empty_n(srcMat_rows_c_i_i_empty_n),
    .if_read(hlsStrm2Array_U0_srcMat_rows_read)
);

fifo_w32_d2_A_x srcMat_cols_c_i_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xfMat2hlsStrm9_U0_srcMat_cols_out_din),
    .if_full_n(srcMat_cols_c_i_i_full_n),
    .if_write(xfMat2hlsStrm9_U0_srcMat_cols_out_write),
    .if_dout(srcMat_cols_c_i_i_dout),
    .if_empty_n(srcMat_cols_c_i_i_empty_n),
    .if_read(hlsStrm2Array_U0_srcMat_cols_read)
);

fifo_w32_d2_A_x dstPtr_V_offset_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xfMat2hlsStrm9_U0_dstPtr_V_offset_out_din),
    .if_full_n(dstPtr_V_offset_c_i_full_n),
    .if_write(xfMat2hlsStrm9_U0_dstPtr_V_offset_out_write),
    .if_dout(dstPtr_V_offset_c_i_dout),
    .if_empty_n(dstPtr_V_offset_c_i_empty_n),
    .if_read(hlsStrm2Array_U0_dstPtr_V_offset_read)
);

start_for_hlsStrmcud start_for_hlsStrmcud_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hlsStrm2Array_U0_din),
    .if_full_n(start_for_hlsStrm2Array_U0_full_n),
    .if_write(xfMat2hlsStrm9_U0_start_write),
    .if_dout(start_for_hlsStrm2Array_U0_dout),
    .if_empty_n(start_for_hlsStrm2Array_U0_empty_n),
    .if_read(hlsStrm2Array_U0_ap_ready)
);

assign ap_done = hlsStrm2Array_U0_ap_done;

assign ap_idle = (xfMat2hlsStrm9_U0_ap_idle & hlsStrm2Array_U0_ap_idle);

assign ap_ready = xfMat2hlsStrm9_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = hlsStrm2Array_U0_ap_done;

assign ap_sync_ready = xfMat2hlsStrm9_U0_ap_ready;

assign dstPtr_V_offset_read = xfMat2hlsStrm9_U0_dstPtr_V_offset_read;

assign hlsStrm2Array_U0_ap_continue = ap_continue;

assign hlsStrm2Array_U0_ap_start = start_for_hlsStrm2Array_U0_empty_n;

assign hlsStrm2Array_U0_start_full_n = 1'b1;

assign hlsStrm2Array_U0_start_write = 1'b0;

assign m_axi_dstPtr_V_ARADDR = 32'd0;

assign m_axi_dstPtr_V_ARBURST = 2'd0;

assign m_axi_dstPtr_V_ARCACHE = 4'd0;

assign m_axi_dstPtr_V_ARID = 1'd0;

assign m_axi_dstPtr_V_ARLEN = 32'd0;

assign m_axi_dstPtr_V_ARLOCK = 2'd0;

assign m_axi_dstPtr_V_ARPROT = 3'd0;

assign m_axi_dstPtr_V_ARQOS = 4'd0;

assign m_axi_dstPtr_V_ARREGION = 4'd0;

assign m_axi_dstPtr_V_ARSIZE = 3'd0;

assign m_axi_dstPtr_V_ARUSER = 1'd0;

assign m_axi_dstPtr_V_ARVALID = 1'b0;

assign m_axi_dstPtr_V_AWADDR = hlsStrm2Array_U0_m_axi_dstPtr_V_AWADDR;

assign m_axi_dstPtr_V_AWBURST = hlsStrm2Array_U0_m_axi_dstPtr_V_AWBURST;

assign m_axi_dstPtr_V_AWCACHE = hlsStrm2Array_U0_m_axi_dstPtr_V_AWCACHE;

assign m_axi_dstPtr_V_AWID = hlsStrm2Array_U0_m_axi_dstPtr_V_AWID;

assign m_axi_dstPtr_V_AWLEN = hlsStrm2Array_U0_m_axi_dstPtr_V_AWLEN;

assign m_axi_dstPtr_V_AWLOCK = hlsStrm2Array_U0_m_axi_dstPtr_V_AWLOCK;

assign m_axi_dstPtr_V_AWPROT = hlsStrm2Array_U0_m_axi_dstPtr_V_AWPROT;

assign m_axi_dstPtr_V_AWQOS = hlsStrm2Array_U0_m_axi_dstPtr_V_AWQOS;

assign m_axi_dstPtr_V_AWREGION = hlsStrm2Array_U0_m_axi_dstPtr_V_AWREGION;

assign m_axi_dstPtr_V_AWSIZE = hlsStrm2Array_U0_m_axi_dstPtr_V_AWSIZE;

assign m_axi_dstPtr_V_AWUSER = hlsStrm2Array_U0_m_axi_dstPtr_V_AWUSER;

assign m_axi_dstPtr_V_AWVALID = hlsStrm2Array_U0_m_axi_dstPtr_V_AWVALID;

assign m_axi_dstPtr_V_BREADY = hlsStrm2Array_U0_m_axi_dstPtr_V_BREADY;

assign m_axi_dstPtr_V_RREADY = 1'b0;

assign m_axi_dstPtr_V_WDATA = hlsStrm2Array_U0_m_axi_dstPtr_V_WDATA;

assign m_axi_dstPtr_V_WID = hlsStrm2Array_U0_m_axi_dstPtr_V_WID;

assign m_axi_dstPtr_V_WLAST = hlsStrm2Array_U0_m_axi_dstPtr_V_WLAST;

assign m_axi_dstPtr_V_WSTRB = hlsStrm2Array_U0_m_axi_dstPtr_V_WSTRB;

assign m_axi_dstPtr_V_WUSER = hlsStrm2Array_U0_m_axi_dstPtr_V_WUSER;

assign m_axi_dstPtr_V_WVALID = hlsStrm2Array_U0_m_axi_dstPtr_V_WVALID;

assign srcMat_cols_read = xfMat2hlsStrm9_U0_srcMat_cols_read;

assign srcMat_data_V_address0 = xfMat2hlsStrm9_U0_srcMat_data_V_address0;

assign srcMat_data_V_address1 = 20'd0;

assign srcMat_data_V_ce0 = xfMat2hlsStrm9_U0_srcMat_data_V_ce0;

assign srcMat_data_V_ce1 = 1'b0;

assign srcMat_data_V_d0 = 1'd0;

assign srcMat_data_V_d1 = 1'd0;

assign srcMat_data_V_read = xfMat2hlsStrm9_U0_srcMat_data_V_write;

assign srcMat_data_V_we0 = 1'b0;

assign srcMat_data_V_we1 = 1'b0;

assign srcMat_rows_read = xfMat2hlsStrm9_U0_srcMat_rows_read;

assign start_for_hlsStrm2Array_U0_din = 1'b1;

assign xfMat2hlsStrm9_U0_ap_continue = 1'b1;

assign xfMat2hlsStrm9_U0_ap_start = ap_start;

assign xfMat2hlsStrm9_U0_srcMat_data_V_full_n = srcMat_data_V_empty_n;

assign xfMat2hlsStrm9_U0_srcMat_data_V_write = 1'b0;

endmodule //xfMat2Array
