// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xfMat2hlsStrm9 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcMat_rows_dout,
        srcMat_rows_empty_n,
        srcMat_rows_read,
        srcMat_cols_dout,
        srcMat_cols_empty_n,
        srcMat_cols_read,
        srcMat_data_V_address0,
        srcMat_data_V_ce0,
        srcMat_data_V_q0,
        dstStrm_V_V_din,
        dstStrm_V_V_full_n,
        dstStrm_V_V_write,
        srcMat_rows_out_din,
        srcMat_rows_out_full_n,
        srcMat_rows_out_write,
        srcMat_cols_out_din,
        srcMat_cols_out_full_n,
        srcMat_cols_out_write,
        dstPtr_V_offset_dout,
        dstPtr_V_offset_empty_n,
        dstPtr_V_offset_read,
        dstPtr_V_offset_out_din,
        dstPtr_V_offset_out_full_n,
        dstPtr_V_offset_out_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state6 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] srcMat_rows_dout;
input   srcMat_rows_empty_n;
output   srcMat_rows_read;
input  [31:0] srcMat_cols_dout;
input   srcMat_cols_empty_n;
output   srcMat_cols_read;
output  [19:0] srcMat_data_V_address0;
output   srcMat_data_V_ce0;
input  [0:0] srcMat_data_V_q0;
output  [7:0] dstStrm_V_V_din;
input   dstStrm_V_V_full_n;
output   dstStrm_V_V_write;
output  [31:0] srcMat_rows_out_din;
input   srcMat_rows_out_full_n;
output   srcMat_rows_out_write;
output  [31:0] srcMat_cols_out_din;
input   srcMat_cols_out_full_n;
output   srcMat_cols_out_write;
input  [31:0] dstPtr_V_offset_dout;
input   dstPtr_V_offset_empty_n;
output   dstPtr_V_offset_read;
output  [31:0] dstPtr_V_offset_out_din;
input   dstPtr_V_offset_out_full_n;
output   dstPtr_V_offset_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg srcMat_rows_read;
reg srcMat_cols_read;
reg srcMat_data_V_ce0;
reg dstStrm_V_V_write;
reg srcMat_rows_out_write;
reg srcMat_cols_out_write;
reg dstPtr_V_offset_read;
reg dstPtr_V_offset_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    srcMat_rows_blk_n;
reg    srcMat_cols_blk_n;
reg    dstStrm_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_3_i_i_i_i_reg_282;
reg    srcMat_rows_out_blk_n;
reg    srcMat_cols_out_blk_n;
reg    dstPtr_V_offset_blk_n;
reg    dstPtr_V_offset_out_blk_n;
reg   [29:0] indvars_iv_i_i_i_i_reg_138;
reg   [29:0] idx_out_i_i_i_i_reg_150;
reg  signed [31:0] rows_reg_252;
reg    ap_block_state1;
reg  signed [31:0] cols_reg_257;
wire   [31:0] tmp_i_i_i_i_fu_162_p2;
reg   [31:0] tmp_i_i_i_i_reg_262;
wire    ap_CS_fsm_state2;
wire   [28:0] tmp_fu_166_p1;
reg   [28:0] tmp_reg_267;
reg   [0:0] tmp_2_reg_272;
wire  signed [30:0] loop_count_cast_i_i_s_fu_219_p1;
reg  signed [30:0] loop_count_cast_i_i_s_reg_277;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_3_i_i_i_i_fu_227_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [29:0] indvars_iv_next_i_i_s_fu_237_p2;
reg   [29:0] indvars_iv_next_i_i_s_reg_291;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg   [29:0] ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4;
reg   [29:0] ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4;
wire   [63:0] tmp_6_i_i_i_i_fu_232_p1;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_1_fu_181_p2;
wire   [31:0] p_neg_i_i_i_i_fu_186_p2;
wire   [28:0] tmp_1_i_i_i_fu_192_p4;
wire   [29:0] p_lshr_cast_i_i_i_i_fu_202_p1;
wire   [29:0] p_neg_t_i_i_i_i_fu_206_p2;
wire   [29:0] tmp_4_cast_i_i_i_i_fu_178_p1;
wire   [29:0] loop_count_fu_212_p3;
wire   [30:0] idx_out_cast_i_i_i_i_fu_223_p1;
wire    ap_CS_fsm_state6;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        idx_out_i_i_i_i_reg_150 <= 30'd0;
    end else if (((tmp_3_i_i_i_i_reg_282 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        idx_out_i_i_i_i_reg_150 <= indvars_iv_i_i_i_i_reg_138;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        indvars_iv_i_i_i_i_reg_138 <= 30'd1;
    end else if (((tmp_3_i_i_i_i_reg_282 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvars_iv_i_i_i_i_reg_138 <= indvars_iv_next_i_i_s_reg_291;
    end
end

always @ (posedge ap_clk) begin
    if ((~((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_reg_257 <= srcMat_cols_dout;
        rows_reg_252 <= srcMat_rows_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_i_i_i_i_fu_227_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvars_iv_next_i_i_s_reg_291 <= indvars_iv_next_i_i_s_fu_237_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        loop_count_cast_i_i_s_reg_277 <= loop_count_cast_i_i_s_fu_219_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_2_reg_272 <= tmp_i_i_i_i_fu_162_p2[32'd28];
        tmp_i_i_i_i_reg_262 <= tmp_i_i_i_i_fu_162_p2;
        tmp_reg_267 <= tmp_fu_166_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_3_i_i_i_i_reg_282 <= tmp_3_i_i_i_i_fu_227_p2;
    end
end

always @ (*) begin
    if ((tmp_3_i_i_i_i_fu_227_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_i_i_i_i_reg_282 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4 = indvars_iv_i_i_i_i_reg_138;
    end else begin
        ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4 = idx_out_i_i_i_i_reg_150;
    end
end

always @ (*) begin
    if (((tmp_3_i_i_i_i_reg_282 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4 = indvars_iv_next_i_i_s_reg_291;
    end else begin
        ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4 = indvars_iv_i_i_i_i_reg_138;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstPtr_V_offset_blk_n = dstPtr_V_offset_empty_n;
    end else begin
        dstPtr_V_offset_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstPtr_V_offset_out_blk_n = dstPtr_V_offset_out_full_n;
    end else begin
        dstPtr_V_offset_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstPtr_V_offset_out_write = 1'b1;
    end else begin
        dstPtr_V_offset_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstPtr_V_offset_read = 1'b1;
    end else begin
        dstPtr_V_offset_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_i_i_i_i_reg_282 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dstStrm_V_V_blk_n = dstStrm_V_V_full_n;
    end else begin
        dstStrm_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_3_i_i_i_i_reg_282 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dstStrm_V_V_write = 1'b1;
    end else begin
        dstStrm_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcMat_cols_blk_n = srcMat_cols_empty_n;
    end else begin
        srcMat_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcMat_cols_out_blk_n = srcMat_cols_out_full_n;
    end else begin
        srcMat_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcMat_cols_out_write = 1'b1;
    end else begin
        srcMat_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcMat_cols_read = 1'b1;
    end else begin
        srcMat_cols_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        srcMat_data_V_ce0 = 1'b1;
    end else begin
        srcMat_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcMat_rows_blk_n = srcMat_rows_empty_n;
    end else begin
        srcMat_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcMat_rows_out_blk_n = srcMat_rows_out_full_n;
    end else begin
        srcMat_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcMat_rows_out_write = 1'b1;
    end else begin
        srcMat_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcMat_rows_read = 1'b1;
    end else begin
        srcMat_rows_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (tmp_3_i_i_i_i_fu_227_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (tmp_3_i_i_i_i_fu_227_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((tmp_3_i_i_i_i_reg_282 == 1'd1) & (dstStrm_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((tmp_3_i_i_i_i_reg_282 == 1'd1) & (dstStrm_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((tmp_3_i_i_i_i_reg_282 == 1'd1) & (dstStrm_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((dstPtr_V_offset_out_full_n == 1'b0) | (dstPtr_V_offset_empty_n == 1'b0) | (srcMat_cols_out_full_n == 1'b0) | (srcMat_rows_out_full_n == 1'b0) | (srcMat_cols_empty_n == 1'b0) | (srcMat_rows_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((tmp_3_i_i_i_i_reg_282 == 1'd1) & (dstStrm_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign dstPtr_V_offset_out_din = dstPtr_V_offset_dout;

assign dstStrm_V_V_din = ((srcMat_data_V_q0[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign idx_out_cast_i_i_i_i_fu_223_p1 = ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4;

assign indvars_iv_next_i_i_s_fu_237_p2 = (30'd1 + ap_phi_mux_indvars_iv_i_i_i_i_phi_fu_142_p4);

assign loop_count_cast_i_i_s_fu_219_p1 = $signed(loop_count_fu_212_p3);

assign loop_count_fu_212_p3 = ((tmp_2_reg_272[0:0] === 1'b1) ? p_neg_t_i_i_i_i_fu_206_p2 : tmp_4_cast_i_i_i_i_fu_178_p1);

assign p_lshr_cast_i_i_i_i_fu_202_p1 = tmp_1_i_i_i_fu_192_p4;

assign p_neg_i_i_i_i_fu_186_p2 = (32'd0 - tmp_1_fu_181_p2);

assign p_neg_t_i_i_i_i_fu_206_p2 = (30'd0 - p_lshr_cast_i_i_i_i_fu_202_p1);

assign srcMat_cols_out_din = srcMat_cols_dout;

assign srcMat_data_V_address0 = tmp_6_i_i_i_i_fu_232_p1;

assign srcMat_rows_out_din = srcMat_rows_dout;

assign start_out = real_start;

assign tmp_1_fu_181_p2 = tmp_i_i_i_i_reg_262 << 32'd3;

assign tmp_1_i_i_i_fu_192_p4 = {{p_neg_i_i_i_i_fu_186_p2[31:3]}};

assign tmp_3_i_i_i_i_fu_227_p2 = (($signed(idx_out_cast_i_i_i_i_fu_223_p1) < $signed(loop_count_cast_i_i_s_reg_277)) ? 1'b1 : 1'b0);

assign tmp_4_cast_i_i_i_i_fu_178_p1 = tmp_reg_267;

assign tmp_6_i_i_i_i_fu_232_p1 = ap_phi_mux_idx_out_i_i_i_i_phi_fu_154_p4;

assign tmp_fu_166_p1 = tmp_i_i_i_i_fu_162_p2[28:0];

assign tmp_i_i_i_i_fu_162_p2 = ($signed(rows_reg_252) * $signed(cols_reg_257));

endmodule //xfMat2hlsStrm9
